// nodes/legal_names.js — NOMBRES LEGALES y nombres alternativos → id del grafo
// (Phase 1 · M2, pendiente "Enriquecer alias con nombres legales completos").
//
// El catálogo llama a las empresas por su nombre corto ("TSMC", "Alphabet"),
// pero noticias, reguladores y modelos de IA usan el legal ("Taiwan
// Semiconductor Manufacturing Company", "Google"). Sin esta tabla esos textos
// no se pegaban a su entidad: el resolvedor —correctamente— no adivina.
//
// Una sola tabla para los DOS resolvedores:
//   - navegador: engine/resolve.js (window.LEGAL_NAMES)
//   - servidor:  core/entities.py lee `legal_names` de data/grafo_v0.json,
//                que exporta scripts/export_graph_v0.js desde este archivo.
// Los sufijos societarios (Inc, Corp, Ltd, AG…) ya se quitan solos: no hace
// falta repetir "Nvidia Corporation". Valor = id REAL del grafo; una entrada
// cuyo id no exista se ignora en ambos lados (y un test lo vigila).
window.LEGAL_NAMES = {
  // ── Semiconductores ──────────────────────────────────────────────────────
  'Taiwan Semiconductor Manufacturing Company': 'TSMC',
  'Taiwan Semiconductor Manufacturing': 'TSMC',
  'Taiwan Semiconductor': 'TSMC',
  'Advanced Micro Devices': 'AMD',
  'Samsung': 'Samsung',
  'SK hynix': 'SKHynix',
  'Micron Technology': 'Micron',
  'ASML Holding': 'ASML',
  'Applied Materials': 'AMAT',
  'KLA Corporation': 'KLA',
  'KLA-Tencor': 'KLA',
  'Tokyo Electron Limited': 'TEL',
  'Semiconductor Manufacturing International Corporation': 'SMIC',
  'Semiconductor Manufacturing International': 'SMIC',
  'Arm Holdings': 'ARM',
  'Qualcomm Incorporated': 'Qualcomm',
  'Broadcom Inc': 'Broadcom',
  'Marvell Technology': 'Marvell',
  'Texas Instruments Incorporated': 'TexasInstruments',
  'Infineon Technologies': 'Infineon',
  'ON Semiconductor': 'onsemi',
  'Intel Corporation': 'Intel',
  'Synopsys Inc': 'Synopsys',
  'Cadence Design Systems': 'Cadence',
  'Advantest Corporation': 'Advantest',
  'Amkor Technology': 'Amkor',
  'ASE Group': 'ASE',
  'Advanced Semiconductor Engineering': 'ASE',
  'BE Semiconductor Industries': 'Besi',
  'ASM International NV': 'ASMInt',
  'Shin-Etsu': 'ShinEtsu',
  'Western Digital Corporation': 'WesternDigital',
  'Kioxia Holdings': 'Kioxia',
  'NXP': 'NXP',
  'STMicro': 'STMicroelectronics',
  'ST Microelectronics': 'STMicroelectronics',
  'Monolithic Power Systems': 'MPWR',
  'Lattice Semiconductor Corporation': 'Lattice',
  'Microchip': 'Microchip_Tech',
  'Renesas': 'Renesas',
  'Wolfspeed Inc': 'Wolfspeed',
  'Cree': 'Wolfspeed',
  'Hua Hong': 'HuaHong',
  'ChangXin Memory Technologies': 'CXMT',
  'ChangXin Memory': 'CXMT',
  'Nanya': 'Nanya',
  'Cerebras': 'Cerebras',
  'Credo Technology Group': 'Credo',
  'Astera Labs Inc': 'Astera',
  'Coherent Corp': 'Coherent',
  'II-VI': 'Coherent',
  'Lumentum Holdings': 'Lumentum',
  'Teradyne Inc': 'Teradyne',
  'Entegris Inc': 'Entegris',
  'Lam Research Corporation': 'Lam',

  // ── Hardware, redes, servidores ───────────────────────────────────────────
  'Hon Hai Precision Industry': 'Foxconn',
  'Hon Hai': 'Foxconn',
  'Foxconn': 'Foxconn',
  'Super Micro Computer': 'SuperMicro',
  'Supermicro': 'SuperMicro',
  'Hewlett Packard Enterprise': 'HPE',
  'Dell': 'Dell',
  'Arista': 'Arista',
  'Cisco Systems': 'Cisco',
  'Corning Incorporated': 'Corning',
  'Vertiv Holdings': 'Vertiv',
  'Eaton Corporation': 'Eaton',
  'Schneider': 'Schneider',
  'Amphenol Corporation': 'Amphenol',
  'Quanta Computer Inc': 'Quanta',
  'Lenovo Group': 'Lenovo',
  'Celestica Inc': 'Celestica',
  'Jabil Inc': 'Jabil',
  'Seagate': 'Seagate',

  // ── Nube, software, IA ────────────────────────────────────────────────────
  'Google': 'Alphabet',
  'Google Cloud': 'Alphabet',
  'Alphabet Inc': 'Alphabet',
  'Microsoft Corporation': 'Microsoft',
  'Azure': 'Microsoft',
  'Amazon.com': 'Amazon',
  'Amazon Web Services': 'Amazon',
  'AWS': 'Amazon',
  'Oracle Corporation': 'Oracle',
  'Meta Platforms': 'Meta',
  'Facebook': 'Meta',
  'Apple Inc': 'Apple',
  'Alibaba Group': 'Qwen',
  'Alibaba': 'Qwen',
  'Tencent Holdings': 'Tencent',
  'Baidu Inc': 'Baidu',
  'Palantir Technologies': 'Palantir',
  'CrowdStrike Holdings': 'CrowdStrike',
  'Snowflake Inc': 'Snowflake',
  'Salesforce Inc': 'Salesforce',
  'Palo Alto': 'PaloAltoNetworks',
  'Cloudflare Inc': 'Cloudflare',
  'Equinix Inc': 'Equinix',
  'Digital Realty Trust': 'DigitalRealty',
  'CoreWeave Inc': 'CoreWeave',
  'Nebius Group': 'Nebius',
  'Tesla Inc': 'Tesla',
  'Tesla Motors': 'Tesla',

  // ── Energía ───────────────────────────────────────────────────────────────
  'Constellation Energy Corporation': 'Constellation',
  'GE Vernova Inc': 'GEVernova',
  'Siemens Energy AG': 'SiemensEnergy',
  'Vistra Corp': 'Vistra',
  'NextEra': 'NextEraEnergy',
  'Exxon': 'ExxonMobil',
  'Exxon Mobil': 'ExxonMobil',
  'Chevron Corporation': 'Chevron',
  'Shell plc': 'Shell',
  'Royal Dutch Shell': 'Shell',
  'British Petroleum': 'BP',
  'Aramco': 'SaudiAramco',
  'Saudi Arabian Oil Company': 'SaudiAramco',
  'Petroleo Brasileiro': 'Petrobras',
  'Cameco': 'Cameco',
  'Oklo': 'Oklo',
  'NuScale': 'NuScale',
  'Tokyo Electric Power Company': 'TEPCO',
  'Korea Electric Power Corporation': 'KEPCO',
  'Pacific Gas and Electric': 'PGECorp',

  // ── Materiales y minería ─────────────────────────────────────────────────
  'Freeport': 'FreeportMcMoRan',
  'BHP Group': 'BHP',
  'Rio Tinto Group': 'RioTinto',
  'Vale SA': 'Vale',
  'Albemarle': 'Albemarle',
  'Sociedad Quimica y Minera': 'SQM',
  'MP Materials Corp': 'MP_Materials',
  'Lynas': 'Lynas',

  // ── Finanzas ─────────────────────────────────────────────────────────────
  'JPMorgan Chase': 'JPMorgan',
  'JP Morgan': 'JPMorgan',
  'Goldman Sachs Group': 'GoldmanSachs',
  'Bank of America Corporation': 'BankOfAmerica',
  'BofA': 'BankOfAmerica',
  'Citi': 'Citigroup',
  'Mitsubishi UFJ Financial Group': 'MUFG',
  'Sumitomo Mitsui Banking Corporation': 'SMBC',
  'Blackstone Inc': 'Blackstone',
  'Kohlberg Kravis Roberts': 'KKR',
  'Apollo Global Management': 'ApolloGlobal',
  'Brookfield Asset Management': 'Brookfield',
  'Intercontinental Exchange': 'ICE',
  'London Stock Exchange Group': 'LSEG',
  'S&P Global': 'SPGlobalRatings',
  "Moody's": 'MoodysRatings',
  'Fed': 'FederalReserve',

  // ── Defensa, aeroespacio, espacio ─────────────────────────────────────────
  'Lockheed': 'lockheed-martin',
  'Northrop': 'Northrop',
  'RTX Corporation': 'Raytheon',
  'Raytheon Technologies': 'Raytheon',
  'Space Exploration Technologies': 'SpaceX',
  'The Boeing Company': 'Boeing',
  'Airbus SE': 'Airbus',

  // ── Logística ─────────────────────────────────────────────────────────────
  'A.P. Moller-Maersk': 'Maersk',
  'AP Moller Maersk': 'Maersk',
  'United Parcel Service': 'UPS',
  'Deutsche Post DHL': 'DHL_Group',
  'Federal Express': 'FedEx',
};
