// nodes/links_connect.js — Conexiones de cadena de suministro para nodos huérfanos
// Conecta los ~82 nodos que se habían añadido (expand2/expand3) sin enlaces,
// con relaciones reales verificadas. Formato: {s, t, w, rel, type}
// Convención (igual que links_expand.js): s = empresa, t = aquello de lo que depende
//   (proveedor/fab/cloud/licencia aguas arriba) o su cliente (deploy/customer).
// type ∈ supply | fab | license | cloud | invest | deploy | partner | owns

var LINKS_CONNECT = [
  // ── CANONIZADO (Etapa 2, 2026-07): source PROVEE a target; customer→supply,
  // investor→invest. Direcciones adjudicadas arista por arista (clasificador +
  // revisión manual). Formato uniforme [s, t, w, rel, type]. ──
  // 2026-10-06 (aprobado por Fabrizio): 49 filas seguían escritas [cliente, proveedor] — p. ej.
  // "Wayve→Nvidia: GPU para conducción autónoma" — y se voltearon a [proveedor, cliente].
  ['TSMC','Achronix',3,'Fabrica sus FPGA en TSMC','fab'],
  ['Synopsys','Achronix',2,'Diseña con herramientas EDA de Synopsys','license'],
  ['Achronix','Microsoft',2,'FPGAs para aceleración en data center','supply'],
  ['Arm_Holdings','Apple',5,'Licencia la ISA ARM para sus chips A/M','license'],
  ['Arm_Holdings','Qualcomm',5,'Licencia núcleos ARM para Snapdragon','license'],
  ['Arm_Holdings','Nvidia',4,'CPU Grace basada en ARM','license'],
  ['Arm_Holdings','Samsung',4,'Exynos sobre arquitectura ARM','license'],
  ['Arm_Holdings','MediaTek',4,'Dimensity sobre núcleos ARM','license'],
  ['CEVA','Qualcomm',2,'Licencia DSP IP de CEVA','license'],
  ['CEVA','MediaTek',2,'IP de conectividad y DSP','license'],
  ['Ceva','Samsung',2,'Licencia IP de DSP/Bluetooth','license'],
  ['TSMC','FlexLogix',2,'eFPGA embebida fabricada en TSMC','fab'],
  ['FlexLogix','Boeing',2,'FPGA reconfigurable para aeroespacial','supply'],
  ['TSMC','Himax_Tech',3,'Fabrica drivers de display en TSMC','fab'],
  ['Samsung','Himax_Tech',2,'Capacidad de foundry adicional','fab'],
  ['TSMC','Indie',2,'Chips automotrices fabricados en TSMC','fab'],
  ['Indie','BMW',2,'Semiconductores para ADAS','supply'],
  ['TSMC','Indie_Semi',2,'SoC automotriz fabricado en TSMC','fab'],
  ['Indie_Semi','Stellantis',2,'Chips para sistemas del vehículo','supply'],
  ['Samsung','Lattice',3,'FPGA de bajo consumo en Samsung Foundry','fab'],
  ['TSMC','Lattice',2,'Capacidad de foundry adicional','fab'],
  ['Lattice','Microsoft',2,'FPGA para seguridad de servidores','supply'],
  ['TSMC','Microchip_Tech',3,'Complementa fabs propias con TSMC','fab'],
  ['Microchip_Tech','BMW',2,'Microcontroladores automotrices','supply'],
  ['TSMC','NXP',4,'Procesadores automotrices en TSMC','fab'],
  ['GlobalFoundries','NXP',3,'Capacidad de nodos maduros','fab'],
  ['NXP','BMW',3,'Chips para powertrain y ADAS','supply'],
  ['NXP','Tesla',3,'Microcontroladores del vehículo','supply'],
  ['Rambus','Micron',2,'Licencia IP de interfaz de memoria','license'],
  ['Rambus','SKHynix',2,'IP de memoria de alto ancho de banda','license'],
  ['Rambus','Samsung',2,'Licencia de IP de memoria','license'],
  ['TSMC','Renesas',3,'Complementa fabs propias con TSMC','fab'],
  ['Renesas','BMW',3,'Microcontroladores automotrices','supply'],
  ['Renesas','Hyundai',2,'Chips para el vehículo','supply'],
  ['TSMC','STMicro',2,'Capacidad de foundry adicional','fab'],
  ['STMicro','Apple',2,'Sensores y chips de potencia','supply'],
  ['STMicro','Tesla',3,'SiC para inversores de potencia','supply'],
  ['Sensata','Tesla',2,'Sensores para el vehículo eléctrico','supply'],
  ['Sensata','BMW',2,'Sensores de presión y temperatura','supply'],
  ['TSMC','Silicon_Labs',2,'Chips IoT fabricados en TSMC','fab'],
  ['Silicon_Labs','Amazon',2,'SoC inalámbricos para dispositivos IoT','supply'],
  ['ASML','TataSemiconductor',3,'Litografía para su nueva fab en India','supply'],
  ['AMAT','TataSemiconductor',2,'Equipos de deposición y grabado','supply'],
  ['AMAT','TowerSemi',2,'Equipos para nodos analógicos','supply'],
  ['TowerSemi','Broadcom',2,'Foundry para chips analógicos/RF','fab'],
  ['ASML','Vedanta_Semi',2,'Litografía para fab India (Foxconn JV)','supply'],
  ['AMAT','X_Fab',2,'Equipos para foundry de SiC','supply'],
  ['X_Fab','Tesla',2,'Foundry para chips de potencia','fab'],
  ['ACM_Research','Samsung',2,'Equipos de limpieza de obleas','supply'],
  ['ACM_Research','TSMC',2,'Limpieza húmeda de obleas','supply'],
  ['Aehr_Test','TSMC',2,'Sistemas de burn-in y test','supply'],
  ['Aehr_Test','Intel',2,'Test de fiabilidad de chips','supply'],
  ['Cohu','Samsung',2,'Equipos de handling y test','supply'],
  ['Onto_Innovation','TSMC',2,'Metrología e inspección óptica','supply'],
  ['Onto_Innovation','Samsung',2,'Inspección de packaging avanzado','supply'],
  ['Ultra_Clean','AMAT',5,'Subsistemas y módulos críticos','supply'],
  ['Ultra_Clean','Lam',3,'Componentes para equipos de grabado','supply'],
  ['TSMC','Allegro_Micro',2,'Sensores de corriente en TSMC','fab'],
  ['Allegro_Micro','Tesla',2,'Sensores Hall para motores','supply'],
  ['TSMC','Monolithic_Power',3,'PMIC fabricados en TSMC','fab'],
  ['Monolithic_Power','Nvidia',3,'Gestión de energía para GPU/servidores','supply'],
  ['TSMC','Navitas',2,'GaN/SiC fabricado en TSMC','fab'],
  ['Navitas','Tesla',2,'Semiconductores GaN para carga','supply'],
  ['TSMC','Qorvo',3,'Front-end RF fabricado en TSMC','fab'],
  ['Qorvo','Apple',4,'Módulos RF para iPhone','supply'],
  ['Qorvo','Samsung',2,'RF para Galaxy','supply'],
  ['TSMC','Richtek',2,'PMIC fabricados en TSMC','fab'],
  ['Richtek','MediaTek',2,'Gestión de energía para SoC','supply'],
  ['Rohm','BMW',2,'SiC para inversores EV','supply'],
  ['Rohm','Hyundai',2,'Semiconductores de potencia','supply'],
  ['TSMC','Skyworks',3,'Front-end RF fabricado en TSMC','fab'],
  ['Skyworks','Apple',4,'Amplificadores RF para iPhone','supply'],
  ['AMAT','Nanya',2,'Equipos para DRAM','supply'],
  ['Nanya','Foxconn',2,'DRAM para ensamblaje','supply'],
  ['Winbond','MediaTek',2,'Memoria especializada para SoC','supply'],
  ['TSMC','Winbond',2,'Capacidad de foundry adicional','fab'],
  ['TSMC','GrAI_Matter',2,'Chips neuromórficos en TSMC','fab'],
  ['TSMC','Prophesee',2,'Sensores de visión por eventos','fab'],
  ['Qualcomm','Prophesee',2,'Sensado por eventos para móvil','partner'],
  ['TSMC','Rain_Neuromorphics',2,'Chips analógicos in-memory en TSMC','fab'],
  ['OpenAI','Rain_Neuromorphics',2,'Inversión en hardware neuromórfico','invest'],
  ['TSMC','BroadcomASIC',5,'ASIC de IA fabricados en TSMC','fab'],
  ['BroadcomASIC','Alphabet',5,'Co-diseño de los TPU de Google','supply'],
  ['BroadcomASIC','Meta',4,'ASIC MTIA para inferencia','supply'],
  ['TSMC','Etched',3,'ASIC de transformers (Sohu) en TSMC','fab'],
  ['Etched','Anthropic',2,'Aceleradores de inferencia de transformers','supply'],
  ['TSMC','Graphcore',3,'IPU fabricadas en TSMC','fab'],
  ['SoftBank','Graphcore',3,'Adquirida por SoftBank (2024)','owns'],
  ['TSMC','Esperanto_Tech',2,'Chips RISC-V para IA en TSMC','fab'],
  ['TSMC','Coherus_Bio',2,'Fotónica de silicio en TSMC','fab'],
  ['Coherus_Bio','Nvidia',2,'Óptica co-empaquetada para switches','supply'],
  ['TSMC','InfiniteraNet',2,'DSP ópticos coherentes en TSMC','fab'],
  ['InfiniteraNet','Amazon',2,'Transporte óptico para data centers','supply'],
  ['Altium','Nvidia',2,'Diseño de PCB para placas','license'],
  ['Altium','Apple',2,'Herramientas de diseño de PCB','license'],
  ['PDF_Solutions','TSMC',2,'Analítica de rendimiento de fab','license'],
  ['PDF_Solutions','Samsung',2,'Optimización de yield','license'],
  ['Photronics','TSMC',3,'Fotomáscaras para litografía','supply'],
  ['Photronics','Samsung',2,'Máscaras para procesos avanzados','supply'],
  ['Shinko_Electric','Intel',3,'Sustratos de packaging avanzado','supply'],
  ['Shinko_Electric','TSMC',2,'Sustratos para CoWoS','supply'],
  ['Cabot_Micro','TSMC',3,'Slurry de CMP para pulido','supply'],
  ['Cabot_Micro','Samsung',2,'Consumibles de CMP','supply'],
  ['Cabot_Micro','Intel',2,'Materiales de pulido CMP','supply'],
  ['Arm_Holdings','FujitsuHPC',3,'CPU A64FX (Fugaku) basada en ARM','license'],
  ['TSMC','FujitsuHPC',2,'Fabrica sus CPU HPC en TSMC','fab'],
  ['Nvidia','Penguin_Solutions',3,'Integra clusters de GPU Nvidia','supply'],
  ['Nvidia','Together_AI',3,'Cloud de GPU para entrenamiento','supply'],
  ['Amazon','Together_AI',2,'Infraestructura cloud complementaria','cloud'],
  ['Modine','Nvidia',2,'Refrigeración térmica para racks GPU','supply'],
  ['Modine','Microsoft',2,'Soluciones de enfriamiento de DC','supply'],
  ['Pegatron','Apple',3,'Ensamblaje de productos','supply'],
  ['Quanta_Computer','Nvidia',4,'ODM de servidores DGX/HGX','supply'],
  ['Quanta_Computer','Amazon',3,'Servidores para AWS','supply'],
  ['Supermicro_Liquid','Nvidia',3,'Servidores con refrigeración líquida','supply'],
  ['Supermicro_Liquid','Microsoft',2,'Racks GPU para Azure','supply'],
  ['Wistron','Nvidia',3,'ODM de placas y servidores GPU','supply'],
  ['Wistron','Apple',2,'Ensamblaje de dispositivos','supply'],
  ['ABB_Robotics','BMW',3,'Robots de línea de ensamblaje','supply'],
  ['ABB_Robotics','Nvidia',2,'Isaac para IA de robots','partner'],
  ['Fanuc','Nvidia',2,'IA para automatización industrial','partner'],
  ['Fanuc','Tesla',3,'Robots para Gigafactory','supply'],
  ['Fanuc','Foxconn',3,'Robots de ensamblaje','supply'],
  ['Yaskawa','Nvidia',2,'IA para robótica colaborativa','partner'],
  ['Yaskawa','BMW',2,'Servomotores y robots','supply'],
  ['Nvidia','Joby_Aviation',2,'Cómputo para autonomía eVTOL','supply'],
  ['Joby_Aviation','Qualcomm',2,'Conectividad y cómputo embebido','partner'],
  ['Nvidia','Wayve',3,'GPU para conducción autónoma E2E','supply'],
  ['SoftBank','Wayve',3,'Inversión líder Serie C','invest'],
  ['Microsoft','Wayve',2,'Azure para entrenamiento','cloud'],
  ['Nvidia','AeroVironment',2,'Cómputo de IA para drones','supply'],
  ['AeroVironment','Palantir',2,'Software de misión','partner'],
  ['BoozAllen','Palantir',3,'Integrador de plataformas Palantir','partner'],
  ['Amazon','BoozAllen',2,'Cloud gubernamental (AWS GovCloud)','cloud'],
  ['Nvidia','Kratos',2,'Cómputo para sistemas autónomos','supply'],
  ['Kratos','Boeing',2,'Drones colaborativos de combate','partner'],
  ['Crane_NXT','Microsoft',2,'Cloud para soluciones fintech','cloud'],
  ['Alphabet','TempusAI',3,'Google Cloud para genómica','cloud'],
  ['Nvidia','TempusAI',2,'GPU para modelos clínicos','supply'],
  ['Nvidia','Cohere_AI',3,'GPU para entrenar LLM empresariales','supply'],
  ['Alphabet','Cohere_AI',2,'Google Cloud como infraestructura','cloud'],
  ['Amazon','HuggingFace',3,'AWS como socio de despliegue','cloud'],
  ['Nvidia','HuggingFace',3,'GPU para el hub de modelos','supply'],
  ['Meta','Scale_AI',3,'Etiquetado de datos; Meta invirtió (2025)','invest'],
  ['Scale_AI','OpenAI',3,'Datos de entrenamiento etiquetados','supply'],
  ['SpaceX','Maxar',3,'Lanza sus satélites con SpaceX','supply'],
  ['Maxar','Palantir',2,'Imágenes para análisis geoespacial','partner'],
  ['SpaceX','Spire_Global',3,'Lanzamiento de nanosatélites','supply'],
  ['SpaceX','EutelsatOneWeb',3,'Parte de la constelación lanzada por SpaceX','supply'],
  ['Airbus','EutelsatOneWeb',3,'Airbus fabrica los satélites OneWeb','supply'],
  ['HughesNetwork','SpaceX',2,'Capacidad complementaria de banda','partner'],
  ['SpaceX','Orbcomm',2,'Lanzamiento de satélites IoT','supply'],
  ['SpaceX','SES',3,'Lanza su constelación O3b mPOWER','supply'],
  ['Boeing','SES',2,'Boeing fabrica satélites GEO','supply'],
  ['BlueOrigin','Amazon',3,'Lanza satélites Kuiper en New Glenn','deploy'],
  ['BlueOrigin','Boeing',2,'Socios en ULA (motores BE-4)','partner'],
  ['PiedmontLithium','Tesla',3,'Litio para baterías','supply'],
  ['Umicore','BMW',3,'Materiales catódicos para baterías','supply'],
  ['Umicore','Hyundai',2,'Cátodos para vehículos eléctricos','supply'],
  ['Energy_Fuels','Tesla',2,'Tierras raras para imanes de motor','supply'],
  ['Energy_Fuels','Boeing',2,'Tierras raras para defensa/aero','supply'],
  ['Oxford_Instruments','IBMQuantum',3,'Criostatos de dilución para qubits','supply'],
  ['Oxford_Instruments','Rigetti',2,'Refrigeración criogénica','supply'],
  ['Oxford_Instruments','IonQ',2,'Instrumentación criogénica','supply'],
  ['CommScopeHolding','Ericsson',2,'Infraestructura RAN y antenas','partner'],
  ['CommScopeHolding','Nokia',2,'Conectividad de red fija/móvil','partner'],
  ['TSMC','Qualcomm_Infra',3,'Chips de infraestructura 5G en TSMC','fab'],
  ['Qualcomm_Infra','Ericsson',2,'Soluciones RAN 5G','partner'],
  ['L3Harris','Aerojet',4,'Adquirió Aerojet Rocketdyne (2023, $4.7B)','owns'],
  ['Renesas','Altium',3,'Adquirió Altium (2024, $5.9B)','owns'],
];

if (typeof window !== 'undefined') window.LINKS_CONNECT = LINKS_CONNECT;
