// links_expand.js — Khipu Finance · Supply Chain Links for Expanded Nodes
// ~150+ meaningful supply chain links for nodes in nodes_expand.js and nodes_expand2.js
// Generated 2026-06

var LINKS_EXPAND = [

  // ── AI DEFENSE ──────────────────────────────────────────────────
  {s:"CrowdStrike",       t:"Microsoft",         type:"cloud"},
  {s:"CrowdStrike",       t:"AWS",               type:"cloud"},
  {s:"SentinelOne",       t:"AWS",               type:"cloud"},
  {s:"SentinelOne",       t:"Azure",             type:"cloud"},
  {s:"PaloAltoNetworks",  t:"AWS",               type:"cloud"},
  {s:"Palantir",          t:"AWS",               type:"cloud"},
  {s:"Palantir",          t:"Azure",             type:"cloud"},
  {s:"Palantir_Gov",      t:"AWS",               type:"cloud"},
  {s:"AxonEnterprise",    t:"AWS",               type:"cloud"},
  {s:"Leidos",            t:"Palantir",          type:"partner"},
  {s:"SAIC",              t:"Palantir",          type:"partner"},
  {s:"BAESystems",        t:"Intel",             type:"supply"},
  {s:"BAESystems",        t:"NVIDIA",            type:"supply"},
  {s:"Rheinmetall",       t:"Infineon",          type:"supply"},
  {s:"Rheinmetall",       t:"STMicro",           type:"supply"},
  {s:"Booz_Allen",        t:"Microsoft",         type:"cloud"},
  {s:"Booz_Allen",        t:"AWS",               type:"cloud"},
  {s:"BoozAllen",         t:"Microsoft",         type:"cloud"},
  {s:"BoozAllen",         t:"AWS",               type:"cloud"},
  {s:"Teledyne_Flir",     t:"NVIDIA",            type:"supply"},
  {s:"Leonardo_DRS",      t:"Texas_Instruments", type:"supply"},
  {s:"Leonardo_DRS",      t:"Xilinx",            type:"supply"},
  {s:"Mercury_Systems",   t:"Intel",             type:"supply"},
  {s:"Mercury_Systems",   t:"NVIDIA",            type:"supply"},
  {s:"L3Harris",          t:"Intel",             type:"supply"},
  {s:"L3Harris",          t:"NVIDIA",            type:"supply"},
  {s:"Raytheon",          t:"Intel",             type:"supply"},
  {s:"Raytheon",          t:"Raytheon",          type:"supply"},
  {s:"CACI",              t:"AWS",               type:"cloud"},
  {s:"CACI",              t:"Microsoft",         type:"cloud"},
  {s:"Parsons",           t:"AWS",               type:"cloud"},
  {s:"Thales",            t:"Intel",             type:"supply"},
  {s:"Saab_AB",           t:"Intel",             type:"supply"},

  // ── AI AUTO ──────────────────────────────────────────────────────
  {s:"Waymo",             t:"NVIDIA",            type:"supply"},
  {s:"Waymo",             t:"GCP",               type:"cloud"},
  {s:"Hesai",             t:"TSMC",              type:"supply"},
  {s:"Hesai",             t:"NVIDIA",            type:"supply"},
  {s:"Innoviz",           t:"TSMC",              type:"supply"},
  {s:"Innoviz",           t:"Mobileye_Auto",     type:"partner"},
  {s:"Mobileye_Auto",     t:"TSMC",              type:"supply"},
  {s:"Mobileye_Auto",     t:"Intel",             type:"owns"},
  {s:"Mobileye",          t:"TSMC",              type:"supply"},
  {s:"Mobileye",          t:"Intel",             type:"owns"},
  {s:"Luminar_Lidar",     t:"TSMC",              type:"supply"},
  {s:"Luminar_Lidar",     t:"Infineon",          type:"supply"},
  {s:"Luminar",           t:"TSMC",              type:"supply"},
  {s:"Zoox",              t:"NVIDIA",            type:"supply"},
  {s:"Zoox",              t:"AWS",               type:"cloud"},
  {s:"Nuro",              t:"NVIDIA",            type:"supply"},
  {s:"Nuro",              t:"GCP",               type:"cloud"},
  {s:"Cepton",            t:"TSMC",              type:"supply"},

  // ── AI HEALTH ────────────────────────────────────────────────────
  {s:"Veracyte",          t:"AWS",               type:"cloud"},
  {s:"Veracyte",          t:"NVIDIA",            type:"supply"},
  {s:"ButterflyNetwork",  t:"TSMC",              type:"supply"},
  {s:"ButterflyNetwork",  t:"AWS",               type:"cloud"},
  {s:"Butterfly",         t:"TSMC",              type:"supply"},
  {s:"Butterfly",         t:"AWS",               type:"cloud"},
  {s:"Exscientia",        t:"AWS",               type:"cloud"},
  {s:"Exscientia",        t:"NVIDIA",            type:"supply"},
  {s:"BenevolentAI",      t:"Azure",             type:"cloud"},
  {s:"BenevolentAI",      t:"NVIDIA",            type:"supply"},
  {s:"InsilicoBio",       t:"AWS",               type:"cloud"},
  {s:"InsilicoBio",       t:"NVIDIA",            type:"supply"},
  {s:"Insilico",          t:"AWS",               type:"cloud"},
  {s:"Insilico",          t:"NVIDIA",            type:"supply"},
  {s:"Recursion",         t:"NVIDIA",            type:"supply"},
  {s:"Recursion",         t:"AWS",               type:"cloud"},
  {s:"PathAI",            t:"AWS",               type:"cloud"},
  {s:"PathAI",            t:"NVIDIA",            type:"supply"},
  {s:"Tempus",            t:"AWS",               type:"cloud"},
  {s:"Tempus",            t:"NVIDIA",            type:"supply"},

  // ── PHOTONICS ────────────────────────────────────────────────────
  {s:"Coherent",          t:"TSMC",              type:"supply"},
  {s:"Lumentum",          t:"TSMC",              type:"supply"},
  {s:"Lumentum",          t:"Apple",             type:"customer"},
  {s:"ViaviSolutions",    t:"Ciena",             type:"customer"},
  {s:"Viavi",             t:"Ciena",             type:"customer"},
  {s:"AyarLabs",          t:"TSMC",              type:"supply"},
  {s:"AyarLabs",          t:"NVIDIA",            type:"customer"},
  {s:"RockleyPhotonics",  t:"TSMC",              type:"supply"},
  {s:"Lightelligence",    t:"TSMC",              type:"supply"},

  // ── ASIC / CUSTOM SILICON ────────────────────────────────────────
  {s:"Tenstorrent",       t:"TSMC",              type:"supply"},
  {s:"Tenstorrent",       t:"Samsung",           type:"supply"},
  {s:"dMatrix",           t:"TSMC",              type:"supply"},
  {s:"dMatrix",           t:"Microsoft",         type:"customer"},
  {s:"Hailo",             t:"TSMC",              type:"supply"},
  {s:"SiMa",              t:"TSMC",              type:"supply"},
  {s:"Groq_AI",           t:"TSMC",              type:"supply"},
  {s:"Groq_AI",           t:"AWS",               type:"cloud"},
  {s:"Groq",              t:"TSMC",              type:"supply"},
  {s:"Cerebras",          t:"TSMC",              type:"supply"},
  {s:"SambaNova",         t:"TSMC",              type:"supply"},
  {s:"AmpereComputing",   t:"TSMC",              type:"supply"},
  {s:"Ampere_Computing",  t:"TSMC",              type:"supply"},
  {s:"Untether_AI",       t:"Samsung",           type:"supply"},
  {s:"Mythic",            t:"TSMC",              type:"supply"},
  {s:"BrainChip",         t:"TSMC",              type:"supply"},
  {s:"Kneron",            t:"TSMC",              type:"supply"},
  {s:"Esperanto",         t:"TSMC",              type:"supply"},
  {s:"EsperantoTech",     t:"TSMC",              type:"supply"},
  {s:"GreenWaves",        t:"TSMC",              type:"supply"},
  {s:"Innatera",          t:"TSMC",              type:"supply"},
  {s:"EdgeImpulse",       t:"AWS",               type:"cloud"},
  {s:"Syntiant",          t:"TSMC",              type:"supply"},

  // ── CDN / EDGE ───────────────────────────────────────────────────
  {s:"Cloudflare",        t:"Intel",             type:"supply"},
  {s:"Cloudflare",        t:"AMD",               type:"supply"},
  {s:"Akamai",            t:"Intel",             type:"supply"},
  {s:"Akamai",            t:"AWS",               type:"cloud"},
  {s:"Fastly",            t:"AWS",               type:"cloud"},
  {s:"Fastly",            t:"GCP",               type:"cloud"},
  {s:"Zscaler",           t:"AWS",               type:"cloud"},
  {s:"Zscaler",           t:"Azure",             type:"cloud"},
  {s:"Edgio",             t:"AWS",               type:"cloud"},

  // ── DC REITs ─────────────────────────────────────────────────────
  {s:"Equinix",           t:"Vertiv",            type:"supply"},
  {s:"Equinix",           t:"EatonCorp",         type:"supply"},
  {s:"DigitalRealty",     t:"Vertiv",            type:"supply"},
  {s:"DigitalRealty",     t:"Schneider",         type:"supply"},
  {s:"IronMountain",      t:"Vertiv",            type:"supply"},
  {s:"CoreWeave",         t:"NVIDIA",            type:"supply"},
  {s:"CoreWeave",         t:"Equinix",           type:"customer"},
  {s:"LambdaLabs",        t:"NVIDIA",            type:"supply"},
  {s:"LambdaLabs",        t:"DigitalRealty",     type:"customer"},
  {s:"CyrusOne",          t:"Vertiv",            type:"supply"},
  {s:"QTS",               t:"Vertiv",            type:"supply"},
  {s:"DataBank",          t:"Vertiv",            type:"supply"},
  {s:"Switch",            t:"Vertiv",            type:"supply"},

  // ── POWER / ENERGY ───────────────────────────────────────────────
  {s:"Vertiv",            t:"EatonCorp",         type:"supply"},
  {s:"Vertiv",            t:"NVIDIA",            type:"customer"},
  {s:"Vertiv",            t:"Equinix",           type:"customer"},
  {s:"EatonCorp",         t:"Schneider",         type:"partner"},
  {s:"NexTracker",        t:"First_Solar",       type:"partner"},
  {s:"Lightsource_BP",    t:"SMA_Solar",         type:"supply"},
  {s:"Array_Technologies",t:"First_Solar",       type:"partner"},

  // ── SPACE ────────────────────────────────────────────────────────
  {s:"Firefly",           t:"Northrop",          type:"supply"},
  {s:"Firefly",           t:"Aerojet",           type:"supply"},
  {s:"RelativitySpace",   t:"Aerojet",           type:"supply"},
  {s:"RelativitySpace",   t:"AWS",               type:"cloud"},
  {s:"Relativity",        t:"AWS",               type:"cloud"},
  {s:"StokSpace",         t:"AWS",               type:"cloud"},
  {s:"StokSpace",         t:"Boeing",            type:"supply"},
  {s:"HawkEye360",        t:"SpaceX",            type:"supply"},
  {s:"HawkEye360",        t:"AWS",               type:"cloud"},
  {s:"Umbra",             t:"RocketLab",         type:"supply"},
  {s:"Umbra",             t:"AWS",               type:"cloud"},
  {s:"SpireGlobal",       t:"SpaceX",            type:"supply"},
  {s:"SpireGlobal",       t:"AWS",               type:"cloud"},
  {s:"Satellogic",        t:"SpaceX",            type:"supply"},
  {s:"ViaSatCom",         t:"Boeing",            type:"supply"},
  {s:"ViaSatCom",         t:"SpaceX",            type:"supply"},
  {s:"Viasat",            t:"Boeing",            type:"supply"},
  {s:"Viasat",            t:"SpaceX",            type:"supply"},
  {s:"CapellaSpace",      t:"SpaceX",            type:"supply"},
  {s:"CapellaSpace",      t:"AWS",               type:"cloud"},
  {s:"Iridium",           t:"SpaceX",            type:"supply"},
  {s:"Eutelsat",          t:"SpaceX",            type:"supply"},
  {s:"RocketLab",         t:"Electron",          type:"supply"},
  {s:"ULA",               t:"Boeing",            type:"owns"},
  {s:"ULA",               t:"Northrop",          type:"supply"},

  // ── SEMICONDUCTOR EQUIPMENT ──────────────────────────────────────
  {s:"Axcelis",           t:"TSMC",              type:"customer"},
  {s:"Axcelis",           t:"Samsung",           type:"customer"},
  {s:"Veeco",             t:"Wolfspeed",         type:"customer"},
  {s:"Veeco",             t:"TSMC",              type:"customer"},
  {s:"AdvancedEnergy",    t:"Lam_Research",      type:"supply"},
  {s:"AdvancedEnergy",    t:"Applied_Materials", type:"supply"},
  {s:"Azenta",            t:"TSMC",              type:"customer"},
  {s:"Azenta",            t:"Samsung",           type:"customer"},
  {s:"Ichor",             t:"Lam_Research",      type:"supply"},
  {s:"Ichor",             t:"Applied_Materials", type:"supply"},
  {s:"Ichor",             t:"Tokyo_Electron",    type:"supply"},
  {s:"OntoInnovation",    t:"TSMC",              type:"customer"},
  {s:"OntoInnovation",    t:"Samsung",           type:"customer"},
  {s:"FormFactor",        t:"TSMC",              type:"customer"},
  {s:"FormFactor",        t:"Micron",            type:"customer"},
  {s:"FormFactor",        t:"Intel",             type:"customer"},
  {s:"Teradyne",          t:"TSMC",              type:"customer"},
  {s:"Teradyne",          t:"Qualcomm",          type:"customer"},
  {s:"Teradyne",          t:"Samsung",           type:"customer"},
  {s:"Teradyne",          t:"Intel",             type:"customer"},
  {s:"Keysight",          t:"TSMC",              type:"customer"},
  {s:"Keysight",          t:"Qualcomm",          type:"customer"},
  {s:"ASML_EUV",          t:"TSMC",              type:"customer"},
  {s:"DuPont_Electronics",t:"TSMC",              type:"customer"},
  {s:"DuPont_Electronics",t:"ASML_EUV",          type:"partner"},
  {s:"CMC_Materials",     t:"TSMC",              type:"customer"},
  {s:"CMC_Materials",     t:"Samsung",           type:"customer"},
  {s:"CMC_Materials",     t:"Intel",             type:"customer"},
  {s:"Entegris",          t:"TSMC",              type:"customer"},
  {s:"Entegris",          t:"Samsung",           type:"customer"},
  {s:"Entegris",          t:"Intel",             type:"customer"},

  // ── NETWORKING ───────────────────────────────────────────────────
  {s:"Ciena",             t:"Corning",           type:"supply"},
  {s:"Ciena",             t:"AWS",               type:"cloud"},
  {s:"Calix",             t:"Corning",           type:"supply"},
  {s:"Calix_Net",         t:"Corning",           type:"supply"},
  {s:"ExtremeNetworks",   t:"Broadcom",          type:"supply"},
  {s:"ExtremeNetworks",   t:"Intel",             type:"supply"},
  {s:"NVidia_Networking", t:"TSMC",              type:"supply"},
  {s:"Arista",            t:"Broadcom",          type:"supply"},
  {s:"Arista",            t:"Intel",             type:"supply"},
  {s:"Nokia",             t:"Intel",             type:"supply"},
  {s:"Ericsson",          t:"Intel",             type:"supply"},
  {s:"MaxLinear",         t:"TSMC",              type:"supply"},
  {s:"MaxLinear_Optical", t:"TSMC",              type:"supply"},
  {s:"Silicom",           t:"Intel",             type:"supply"},

  // ── MEMORY ───────────────────────────────────────────────────────
  {s:"Kioxia",            t:"TSMC",              type:"partner"},
  {s:"Kioxia",            t:"Western_Digital",   type:"partner"},
  {s:"Western_Digital",   t:"Kioxia",            type:"partner"},
  {s:"Seagate",           t:"Western_Digital",   type:"partner"},
  {s:"SiliconMotion",     t:"SK_Hynix",          type:"customer"},
  {s:"SiliconMotion",     t:"Kioxia",            type:"customer"},

  // ── AI LABS / MODELS ─────────────────────────────────────────────
  {s:"Mistral",           t:"Azure",             type:"cloud"},
  {s:"Mistral",           t:"GCP",               type:"cloud"},
  {s:"Perplexity",        t:"AWS",               type:"cloud"},
  {s:"Perplexity",        t:"Azure",             type:"cloud"},
  {s:"CharacterAI",       t:"GCP",               type:"cloud"},
  {s:"CharacterAI",       t:"NVIDIA",            type:"supply"},
  {s:"DeepSeek",          t:"Huawei",            type:"supply"},
  {s:"DeepSeek",          t:"AlibabaCloud",      type:"cloud"},
  {s:"AlephAlpha",        t:"Azure",             type:"cloud"},
  {s:"AlephAlpha",        t:"NVIDIA",            type:"supply"},
  {s:"Cohere_NLP",        t:"AWS",               type:"cloud"},
  {s:"Cohere_NLP",        t:"GCP",               type:"cloud"},
  {s:"Cohere",            t:"AWS",               type:"cloud"},
  {s:"Cohere",            t:"GCP",               type:"cloud"},
  {s:"Groq_AI",           t:"Meta",              type:"customer"},
  {s:"StabilityAI",       t:"AWS",               type:"cloud"},
  {s:"StabilityAI",       t:"NVIDIA",            type:"supply"},
  {s:"Inflection",        t:"Azure",             type:"cloud"},
  {s:"Inflection",        t:"NVIDIA",            type:"supply"},
  {s:"Adept",             t:"GCP",               type:"cloud"},
  {s:"Adept",             t:"NVIDIA",            type:"supply"},
  {s:"AdeptAI",           t:"GCP",               type:"cloud"},
  {s:"Imbue",             t:"AWS",               type:"cloud"},
  {s:"01AI",              t:"AWS",               type:"cloud"},
  {s:"01AI",              t:"NVIDIA",            type:"supply"},
  {s:"Runway",            t:"AWS",               type:"cloud"},
  {s:"Runway",            t:"NVIDIA",            type:"supply"},
  {s:"Suno",              t:"AWS",               type:"cloud"},
  {s:"Cognition",         t:"Azure",             type:"cloud"},
  {s:"CognitionAI",       t:"Azure",             type:"cloud"},
  {s:"Glean",             t:"GCP",               type:"cloud"},
  {s:"Glean",             t:"AWS",               type:"cloud"},

  // ── CLOUD / SAAS ─────────────────────────────────────────────────
  {s:"Snowflake",         t:"AWS",               type:"cloud"},
  {s:"Snowflake",         t:"Azure",             type:"cloud"},
  {s:"Snowflake",         t:"GCP",               type:"cloud"},
  {s:"Databricks",        t:"AWS",               type:"cloud"},
  {s:"Databricks",        t:"Azure",             type:"cloud"},
  {s:"Databricks",        t:"GCP",               type:"cloud"},
  {s:"Confluent",         t:"AWS",               type:"cloud"},
  {s:"Confluent",         t:"Azure",             type:"cloud"},
  {s:"MongoDB",           t:"AWS",               type:"cloud"},
  {s:"MongoDB",           t:"Azure",             type:"cloud"},
  {s:"OracleCloud",       t:"NVIDIA",            type:"supply"},
  {s:"AlibabaCloud",      t:"Alibaba",           type:"owns"},
  {s:"AlibabaCloud",      t:"NVIDIA",            type:"supply"},
  {s:"Datadog",           t:"AWS",               type:"cloud"},
  {s:"Datadog",           t:"Azure",             type:"cloud"},
  {s:"Datadog",           t:"GCP",               type:"cloud"},
  {s:"Elastic",           t:"AWS",               type:"cloud"},
  {s:"Elastic",           t:"Azure",             type:"cloud"},
  {s:"C3AI",              t:"AWS",               type:"cloud"},
  {s:"C3AI",              t:"GCP",               type:"cloud"},
  {s:"C3ai",              t:"AWS",               type:"cloud"},
  {s:"HashiCorp",         t:"AWS",               type:"cloud"},
  {s:"HashiCorp",         t:"Azure",             type:"cloud"},
  {s:"LangChain",         t:"AWS",               type:"cloud"},
  {s:"LangChain",         t:"GCP",               type:"cloud"},
  {s:"Voiceflow",         t:"AWS",               type:"cloud"},
  {s:"NVIDIA_NIM",        t:"NVIDIA",            type:"owns"},

  // ── ROBOTICS ─────────────────────────────────────────────────────
  {s:"Figure",            t:"NVIDIA",            type:"supply"},
  {s:"Figure",            t:"OpenAI",            type:"partner"},
  {s:"PhysicalIntelligence",t:"NVIDIA",          type:"supply"},
  {s:"PhysicalIntelligence",t:"Google",          type:"partner"},
  {s:"Apptronik",         t:"NVIDIA",            type:"supply"},
  {s:"Apptronik",         t:"Google",            type:"partner"},
  {s:"Agility",           t:"NVIDIA",            type:"supply"},
  {s:"Agility",           t:"AWS",               type:"cloud"},
  {s:"Zebra_Technologies",t:"NVIDIA",            type:"supply"},
  {s:"Zebra_Technologies",t:"AWS",               type:"cloud"},

  // ── QUANTUM ──────────────────────────────────────────────────────
  {s:"IonQ",              t:"AWS",               type:"cloud"},
  {s:"IonQ",              t:"Azure",             type:"cloud"},
  {s:"IonQ",              t:"GCP",               type:"cloud"},
  {s:"PsiQuantum",        t:"TSMC",              type:"supply"},
  {s:"PsiQuantum",        t:"AWS",               type:"cloud"},
  {s:"Quantinuum",        t:"Azure",             type:"cloud"},
  {s:"Quantinuum",        t:"AWS",               type:"cloud"},
  {s:"QuEra",             t:"AWS",               type:"cloud"},
  {s:"Sycamore",          t:"GCP",               type:"cloud"},

  // ── FABLESS SEMI / ADDITIONAL ────────────────────────────────────
  {s:"MACOM",             t:"TSMC",              type:"supply"},
  {s:"Cirrus_Logic",      t:"Apple",             type:"customer"},
  {s:"Lattice_Semiconductor",t:"TSMC",           type:"supply"},
  {s:"LatticeSemi",       t:"TSMC",              type:"supply"},
  {s:"Wolfspeed",         t:"Infineon",          type:"supply"},
  {s:"Wolfspeed",         t:"Stellantis",        type:"customer"},
  {s:"Semtech",           t:"TSMC",              type:"supply"},
  {s:"Allegro",           t:"TSMC",              type:"supply"},
  {s:"MonolithicPower",   t:"TSMC",              type:"supply"},
  {s:"SiliconLabs",       t:"TSMC",              type:"supply"},
  {s:"PowerIntegrations", t:"TSMC",              type:"supply"},
  {s:"Diodes",            t:"TSMC",              type:"supply"},
  {s:"PixelWorks",        t:"TSMC",              type:"supply"},

  // ── FOUNDRIES / CONTRACT MFG ─────────────────────────────────────
  {s:"GlobalFoundries",   t:"Intel",             type:"customer"},
  {s:"GlobalFoundries",   t:"Qualcomm",          type:"customer"},
  {s:"GlobalFoundries",   t:"AMD",               type:"customer"},
  {s:"TowerSemiconductor",t:"Intel",             type:"partner"},
  {s:"TowerSemiconductor",t:"Qualcomm",          type:"customer"},
  {s:"PowerchipSemi",     t:"TSMC",              type:"partner"},
  {s:"ASEGroup",          t:"Apple",             type:"customer"},
  {s:"ASEGroup",          t:"Qualcomm",          type:"customer"},
  {s:"ASEGroup",          t:"AMD",               type:"customer"},

  // ── EMS / ODM ────────────────────────────────────────────────────
  {s:"SuperMicro",        t:"NVIDIA",            type:"partner"},
  {s:"SuperMicro",        t:"Intel",             type:"supply"},
  {s:"Celestica",         t:"Cisco",             type:"customer"},
  {s:"Celestica",         t:"Meta",              type:"customer"},
  {s:"Inspur",            t:"NVIDIA",            type:"supply"},
  {s:"Inspur",            t:"Intel",             type:"supply"},
  {s:"HPE_Cray",          t:"NVIDIA",            type:"supply"},
  {s:"HPE_Cray",          t:"AMD",               type:"supply"},
  {s:"CrayHPE",           t:"NVIDIA",            type:"supply"},
  {s:"CrayHPE",           t:"AMD",               type:"supply"},

  // ── FINTECH / DATA ───────────────────────────────────────────────
  {s:"VirtuFinancial",    t:"NASDAQ",            type:"partner"},
  {s:"VirtuFinancial",    t:"CBOE",              type:"partner"},
  {s:"FactSet",           t:"AWS",               type:"cloud"},
  {s:"Morningstar",       t:"AWS",               type:"cloud"},
  {s:"AlphaSenseFin",     t:"AWS",               type:"cloud"},
  {s:"Kensho",            t:"AWS",               type:"cloud"},
  {s:"Addepar",           t:"AWS",               type:"cloud"},
  {s:"Kavout",            t:"AWS",               type:"cloud"},

  // ── INDUSTRIAL / IOT ─────────────────────────────────────────────
  {s:"Samsara",           t:"AWS",               type:"cloud"},
  {s:"Samsara",           t:"NVIDIA",            type:"supply"},
  {s:"Veeva",             t:"Salesforce",        type:"partner"},
  {s:"Veeva",             t:"AWS",               type:"cloud"},
  {s:"Danaher",           t:"TSMC",              type:"customer"},
  {s:"Rockwell_Automation",t:"Intel",            type:"supply"},
  {s:"Rockwell_Automation",t:"NVIDIA",           type:"supply"},
  {s:"Cognex",            t:"NVIDIA",            type:"supply"},
  {s:"Cognex",            t:"Intel",             type:"supply"},
  {s:"Trimble_Inc",       t:"AWS",               type:"cloud"},
  {s:"AnsysEDA",          t:"AWS",               type:"cloud"},
  {s:"Ansys",             t:"AWS",               type:"cloud"},
  {s:"Siemens_EDA",       t:"Intel",             type:"customer"},
  {s:"WiTricity",         t:"TSMC",              type:"supply"},

  // ── EDA ──────────────────────────────────────────────────────────
  {s:"IntelLoihi",        t:"Intel",             type:"owns"},
  {s:"Intel_Loihi",       t:"Intel",             type:"owns"},
  {s:"SpiNNcloud",        t:"TSMC",              type:"supply"},

  // ── CRITICAL MATERIALS ───────────────────────────────────────────
  {s:"MP_Materials",      t:"TSMC",              type:"customer"},
  {s:"Lynas",             t:"TSMC",              type:"customer"},
  {s:"Albemarle",         t:"TSMC",              type:"customer"},
  {s:"Livent",            t:"TSMC",              type:"customer"},
  {s:"EnergyFuels",       t:"TSMC",              type:"customer"},
  {s:"ArcadiumLithium",   t:"TSMC",              type:"customer"},
  {s:"SigmaLithium",      t:"TSMC",              type:"customer"},
  {s:"NioCorp",           t:"Intel",             type:"customer"},

  // ── CYBER / SECURITY ─────────────────────────────────────────────
  {s:"Imperva",           t:"AWS",               type:"cloud"},
  {s:"Imperva",           t:"Azure",             type:"cloud"},
  {s:"GenDigital",        t:"AWS",               type:"cloud"},
  {s:"Verint",            t:"AWS",               type:"cloud"},

  // ── NEW NODES LINKS ───────────────────────────────────────────────
  {s:"STMicro",           t:"TSMC",              type:"supply"},
  {s:"STMicro",           t:"Infineon",          type:"partner"},
  {s:"STMicroelectronics",t:"TSMC",              type:"supply"},
  {s:"Cepton",            t:"NVIDIA",            type:"supply"},
  {s:"Butterfly",         t:"TSMC",              type:"supply"},
  {s:"Butterfly",         t:"AWS",               type:"cloud"},
  {s:"Insilico",          t:"NVIDIA",            type:"supply"},
  {s:"Insilico",          t:"AWS",               type:"cloud"},
  {s:"PathAI",            t:"NVIDIA",            type:"supply"},
  {s:"PathAI",            t:"AWS",               type:"cloud"},
  {s:"Tempus",            t:"NVIDIA",            type:"supply"},
  {s:"Tempus",            t:"GCP",               type:"cloud"},
  {s:"Viavi",             t:"Corning",           type:"supply"},
  {s:"Lightelligence",    t:"TSMC",              type:"supply"},
  {s:"AmpereComputing",   t:"TSMC",              type:"supply"},
  {s:"AmpereComputing",   t:"OracleCloud",       type:"cloud"},
  {s:"Mythic",            t:"TSMC",              type:"supply"},
  {s:"Esperanto",         t:"TSMC",              type:"supply"},
  {s:"GreenWaves",        t:"TSMC",              type:"supply"},
  {s:"EdgeImpulse",       t:"AWS",               type:"cloud"},
  {s:"EdgeImpulse",       t:"Azure",             type:"cloud"},
  {s:"Edgio",             t:"Intel",             type:"supply"},
  {s:"QTS",               t:"Equinix",           type:"partner"},
  {s:"DataBank",          t:"Equinix",           type:"partner"},
  {s:"Switch",            t:"Schneider",         type:"supply"},
  {s:"First_Solar",       t:"AWS",               type:"cloud"},
  {s:"SMA_Solar",         t:"First_Solar",       type:"partner"},
  {s:"Kratos_Defense",    t:"SpaceX",            type:"supply"},
  {s:"Kratos_Defense",    t:"NVIDIA",            type:"supply"},
  {s:"MaxLinear",         t:"TSMC",              type:"supply"},
  {s:"MaxLinear",         t:"AWS",               type:"cloud"},
  {s:"SiTime",            t:"TSMC",              type:"supply"},
  {s:"Globalstar",        t:"SpaceX",            type:"supply"},
  {s:"Globalstar",        t:"AWS_Ground",        type:"partner"},
  {s:"BlackSky",          t:"SpaceX",            type:"supply"},
  {s:"BlackSky",          t:"AWS",               type:"cloud"},
  {s:"Hexcel",            t:"Boeing",            type:"customer"},
  {s:"Hexcel",            t:"Airbus",            type:"customer"},
  {s:"TorayIndustries",   t:"Boeing",            type:"customer"},
  {s:"TorayIndustries",   t:"Hexcel",            type:"partner"},
  {s:"AlleghenyTech",     t:"Boeing",            type:"customer"},
  {s:"CarpenterTech",     t:"Boeing",            type:"customer"},
  {s:"CarpenterTech",     t:"GE_Aerospace",      type:"customer"},
  {s:"ParkerHannifin",    t:"Boeing",            type:"supply"},
  {s:"ParkerHannifin",    t:"Airbus",            type:"supply"},
  {s:"Moog",              t:"Boeing",            type:"supply"},
  {s:"Moog",              t:"Northrop",          type:"supply"},
  {s:"AWS_Ground",        t:"AWS",               type:"owns"},
  {s:"AWS_Ground",        t:"SpaceX",            type:"customer"},

];
