// nodes/nodes_expand3.js — Khipu Finance · Extended Node Universe Part 3
// 62 verified-unique nodes — completing the 450-node supply chain map
// All IDs verified non-duplicate with nodes_expand, nodes_expand2, nodes_spacex, inline NODES

var NODES_EXPAND3 = [

  // ── Power Semiconductors (5G RF / GaN / SiC) ────────────────────────────
  {"id":"Qorvo","label":"Qorvo","ticker":"QRVO · Nasdaq","cat":"power",
   "role":"Módulos de RF front-end para smartphones 5G, IoT, defensa y conectividad infraestructura.",
   "supplies":"BAW/SAW filters, PA modules para iPhone/Android 5G; GaN para defensa; WiFi 7 modules.",
   "moat":"Diseño propietario BAW + GaN RFIC; fabs propias en Oregon y NC; único proveedor multi-band 5G.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟡 +12% e. 2026; 5G premium smartphone","margin":0.18,"mkt":"QRVO"},
  {"id":"Skyworks","label":"Skyworks Solutions","ticker":"SWKS · Nasdaq","cat":"power",
   "role":"Soluciones de semiconductores analógicos de alta eficiencia para conectividad móvil y IoT.",
   "supplies":"Sky5 unified RF modules para Apple/Samsung 5G; SkyOne para IoT; amplificadores industriales.",
   "moat":"Relación exclusiva Apple de ~40% revenue; liderazgo en eficiencia energética RF.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟡 +10% e. 2026; content gain en iPhone 17","margin":0.23,"mkt":"SWKS"},
  {"id":"Rohm","label":"Rohm Semiconductor","ticker":"6963 · TSE","cat":"power",
   "role":"Fabricante japonés de SiC de potencia para VE e industriales; segundo mayor del mundo.",
   "supplies":"SiC MOSFETs y módulos para inversores Toyota/Honda; ICs analógicos de gestión de energía.",
   "moat":"Integración vertical total SiC; JV con STMicro para capacidad compartida.",
   "loc":"Japón","country":"Japon","growth":"🟢 +28% e. 2026; SiC automotive","margin":0.13,"mkt":"6963.T"},
  {"id":"Navitas","label":"Navitas Semiconductor","ticker":"NVTS · Nasdaq","cat":"power",
   "role":"Chips GaN de alta velocidad para cargadores de alta eficiencia (USB-C, EV on-board).",
   "supplies":"GaNFast ICs para cargadores rápidos 65W-3kW; GeneSiC SiC MOSFETs para solar e industrial.",
   "moat":"Propietario de GaNFast process (GaN+Logic monolítico); 80%+ del mercado GaN en consumer charging.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +35% e. 2026; USB-C GaN charging + EV","margin":0.08,"mkt":"NVTS"},
  {"id":"Monolithic_Power","label":"Monolithic Power Systems","ticker":"MPWR · Nasdaq","cat":"power",
   "role":"ICs de gestión de energía de alta integración para AI servers, portátiles y automoción.",
   "supplies":"DC-DC converters para NVIDIA GPU servers; MOSFETs para AI datacenter power delivery.",
   "moat":"Diseño propietario BCD: menor tamaño/calor; diseñado-in en NVIDIA H100 power delivery.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +40% e. 2026; AI server power delivery","margin":0.55,"mkt":"MPWR"},
  {"id":"Allegro_Micro","label":"Allegro MicroSystems","ticker":"ALGM · Nasdaq","cat":"power",
   "role":"Sensores magnéticos y drivers de motores para automóviles eléctricos y robótica.",
   "supplies":"Current sensors para BMS de baterías EV; driver ICs para motores BLDC; ADAS hall sensors.",
   "moat":"Liderazgo en sensores de corriente para tracción EV; >50% cuota global en hall-effect.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +25% e. 2026; xEV sensor content up","margin":0.22,"mkt":"ALGM"},

  // ── Advanced Packaging / Substrates ─────────────────────────────────────
  {"id":"Shinko_Electric","label":"Shinko Electric Industries","ticker":"6967 · TSE","cat":"substrates",
   "role":"Tercer productor de sustratos IC; adquirida por JX Holdings; foco en flip-chip y BGA.",
   "supplies":"Sustratos FC-CSP, BGA para telecom, automotriz, consumer; FC-BGA packaging.",
   "moat":"Cuarto del oligopolio ABF; partnership con Fujitsu para sustratos de nueva generación.",
   "loc":"Japón","country":"Japon","growth":"🟢 +20% e. 2026; IC substrate demand","margin":0.14,"mkt":"6967.T"},

  // ── Thermal Management ────────────────────────────────────────────────────
  {"id":"Modine","label":"Modine Manufacturing","ticker":"MOD · NYSE","cat":"servers",
   "role":"Soluciones térmicas de alta potencia para centros de datos, VE y sistemas industriales.",
   "supplies":"Chillers, evaporadores, heat exchangers para AI GPU cooling; Climate Control para VE.",
   "moat":"Especialización en thermal management para cargas densas (>100kW/rack); design wins con hyperscalers.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +40% e. 2026; data center thermal solutions","margin":0.09,"mkt":"MOD"},

  // ── Robotics Industrial ──────────────────────────────────────────────────
  {"id":"Fanuc","label":"Fanuc","ticker":"6954 · TSE","cat":"robotics_physical",
   "role":"Líder mundial en CNC y robots industriales; equipos para fabs de chips y manufactura.",
   "supplies":"Robots FANUC para soldadura y ensamblaje en fabs TSMC/Samsung; CNCs para Foxconn.",
   "moat":"70%+ del mercado CNC global; software propietario con 35+ años de datos de uso.",
   "loc":"Japón","country":"Japon","growth":"🔵 +12% e. 2026; factory automation","margin":0.22,"mkt":"6954.T"},
  {"id":"Yaskawa","label":"Yaskawa Electric","ticker":"6506 · TSE","cat":"robotics_physical",
   "role":"Robots industriales MOTOMAN y variadores Sigma para manufactura de semiconductores.",
   "supplies":"Robots de alta velocidad para manejo de obleas; inverters para equipos litografía.",
   "moat":"Liderazgo en servomotores industriales de ultra-precisión; instalados en TSMC y Samsung.",
   "loc":"Japón","country":"Japon","growth":"🟢 +18% e. 2026; semiconductor automation","margin":0.11,"mkt":"6506.T"},
  {"id":"ABB_Robotics","label":"ABB Robotics","ticker":"ABBN · SIX","cat":"robotics_physical",
   "role":"División de robots industriales y automación de ABB; líder en colaborativos (YuMi).",
   "supplies":"Robots IRB para electrónica; YuMi cobots para ensamblaje; software RobotStudio.",
   "moat":"Portfolio completo industrial + cobots; integración con PLCs ABB en plantas existentes.",
   "loc":"Europa","country":"Europa","growth":"🟢 +15% e. 2026; EV + semiconductor automation","margin":0.13,"mkt":"ABBN.SW"},

  // ── Earth Observation ────────────────────────────────────────────────────
  {"id":"Spire_Global","label":"Spire Global","ticker":"SPIR · NYSE","cat":"earth_obs",
   "role":"Satélites nanosatélites para datos meteorológicos, marítimos y aviación en tiempo real.",
   "supplies":"NOAA data contracts; AIS tracking de barcos; RO para meteorología.",
   "moat":"Mayor flota de nanosatélites para datos atmosféricos (>100); único proveedor NOAA de RO data.",
   "loc":"EE.UU.","country":"EEUU","growth":"🔵 Gov contracts growing; weather data","margin":-0.2,"mkt":"SPIR"},
  {"id":"Maxar","label":"Maxar Technologies","ticker":"No cotiza · privado","cat":"earth_obs",
   "role":"Proveedor de imágenes de satélite de alta resolución para NGA, CIA y clientes comerciales.",
   "supplies":"WorldView-3/4 imágenes <30cm resolución; GeoEye para inteligencia geoespacial DoD.",
   "moat":"Contrato NextView exclusivo con NGA ($300M+/año); el satélite comercial de mayor resolución.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 Adquirido Advent/KKR; DoD anchor","margin":null,"preipo":true,"mkt":""},

  // ── Defense Drones / eVTOL ────────────────────────────────────────────────
  {"id":"Kratos","label":"Kratos Defense & Security","ticker":"KTOS · Nasdaq","cat":"ai_defense",
   "role":"Drones de jet de alta velocidad (XQ-58 Valkyrie), blancos aéreos y satélites militares.",
   "supplies":"Valkyrie drone de bajo costo para USAF; HIVE targets para entrenamiento; satcom terrena.",
   "moat":"Única empresa con drone de combate jet a <$3M (10x más barato que caza pilotado).",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +30% e. 2026; drone warfare expansion","margin":0.07,"mkt":"KTOS"},
  {"id":"AeroVironment","label":"AeroVironment","ticker":"AVAV · Nasdaq","cat":"ai_defense",
   "role":"Drones tácticos y loitering munition (Switchblade) para ejércitos NATO y ucranianos.",
   "supplies":"Switchblade 300/600 (munición kamikaze); Puma AE para reconocimiento; JUMP 20 VTOL.",
   "moat":"Principal proveedor de Switchblade a Ucrania; contratos exclusivos US Army de 10 años.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +45% e. 2026; global drone demand","margin":0.12,"mkt":"AVAV"},
  {"id":"Joby_Aviation","label":"Joby Aviation","ticker":"JOBY · NYSE","cat":"ai_auto",
   "role":"eVTOL (taxi aéreo eléctrico) de 5 asientos; tipo: lift-and-cruise de 150 mph.",
   "supplies":"Aeronave S4 para servicio de air taxi; acuerdo Toyota + Delta Air Lines.",
   "moat":"Primer eVTOL con FAA type certificate en proceso; inversión Toyota + USAF.",
   "loc":"EE.UU.","country":"EEUU","growth":"🔵 Certificación FAA 2025-2026; comercial 2026","preipo":false,"mkt":"JOBY"},
  {"id":"Wayve","label":"Wayve","ticker":"No cotiza","cat":"ai_auto",
   "role":"Software de conducción autónoma fundacional (Embodied AI) para OEMs europeos.",
   "supplies":"PRISM foundation model para autonomía de vehículos; Wayve OS para OEM integration.",
   "moat":"Único enfoque embodied AI puro para coches; Microsoft + SoftBank $1.05B investment 2024.",
   "loc":"Europa","country":"Europa","growth":"🟢 $1.05B raised 2024; Aspen & LEVC partnerships","margin":null,"preipo":true,"mkt":""},

  // ── Quantum Infrastructure ───────────────────────────────────────────────
  {"id":"Oxford_Instruments","label":"Oxford Instruments","ticker":"OXIG · LSE","cat":"quantum_infra",
   "role":"Instrumentación científica criogénica, plasma y microscopia para cuántica y semiconductores.",
   "supplies":"NanoScience dilution fridges; Plasma Technology para etching cuántico; microscopia SQUID.",
   "moat":"140+ años: estándares en instrumentación científica; única empresa con full-stack cuántico criogénico.",
   "loc":"Europa","country":"Europa","growth":"🟢 +18% e. 2026; quantum + advanced semi","margin":0.21,"mkt":"OXIG.L"},

  // ── Rare Earth / Critical Materials ─────────────────────────────────────
  {"id":"Energy_Fuels","label":"Energy Fuels Inc","ticker":"UUUU · NYSE","cat":"rare_earth",
   "role":"Productor de uranio y tierras raras en EE.UU.; único procesador integrado REE en Norteamérica.",
   "supplies":"Uranium para reactores nucleares; NdPr y REE de mineral de monazita; vanadio.",
   "moat":"Única instalación de procesamiento de tierras raras en EE.UU. (White Mesa Mill).",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +35% e. 2026; REE + uranium renaissance","margin":0.18,"mkt":"UUUU"},

  // ── Battery Materials ────────────────────────────────────────────────────
  {"id":"Umicore","label":"Umicore","ticker":"UMI · Euronext","cat":"battery_mat",
   "role":"Mayor productor de cátodos para baterías VE (NMC) y reciclaje de metales de batería.",
   "supplies":"Cátodos NMC 622/811 para Samsung SDI, Panasonic; reciclaje de cobalto y litio de baterías.",
   "moat":"Líder en reciclaje de baterías en circuito cerrado; patentes de cátodo de alta densidad energética.",
   "loc":"Europa","country":"Europa","growth":"🟡 +15% e. 2026; EV battery cathode","margin":0.10,"mkt":"UMI.BR"},

  // ── Memory Expansion ────────────────────────────────────────────────────
  {"id":"Nanya","label":"Nanya Technology","ticker":"2303 · TWSE","cat":"memory",
   "role":"Tercer fabricante de DRAM del mundo; produce DDR4/DDR5 para PC y servidores.",
   "supplies":"DDR4/DDR5 para PC/laptop OEMs; módulos LPDDR para automoción.",
   "moat":"Tecnología DRAM de 1a/1b nm en desarrollo; ubicación Taiwán con acceso a TSMC.",
   "loc":"Taiwán","country":"Taiwan","growth":"🔵 +18% e. 2026; DRAM recovery","margin":0.08,"mkt":"2303.TW"},
  {"id":"Winbond","label":"Winbond Electronics","ticker":"2344 · TWSE","cat":"memory",
   "role":"NOR Flash y DRAM para IoT, automoción y electrónica de consumo; nicho NOR.",
   "supplies":"Serial NOR Flash para BIOS chips, routers, IoT; LPSRAM para automoción.",
   "moat":"Dominante en NOR Flash automotriz y BIOS chip (>40% cuota).",
   "loc":"Taiwán","country":"Taiwan","growth":"🟡 +15% e. 2026; auto NOR demand","margin":0.12,"mkt":"2344.TW"},

  // ── EDA / Design Tools ──────────────────────────────────────────────────
  {"id":"Altium","label":"Altium","ticker":"No cotiza · Renesas","cat":"eda",
   "role":"Software de diseño PCB Altium Designer; la herramienta más usada en PCB profesional.",
   "supplies":"Altium Designer (EDA PCB), Altium 365 (cloud collaboration), NEXUS (enterprise).",
   "moat":"Estándar de facto en PCB design para ingenieros hardware: 30K+ empresas.",
   "loc":"Australia","country":"Australia","growth":"🟢 Adquirida por Renesas $5.9B 2024","margin":null,"mkt":""},
  {"id":"Photronics","label":"Photronics","ticker":"PLAB · Nasdaq","cat":"eda",
   "role":"Fabricante de fotomáscaras (photomasks) para litografía semiconductor avanzada.",
   "supplies":"Fotomáscaras para 7nm/5nm/3nm a TSMC, Samsung, GlobalFoundries; flat panel display masks.",
   "moat":"Oligopolio con Toppan: mercado de ~$4B, solo 4 jugadores globales; barreras de capital enormes.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +20% e. 2026; advanced node mask demand","margin":0.26,"mkt":"PLAB"},

  // ── Cybersecurity Semiconductors ─────────────────────────────────────────
  {"id":"Lattice","label":"Lattice Semiconductor","ticker":"LSCC · Nasdaq","cat":"fabless",
   "role":"FPGAs de baja potencia y chips de seguridad de plataforma (raíz de confianza hardware).",
   "supplies":"MachXO3D para raíz de confianza en servidores (Dell, HPE); Nexus FPGAs para 5G.",
   "moat":"Líder de mercado en FPGAs pequeños de bajo consumo; único en integrar raíz de confianza en FPGA.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +20% e. 2026; platform security mandate","margin":0.52,"mkt":"LSCC"},
  {"id":"Rambus","label":"Rambus","ticker":"RMBS · Nasdaq","cat":"fabless",
   "role":"IP de interfaces de memoria (HBM, DDR5, PCIe) y chips de seguridad criptográfica.",
   "supplies":"PHY IP para HBM3/DDR5; CryptoManager HSM IP para automotriz e IoT; SerDes 112G.",
   "moat":"Patentes fundamentales de bus de memoria; cada HBM chip usa su IP; crecimiento en crypto IP.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +25% e. 2026; HBM + security IP boom","margin":0.45,"mkt":"RMBS"},
  {"id":"Achronix","label":"Achronix Semiconductor","ticker":"No cotiza","cat":"fabless",
   "role":"FPGAs de alta velocidad y ACE (FPGA-to-ASIC conversion) para datacenter y 5G.",
   "supplies":"Speedster7t FPGAs (2nm Samsung GAA); speedcore eFPGA IP para ASIC embedding.",
   "moat":"Primer FPGA de alta densidad en 2nm; único vendor de eFPGA para SoC custom integration.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 $155M raised; hyperscaler FPGA wins","margin":null,"preipo":true,"mkt":""},

  // ── Connectivity / IP / Core Semiconductors ───────────────────────────
  {"id":"NXP","label":"NXP Semiconductors","ticker":"NXPI · Nasdaq","cat":"fabless",
   "role":"Líder en semiconductores automotrices, seguridad NFC y microcontroladores de procesamiento.",
   "supplies":"S32 SoC para ADAS y cockpit EV; i.MX para IoT; NFC para pagos (Apple Pay, Google Pay).",
   "moat":"Cuota ~30% en semiconductores automotrices; NFC en 2B+ dispositivos (payments estándar).",
   "loc":"Europa","country":"Europa","growth":"🟢 +18% e. 2026; ADAS + EV content","margin":0.22,"mkt":"NXPI"},
  {"id":"Renesas","label":"Renesas Electronics","ticker":"6723 · TSE","cat":"fabless",
   "role":"Tercer mayor proveedor de semiconductores automotrices; MCU/MPU para sistemas críticos.",
   "supplies":"RH850 MCU para ADAS, powertrain EV; R-Car SoC para IVI; Arm Cortex-based MCUs.",
   "moat":"Cuota #1 en MCU automotriz (28% global); adquirió Dialog, Intersil, Altium para diversificación.",
   "loc":"Japón","country":"Japon","growth":"🟢 +15% e. 2026; EV content per car growing","margin":0.26,"mkt":"6723.T"},
  {"id":"Arm_Holdings","label":"Arm Holdings","ticker":"ARM · Nasdaq","cat":"fabless",
   "role":"Arquitectura de procesadores RISC usada en el 99% de smartphones y creciente en servidores.",
   "supplies":"IP Cortex-A, Cortex-M, Neoverse cores; Mali GPU IP; Total Compute para AI; Armv9.",
   "moat":"Imposible competir: >250B chips con licencia ARM; red de 300+ socios; Armv9 + royalties crecientes.",
   "loc":"Europa","country":"Europa","growth":"🟢 +25% e. 2026; AI accelerator + cloud Neoverse","margin":0.55,"mkt":"ARM"},
  {"id":"Microchip_Tech","label":"Microchip Technology","ticker":"MCHP · Nasdaq","cat":"fabless",
   "role":"Líder global en microcontroladores PIC/dsPIC y AVR; memoria Flash propietaria.",
   "supplies":"PIC/AVR MCUs para automotive, IoT, industrial; FPGAs PolarFire para seguridad; Wi-Fi ICs.",
   "moat":"La mayor base instalada de MCUs del mundo (>200K diseños activos); migración a 32-bit.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟡 +12% e. 2026; industrial recovery + auto","margin":0.40,"mkt":"MCHP"},
  {"id":"CEVA","label":"CEVA Inc","ticker":"CEVA · Nasdaq","cat":"fabless",
   "role":"IP de procesadores de señal digital para wireless 5G/6G, AI edge y capacidades de sensores.",
   "supplies":"CEVA-X DSP para 5G modem; CEVA-NeuPro AI NPU IP; SensPro sensor fusion; Bluetooth SIP.",
   "moat":"IP wireless DSP en 8B+ dispositivos; único que cubre 5G+AI+BT+WiFi en un IP portfolio.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +22% e. 2026; 5G + AI IoT design wins","margin":0.45,"mkt":"CEVA"},

  // ── Optical Networking ────────────────────────────────────────────────────
  {"id":"InfiniteraNet","label":"Infinera","ticker":"INFN · Nasdaq","cat":"photonics_si",
   "role":"Transponders ópticos con PICs (Photonic Integrated Circuits) para redes troncales.",
   "supplies":"GX Series transponders; Cloud Xpress para interconnect; ICE6 modem para 800G.",
   "moat":"Único proveedor de PICs InP propias (vertical integrado): 800G ICE6 en producción masiva.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +18% e. 2026; AI traffic backbone boom","margin":0.06,"mkt":"INFN"},

  // ── AI Software Platform ─────────────────────────────────────────────────
  {"id":"Scale_AI","label":"Scale AI","ticker":"No cotiza","cat":"aisoft",
   "role":"Plataforma de datos para IA: etiquetado, evaluación y RLHF de modelos de lenguaje.",
   "supplies":"Data labeling para OpenAI, Anthropic, Meta; Spellbook para fine-tuning; SEAL benchmarks.",
   "moat":"Mayor plataforma de data labeling y evaluación de modelos IA; contratos DoD clasificados.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 Valoración $14B; DoD + frontier lab contracts","margin":null,"preipo":true,"mkt":""},
  {"id":"HuggingFace","label":"Hugging Face","ticker":"No cotiza","cat":"aisoft",
   "role":"Plataforma open-source para IA: mayor repositorio de modelos y datasets del mundo.",
   "supplies":"Model Hub (400K+ modelos), Datasets (100K+), Spaces (ML apps); Inference API.",
   "moat":"GitHub para IA: red de 1M+ usuarios; estándar para compartir modelos; 100M+ descargas Transformers.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 Valoración $4.5B; Enterprise tier acelerando","margin":null,"preipo":true,"mkt":""},
  {"id":"Cohere_AI","label":"Cohere","ticker":"No cotiza","cat":"ailab",
   "role":"LLMs enterprise-grade para búsqueda semántica, clasificación y chat corporativo.",
   "supplies":"Command R+ LLM, Embed v3, Rerank; Cohere Platform para RAG y agentes enterprise.",
   "moat":"Especialización B2B enterprise (no consumer): contratos Oracle, Salesforce, McKinsey.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 Valoración $5B; Oracle + Salesforce partnership","margin":null,"preipo":true,"mkt":""},

  // ── Specialty Foundries ───────────────────────────────────────────────────
  {"id":"TowerSemi","label":"Tower Semiconductor","ticker":"TSEM · Nasdaq","cat":"foundry",
   "role":"Foundry especializada en analógico, RF y MEMS para aplicaciones de alta mixta señal.",
   "supplies":"RF SOI para Qorvo/Skyworks; CMOS image sensors para Sony; SiGe para 5G; analog PMIC.",
   "moat":"Tecnología RF-SOI única para 5G front-end; capacidades que TSMC/Samsung no replican.",
   "loc":"Israel","country":"Israel","growth":"🟢 +20% e. 2026; RF+MEMS+imager demand","margin":0.12,"mkt":"TSEM"},
  {"id":"X_Fab","label":"X-FAB Silicon Foundries","ticker":"XFAB · Euronext","cat":"foundry",
   "role":"Foundry europea de analógico/mixta señal para automotriz, médico e industrial.",
   "supplies":"SiC process (X-SiC) para power; MEMS para sensores automotrices; BiCMOS para RF.",
   "moat":"Certificaciones ISO/TS automotriz en 8 fabs globales; único analógico puro en Europa.",
   "loc":"Europa","country":"Europa","growth":"🟢 +18% e. 2026; automotive + medical mixed-signal","margin":0.09,"mkt":"XFAB.PA"},
  {"id":"Quanta_Computer","label":"Quanta Computer","ticker":"2382 · TWSE","cat":"servers",
   "role":"Mayor ODM de servidores del mundo; fabrica servidores para AWS, Google, Meta, Microsoft.",
   "supplies":"Rack servers, AI accelerator boxes (DGX-like) para hyperscalers; laptop ODM para HP/Dell.",
   "moat":"Relaciones ODM con todos los hyperscalers; economías de escala únicas en AI server assembly.",
   "loc":"Taiwán","country":"Taiwan","growth":"🟢 +35% e. 2026; AI server assembly boom","margin":0.06,"mkt":"2382.TW"},
  {"id":"Wistron","label":"Wistron Corporation","ticker":"3231 · TWSE","cat":"servers",
   "role":"ODM de servidores y PCs; segundo mayor ODM de notebooks mundial.",
   "supplies":"AI servers para Google y Amazon; notebook ODM para Acer, Lenovo, Dell; iPhone assembly.",
   "moat":"Capacidad de assembly diversificada Taiwan+India+México; major Apple assembler.",
   "loc":"Taiwán","country":"Taiwan","growth":"🔵 +15% e. 2026; AI server + India expansion","margin":0.03,"mkt":"3231.TW"},
  {"id":"Pegatron","label":"Pegatron Corporation","ticker":"4938 · TWSE","cat":"servers",
   "role":"Segundo mayor ensamblador de Apple iPhone y ODM de electrónica de consumo.",
   "supplies":"iPhone assembly (30%+ de iPhones); MacBook assembly; AI server assembly para new contracts.",
   "moat":"Relación exclusiva Apple como segundo ensamblador; capacidad india (Chennai) creciente.",
   "loc":"Taiwán","country":"Taiwan","growth":"🔵 +10% e. 2026; Apple diversification + India","margin":0.02,"mkt":"4938.TW"},

  // ── Display & Sensor Chips ────────────────────────────────────────────────
  {"id":"Indie_Semi","label":"indie Semiconductor","ticker":"INDI · Nasdaq","cat":"fabless",
   "role":"Chips automotrices de nueva generación: ADAS, infotainment, electrificación y conectividad.",
   "supplies":"Surya ADAS SoC, Palantir radar processor; Ultra Ethernet para automotive networking.",
   "moat":"Fundado ex-Maxim/Marvell/Qualcomm; único que integra ADAS+connectivity+power en un SoC.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +35% e. 2026; auto semiconductor content boom","margin":0.15,"mkt":"INDI"},
  {"id":"Sensata","label":"Sensata Technologies","ticker":"ST · NYSE","cat":"fabless",
   "role":"Sensores y controles de misión crítica para automóviles eléctricos e industriales.",
   "supplies":"Current sensors para BMS; pressure sensors para baterías EV; TPMS para vehículos.",
   "moat":"Instalado en >300M vehículos; aumento de contenido por coche EV de 3x vs. ICE.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +20% e. 2026; EV sensor content growth","margin":0.21,"mkt":"ST"},
  {"id":"Himax_Tech","label":"Himax Technologies","ticker":"HIMX · Nasdaq","cat":"fabless",
   "role":"Drivers de display (DDIC) para AR/VR, smartphones y chips de visión para ADAS.",
   "supplies":"Display drivers para Apple Watch, Meta Quest; WiseEye AI MCU para always-on vision.",
   "moat":"Líder en DDIC para AR/VR (LCoS para HoloLens, Magic Leap); WiseEye único en ultra-low-power AI.",
   "loc":"Taiwán","country":"Taiwan","growth":"🟢 +20% e. 2026; AR/VR + AI vision IoT","margin":0.12,"mkt":"HIMX"},

  // ── Test & Measurement / Equipment ──────────────────────────────────────
  {"id":"Onto_Innovation","label":"Onto Innovation","ticker":"ONTO · NYSE","cat":"equip",
   "role":"Sistemas de metrología e inspección de obleas para nodos avanzados y packaging 3D.",
   "supplies":"Atlas (CD-SEM, overlay) para litografía avanzada; Dragonfly (optical inspection) para packaging.",
   "moat":"Cuota creciente en metrology para 3D IC packaging (HBM, CoWoS); único en full-stack overlay.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +28% e. 2026; advanced packaging boom","margin":0.22,"mkt":"ONTO"},
  {"id":"Ultra_Clean","label":"Ultra Clean Holdings","ticker":"UCTT · Nasdaq","cat":"equip",
   "role":"Fabricante de subsistemas de gas y módulos para equipos de fab de semiconductores.",
   "supplies":"Gas panels y chemical delivery systems para AMAT, Lam, TEL; weld assemblies para ASML.",
   "moat":"Proveedor sole-source en muchos módulos de gas; co-diseño con Lam/AMAT en nuevas generaciones.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +22% e. 2026; WFE spending surge","margin":0.09,"mkt":"UCTT"},
  {"id":"Cohu","label":"Cohu","ticker":"COHU · Nasdaq","cat":"equip",
   "role":"Equipos de test y manejo de chips (handlers) para semiconductor testing posterior a fab.",
   "supplies":"KRYOS handler para SiC, RF, automotive chips; Neon inspection; Delta Design thermal control.",
   "moat":"Liderazgo en testing de SiC para EV (único handler a 200°C+); automotive test dominance.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +25% e. 2026; SiC EV + automotive test","margin":0.12,"mkt":"COHU"},
  {"id":"Aehr_Test","label":"Aehr Test Systems","ticker":"AEHR · Nasdaq","cat":"equip",
   "role":"Sistemas de burn-in a nivel de oblea (FOX-P) para SiC y chips de alta fiabilidad.",
   "supplies":"FOX-XP wafer-level burn-in para SiC MOSFET (Wolfspeed, onsemi); reliability testing.",
   "moat":"Único proveedor de burn-in a nivel de oblea para SiC; mandatado por Toyota/Tesla para SiC EV.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +50% e. 2026; SiC EV qualification mandate","margin":0.24,"mkt":"AEHR"},

  // ── Semiconductor Equipment (Wet Processing) ─────────────────────────────
  {"id":"ACM_Research","label":"ACM Research","ticker":"ACMR · Nasdaq","cat":"equip",
   "role":"Equipos de limpieza de obleas por ultrasonidos y electrodeposición para chips avanzados.",
   "supplies":"SAPS/Tebo cleaning para nodos <3nm en CXMT y SMIC; ECP cobre para interconexiones.",
   "moat":"Única alternativa no-occidental en wet cleaning; design wins en China fabs (CXMT, CXMT2).",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +35% e. 2026; China domestic fab equipment","margin":0.26,"mkt":"ACMR"},

  // ── India Semiconductor ───────────────────────────────────────────────────
  {"id":"TataSemiconductor","label":"Tata Electronics Semi","ticker":"No cotiza","cat":"foundry",
   "role":"Primera fab de semiconductores de India: $11B plant en Gujarat con PSMC de Taiwán.",
   "supplies":"Chips de 28nm para automoción, powertrain y electrónica de consumo; packaging OSAT.",
   "moat":"Primero en India con escala; incentivos $2.7B del gobierno indio; PSMC tech transfer.",
   "loc":"India","country":"India","growth":"🔵 Producción 2026-2027; India chip sovereignty","margin":null,"preipo":true,"mkt":""},
  {"id":"Vedanta_Semi","label":"Vedanta-Foxconn Semi","ticker":"No cotiza","cat":"foundry",
   "role":"JV Vedanta-Foxconn para primera fab de chips en India (Gujarat); 28nm process.",
   "supplies":"Chips para India market: consumer electronics, IoT, telecom.",
   "moat":"PLI scheme incentivos + Foxconn process knowhow; primer mover en India fab.",
   "loc":"India","country":"India","growth":"🔵 Planta 2025-2026; India chip sovereignty","margin":null,"preipo":true,"mkt":""},

  // ── AI Inference / Emerging Chips ───────────────────────────────────────
  {"id":"Etched","label":"Etched AI","ticker":"No cotiza","cat":"asic_custom",
   "role":"ASIC Sohu diseñado exclusivamente para ejecutar transformers (sin programabilidad).",
   "supplies":"Sohu chip: 10x más eficiente que GPU para transformer inference; cloud service Sohu Cloud.",
   "moat":"Primer chip single-purpose para transformer: mayor eficiencia FLOPS/W posible en transformers.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 $120M raised; Google, NVIDIA-rival positioning","margin":null,"preipo":true,"mkt":""},
  {"id":"Silicon_Labs","label":"Silicon Laboratories","ticker":"SLAB · Nasdaq","cat":"fabless",
   "role":"Microcontroladores inalámbricos para IoT: Zigbee, Matter, Bluetooth, Z-Wave.",
   "supplies":"EFR32 SoC para Amazon Echo/Google Nest (Zigbee/Matter); chips Thread para smart home.",
   "moat":"Liderazgo en Matter (nuevo estándar smart home): Apple, Amazon, Google usan sus chips.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +20% e. 2026; Matter smart home standard","margin":0.50,"mkt":"SLAB"},

  // ── Satellite Communications ──────────────────────────────────────────────
  {"id":"SES","label":"SES S.A.","ticker":"SESG · Euronext","cat":"satellite",
   "role":"Operador de satélites de segunda generación con flota GEO+MEO (O3b mPOWER) de alta velocidad.",
   "supplies":"O3b mPOWER MEO para broadband marino/remoto; TV/media via GEO para operadores europeos.",
   "moat":"O3b MEO: latencia <150ms en banda Ka para clientes navales y corporativos; C-band FCC award.",
   "loc":"Europa","country":"Europa","growth":"🟢 C-band FCC proceeds + O3b ramp","margin":0.28,"mkt":"SESG.PA"},

  // ── Emerging AI Infrastructure ────────────────────────────────────────────
  {"id":"Together_AI","label":"Together AI","ticker":"No cotiza","cat":"hpc_super",
   "role":"Plataforma cloud para entrenamiento e inferencia de modelos open-source a bajo costo.",
   "supplies":"Training clusters GPU para Llama, Mistral; inference API para 50+ modelos open source.",
   "moat":"Mayor plataforma de modelos open-source: $300M+ ARR; 70% más barato que AWS/Azure para OSS.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 $228M raised; fastest-growing AI infra","margin":null,"preipo":true,"mkt":""},

  // ── Semiconductor Materials ───────────────────────────────────────────────
  {"id":"Cabot_Micro","label":"CMC Materials","ticker":"CCMP · Nasdaq","cat":"chemicals",
   "role":"Slurries CMP (Chemical Mechanical Planarization) para el pulido de obleas en nodos avanzados.",
   "supplies":"Slurries y pads CMP para TSMC, Samsung, Intel; KMG Chemicals (gases electrónicos).",
   "moat":"Cuota ~25% global CMP slurries; co-desarrollo con TSMC en nuevos nodos.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +18% e. 2026; node shrink CMP demand","margin":0.17,"mkt":"CCMP"},

  // ── Emerging Neuromorphic / Edge AI ──────────────────────────────────────
  {"id":"GrAI_Matter","label":"GrAI Matter Labs","ticker":"No cotiza","cat":"neuromorphic",
   "role":"Procesador neuromórfico ultra-eficiente para visión en tiempo real en dispositivos edge.",
   "supplies":"GrAI VIP chip para vision AI <1W; VIP SDK para deployment de vision models en drones.",
   "moat":"Eficiencia energética 100x vs. GPU en inferencia de visión continua; partner Renesas.",
   "loc":"Europa","country":"Europa","growth":"🔵 Series B €15M; drone + auto vision wins","margin":null,"preipo":true,"mkt":""},
  {"id":"Prophesee","label":"Prophesee","ticker":"No cotiza","cat":"neuromorphic",
   "role":"Sensores de visión event-based (bio-inspired): captura cambios de intensidad, no frames.",
   "supplies":"Metavision event-based sensors para robótica, drones, automotriz ADAS.",
   "moat":"Patentes fundacionales en event-based vision; 100x menos datos que cámaras estándar.",
   "loc":"Europa","country":"Europa","growth":"🟢 $74M raised; Sony partnership + Samsung SDC license","margin":null,"preipo":true,"mkt":""},
  {"id":"Esperanto_Tech","label":"Esperanto Technologies","ticker":"No cotiza","cat":"edge_ai",
   "role":"Chips RISC-V masivamente paralelos (1000+ cores) para inferencia LLM de ultra-baja potencia.",
   "supplies":"ET-SoC-1 (1000+ RISC-V cores) para edge inference; AI accelerator para LLM serving.",
   "moat":"Liderazgo en RISC-V para AI: mayor densidad cores/watt en inference; open ISA sin royalties.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 $75M raised; inference market growing","margin":null,"preipo":true,"mkt":""},
  {"id":"Rain_Neuromorphics","label":"Rain Neuromorphics","ticker":"No cotiza","cat":"neuromorphic",
   "role":"Hardware de IA analógico que replica sinápsis cerebrales para training de modelos grandes.",
   "supplies":"Rain AI chip (analógico): entrena modelos 1000x más eficiente que GPU; hardware-software co-design.",
   "moat":"Única empresa con training AI hardware analógico; Sam Altman investment; 1000x efficiency claim.",
   "loc":"EE.UU.","country":"EEUU","growth":"🔵 $25M raised; long-term bet on analog AI","margin":null,"preipo":true,"mkt":""},

  // ── Power / Analog EDA ────────────────────────────────────────────────────
  {"id":"Richtek","label":"Richtek Technology","ticker":"6286 · TWSE","cat":"power",
   "role":"Diseñador de ICs de gestión de energía (PMIC) para AI servers y electrónica de consumo.",
   "supplies":"PMIC para AI GPUs (NVIDIA Hopper power delivery); DDR PMIC; notebook power controllers.",
   "moat":"Cuota creciente en PMIC para AI GPU (alternativa a Monolithic Power en Asia); fabless TSMC.",
   "loc":"Taiwán","country":"Taiwan","growth":"🟢 +30% e. 2026; AI server PMIC demand","margin":0.32,"mkt":"6286.TW"},
  {"id":"PDF_Solutions","label":"PDF Solutions","ticker":"PDFS · Nasdaq","cat":"eda",
   "role":"Software de análisis de rendimiento de fab y datos de proceso para optimizar yield.",
   "supplies":"Exensio plataforma de analítica de datos de fab; CV-eProbe para caracterización de proceso.",
   "moat":"Integrado en flujos de producción de 20+ fabs incluyendo GlobalFoundries, SMIC, tower.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +18% e. 2026; fab analytics for advanced nodes","margin":0.18,"mkt":"PDFS"},

  // ── Wireless Connectivity Chips ──────────────────────────────────────────
  {"id":"Silicon_Labs","label":"Silicon Laboratories","ticker":"SLAB · Nasdaq","cat":"fabless",
   "role":"Microcontroladores inalámbricos para IoT: Zigbee, Matter, Bluetooth, Z-Wave.",
   "supplies":"EFR32 SoC para Amazon Echo/Google Nest (Zigbee/Matter); chips Thread para smart home.",
   "moat":"Liderazgo en Matter (nuevo estándar smart home): Apple, Amazon, Google usan sus chips.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 +20% e. 2026; Matter smart home standard","margin":0.50,"mkt":"SLAB"},

  // ── AI-Driven Fintech ─────────────────────────────────────────────────────
  {"id":"Crane_NXT","label":"Crane NXT","ticker":"CXT · NYSE","cat":"ai_finance",
   "role":"Tecnología de seguridad de billetes, pagos y autenticación de documentos.",
   "supplies":"Máquinas de autenticación de billetes CPI; sensores de seguridad para cajeros ATM.",
   "moat":"Proveedor de Reserva Federal y BCE para detección de billetes falsos; 50+ contratos banco central.",
   "loc":"EE.UU.","country":"EEUU","growth":"🔵 +10% e. 2026; CBDC + payment security","margin":0.22,"mkt":"CXT"},

  // ── Emerging FPGA / Programmable Logic ───────────────────────────────────
  {"id":"FlexLogix","label":"Flex Logix Technologies","ticker":"No cotiza","cat":"fabless",
   "role":"IP de eFPGA (embedded FPGA) y chips de inferencia NN para SoC personalizados.",
   "supplies":"EFLX eFPGA IP para SoC customization; InferX X1 chip para edge AI inference.",
   "moat":"Mayor cuota eFPGA IP (>60%); permite FPGAs dentro de ASICs — único segmento sin Xilinx/Altera.",
   "loc":"EE.UU.","country":"EEUU","growth":"🟢 $42M raised; ARM + Samsung partnerships","margin":null,"preipo":true,"mkt":""},

];

window.NODES_EXPAND3 = NODES_EXPAND3;
