// nodes_expand.js — Khipu Finance · Extended Node Universe
// ~250 additional company nodes across new and existing categories
// Generated 2026-06

var NODES_EXPAND = [

  // ── AI DEFENSE ──────────────────────────────────────────────────
  {
    "id": "L3Harris",
    "label": "L3Harris Technologies",
    "ticker": "LHX · NYSE",
    "cat": "ai_defense",
    "port": "",
    "role": "Electrónica de defensa e inteligencia",
    "supplies": "Sistemas de comunicaciones, sensores ISR y guía de precisión",
    "moat": "Contratos plurianuales DoD; integración vertical de radio y EW",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Backlog $21B; demanda JADC2",
    "margin": 0.15,
    "capex_2026": "~$0.5B",
    "backlog_status": "Robusto",
    "mkt": "LHX"
  },
  {
    "id": "Raytheon",
    "label": "RTX / Raytheon",
    "ticker": "RTX · NYSE",
    "cat": "ai_defense",
    "port": "",
    "role": "Misiles, radar y defensa aérea",
    "supplies": "Patriot, AMRAAM, Stinger; radares AESA para F-35",
    "moat": "Única fuente en múltiples programas críticos de misiles",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Backlog récord $206B",
    "margin": 0.10,
    "capex_2026": "~$2.0B",
    "backlog_status": "Récord",
    "mkt": "RTX"
  },
  {
    "id": "Leidos",
    "label": "Leidos Holdings",
    "ticker": "LDOS · NYSE",
    "cat": "ai_defense",
    "port": "",
    "role": "Tecnología de defensa, inteligencia y salud",
    "supplies": "Sistemas C4ISR, análisis IA, ciberseguridad federal",
    "moat": "Mayor empresa IT de defensa por revenue; backlog $38B+",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Crecimiento orgánico sostenido",
    "margin": 0.09,
    "capex_2026": "~$0.3B",
    "backlog_status": "Récord",
    "mkt": "LDOS"
  },
  {
    "id": "CACI",
    "label": "CACI International",
    "ticker": "CACI · NYSE",
    "cat": "ai_defense",
    "port": "",
    "role": "Inteligencia y soluciones de misión para DoD/IC",
    "supplies": "Analítica IA, guerra electrónica cognitiva, modernización IT",
    "moat": "Especialización en agencias de inteligencia; clearances críticos",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Doble dígito revenue growth",
    "margin": 0.08,
    "capex_2026": "~$0.1B",
    "backlog_status": "Fuerte",
    "mkt": "CACI"
  },
  {
    "id": "Parsons",
    "label": "Parsons Corporation",
    "ticker": "PSN · NYSE",
    "cat": "ai_defense",
    "port": "",
    "role": "Infraestructura crítica y soluciones de defensa",
    "supplies": "Ciberseguridad, inteligencia geoespacial, C5ISR",
    "moat": "Posicionamiento en seguridad nacional y mercados federales",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Adquisiciones estratégicas",
    "margin": 0.07,
    "capex_2026": "~$0.1B",
    "backlog_status": "Estable",
    "mkt": "PSN"
  },
  {
    "id": "SentinelOne",
    "label": "SentinelOne",
    "ticker": "S · NYSE",
    "cat": "ai_defense",
    "port": "",
    "role": "Ciberseguridad autónoma basada en IA",
    "supplies": "Plataforma XDR/EDR, detección de amenazas en tiempo real",
    "moat": "Motor IA Singularity; cobertura endpoint líder vs CrowdStrike",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 ARR >$700M, crecimiento 35%+",
    "margin": -0.10,
    "capex_2026": "~$0.1B",
    "backlog_status": "Hipercrecimiento",
    "mkt": "S"
  },
  {
    "id": "CrowdStrike",
    "label": "CrowdStrike",
    "ticker": "CRWD · NASDAQ",
    "cat": "ai_defense",
    "port": "",
    "role": "Plataforma cloud de ciberseguridad",
    "supplies": "Falcon XDR, threat intelligence, SIEM nativo IA",
    "moat": "Grafo de amenazas con 1T+ eventos/día; efecto red en inteligencia",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 ARR $4B+; mercado GovCloud expansión",
    "margin": 0.12,
    "capex_2026": "~$0.3B",
    "backlog_status": "Fuerte",
    "mkt": "CRWD"
  },
  {
    "id": "C3ai",
    "label": "C3.ai",
    "ticker": "AI · NYSE",
    "cat": "ai_defense",
    "port": "",
    "role": "IA empresarial y aplicaciones federales",
    "supplies": "Suite IA para defensa, energía, manufactura; integración ERP",
    "moat": "Contratos DoD; integración con Microsoft, AWS, Google",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Transición a modelo por uso",
    "margin": -0.30,
    "capex_2026": "~$0.05B",
    "backlog_status": "Incierto",
    "mkt": "AI"
  },

  // ── ASICs / CUSTOM SILICON ──────────────────────────────────────
  {
    "id": "BroadcomASIC",
    "label": "Broadcom (ASIC/HPC)",
    "ticker": "AVGO · NASDAQ",
    "cat": "asic_custom",
    "port": "",
    "role": "ASICs custom para hyperscalers (Google, Meta, Apple)",
    "supplies": "TPU-class XPUs, switching silicon Tomahawk/Trident, SerDes",
    "moat": "Co-diseño exclusivo con Google/Meta; backlog multiaño $20B+",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 AI revenue >$12B en 2026",
    "margin": 0.55,
    "capex_2026": "~$1.5B",
    "backlog_status": "Récord",
    "mkt": "AVGO"
  },
  {
    "id": "AmpereComputing",
    "label": "Ampere Computing",
    "ticker": "Privada",
    "cat": "asic_custom",
    "port": "",
    "role": "CPUs ARM cloud-native de alta eficiencia",
    "supplies": "AmpereOne 192-core; procesadores para inferencia IA en DC",
    "moat": "Arquitectura ARM pura para cloud; 30% mejor perf/watt vs x86",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Design wins en Oracle, Microsoft",
    "margin": 0.25,
    "capex_2026": "~$0.3B",
    "backlog_status": "Crecimiento",
    "preipo": true,
    "mkt": "AMPERE"
  },
  {
    "id": "Tenstorrent",
    "label": "Tenstorrent",
    "ticker": "Privada",
    "cat": "asic_custom",
    "port": "",
    "role": "Hardware IA de código abierto (Jim Keller)",
    "supplies": "Wormhole, Blackhole GPUs/NPUs; stack SW abierto",
    "moat": "Arquitectura RISC-V + Tensix; licenciamiento IP diferenciado",
    "loc": "EE.UU./Canadá",
    "country": "EEUU",
    "growth": "🟢 $700M+ funding; Samsung partnership",
    "margin": 0.10,
    "capex_2026": "~$0.2B",
    "backlog_status": "Early stage",
    "preipo": true,
    "mkt": "TENSTORRENT"
  },
  {
    "id": "Groq",
    "label": "Groq",
    "ticker": "Privada",
    "cat": "asic_custom",
    "port": "",
    "role": "LPU (Language Processing Unit) para inferencia ultra-rápida",
    "supplies": "GroqChip LPU; GroqCloud API; tokens/seg más rápido del mercado",
    "moat": "Arquitectura determinista sin cache; 500T tokens/día inferencia",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 $1.5B valuation; adopción enterprise",
    "margin": 0.05,
    "capex_2026": "~$0.5B",
    "backlog_status": "Expansión",
    "preipo": true,
    "mkt": "GROQ"
  },
  {
    "id": "dMatrix",
    "label": "d-Matrix",
    "ticker": "Privada",
    "cat": "asic_custom",
    "port": "",
    "role": "Chips In-Memory Computing para inferencia IA",
    "supplies": "Corsair IMC; 20x mejor eficiencia vs GPU en inferencia LLM",
    "moat": "Compute-in-memory patentado; Microsoft strategic investment",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Early sampling; Microsoft partnership",
    "margin": 0.00,
    "capex_2026": "~$0.1B",
    "backlog_status": "Pre-revenue",
    "preipo": true,
    "mkt": "DMATRIX"
  },
  {
    "id": "Hailo",
    "label": "Hailo Technologies",
    "ticker": "Privada",
    "cat": "asic_custom",
    "port": "",
    "role": "NPUs Edge IA para automotive y visión",
    "supplies": "Hailo-8, Hailo-15; inferencia IA en dispositivos edge <5W",
    "moat": "Estructura de datos distribuidos patentada; lider edge AI automotive",
    "loc": "Israel",
    "country": "Israel",
    "growth": "🟢 Integración OEMs automotriz",
    "margin": 0.15,
    "capex_2026": "~$0.1B",
    "backlog_status": "Crecimiento",
    "preipo": true,
    "mkt": "HAILO"
  },
  {
    "id": "Esperanto",
    "label": "Esperanto Technologies",
    "ticker": "Privada",
    "cat": "asic_custom",
    "port": "",
    "role": "RISC-V masivamente paralelo para inferencia eficiente",
    "supplies": "ET-SoC-1 con 1000+ cores RISC-V; inferencia LLM eficiente",
    "moat": "Open ISA; densidad de cómputo superior en SoC",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Design wins tempranos",
    "margin": 0.00,
    "capex_2026": "~$0.05B",
    "backlog_status": "Early stage",
    "preipo": true,
    "mkt": "ESPERANTO"
  },

  // ── PHOTONICS / SILICON PHOTONICS ───────────────────────────────
  {
    "id": "Coherent",
    "label": "Coherent Corp (II-VI)",
    "ticker": "COHR · NYSE",
    "cat": "photonics_si",
    "port": "",
    "role": "Componentes fotónicos y láseres industriales",
    "supplies": "Transceptores ópticos 800G+, láseres industriales, SiC para EV",
    "moat": "Portfolio integrado vertical fotónica; único en datacenter + defensa + EV",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Demanda AI datacenters 800G/1.6T",
    "margin": 0.12,
    "capex_2026": "~$0.8B",
    "backlog_status": "Fuerte",
    "mkt": "COHR"
  },
  {
    "id": "Lumentum",
    "label": "Lumentum Holdings",
    "ticker": "LITE · NASDAQ",
    "cat": "photonics_si",
    "port": "",
    "role": "Fotónica para redes ópticas y láseres",
    "supplies": "Transceptores de alta velocidad, VCSEL, láseres industriales",
    "moat": "Tecnología VCSEL líder; contratos Apple 3D sensing",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Recuperación ciclo óptico; AI networking",
    "margin": 0.10,
    "capex_2026": "~$0.3B",
    "backlog_status": "Recuperación",
    "mkt": "LITE"
  },
  {
    "id": "Viavi",
    "label": "Viavi Solutions",
    "ticker": "VIAV · NASDAQ",
    "cat": "photonics_si",
    "port": "",
    "role": "Test y medición de redes ópticas",
    "supplies": "Equipos de prueba para 5G, datacenters ópticos, fibra",
    "moat": "Posición dominante en test de redes ópticas y anti-falsificación",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Ciclo de 5G y AI networking",
    "margin": 0.15,
    "capex_2026": "~$0.1B",
    "backlog_status": "Estable",
    "mkt": "VIAV"
  },
  {
    "id": "AyarLabs",
    "label": "Ayar Labs",
    "ticker": "Privada",
    "cat": "photonics_si",
    "port": "",
    "role": "Interconexión óptica dentro del chip (optical I/O)",
    "supplies": "TeraPHY chiplet óptico; reemplaza cobre con luz dentro del package",
    "moat": "Único optical I/O chiplet in-package; Intel + NVIDIA investment",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Sampleo con hyperscalers 2025-26",
    "margin": 0.00,
    "capex_2026": "~$0.1B",
    "backlog_status": "Pre-comercial",
    "preipo": true,
    "mkt": "AYARLABS"
  },
  {
    "id": "Lightelligence",
    "label": "Lightelligence",
    "ticker": "Privada",
    "cat": "photonics_si",
    "port": "",
    "role": "Computing fotónico para IA",
    "supplies": "Chips ópticos para matrix multiply; AI inference en luz",
    "moat": "Multiplicación matricial óptica 100x más eficiente energéticamente",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Laboratorio a producto",
    "margin": 0.00,
    "capex_2026": "~$0.05B",
    "backlog_status": "I+D",
    "preipo": true,
    "mkt": "LIGHTELLIGENCE"
  },

  // ── NEUROMORPHIC ─────────────────────────────────────────────────
  {
    "id": "IntelLoihi",
    "label": "Intel (Loihi Neuromorphic)",
    "ticker": "INTC · NASDAQ",
    "cat": "neuromorphic",
    "port": "",
    "role": "Computing neuromórfico de bajo consumo",
    "supplies": "Loihi 2 SNN chip; Hala Point sistema 1.15B neuronas",
    "moat": "Mayor sistema neuromórfico del mundo; investigación con 200+ labs",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 I+D largo plazo; pre-comercial",
    "margin": 0.05,
    "capex_2026": "~$10B",
    "backlog_status": "Investigación",
    "mkt": "INTC"
  },
  {
    "id": "BrainChip",
    "label": "BrainChip Holdings",
    "ticker": "BRN · ASX",
    "cat": "neuromorphic",
    "port": "",
    "role": "SNN edge AI chip comercial",
    "supplies": "Akida NPU para detección de patrones ultra low-power",
    "moat": "Primer NPU neuromórfico comercial en mercado edge/IoT",
    "loc": "Australia",
    "country": "Australia",
    "growth": "🟡 Adopción temprana automotive",
    "margin": -0.40,
    "capex_2026": "~$0.02B",
    "backlog_status": "Early",
    "mkt": "BRN.AX"
  },
  {
    "id": "SpiNNcloud",
    "label": "SpiNNcloud Systems",
    "ticker": "Privada",
    "cat": "neuromorphic",
    "port": "",
    "role": "Supercomputación neuromórfica en la nube",
    "supplies": "SpiNNaker2 plataforma; acceso cloud a HPC neuromórfico",
    "moat": "Spin-off TU Dresden; arquitectura masivamente paralela SNN",
    "loc": "Europa",
    "country": "Europa",
    "growth": "🟡 Investigación y primeros clientes",
    "margin": 0.00,
    "capex_2026": "~$0.02B",
    "backlog_status": "Pre-revenue",
    "preipo": true,
    "mkt": "SPINNCLOUD"
  },
  {
    "id": "Innatera",
    "label": "Innatera Nanosystems",
    "ticker": "Privada",
    "cat": "neuromorphic",
    "port": "",
    "role": "NPU analógico ultra-eficiente para edge",
    "supplies": "T1 Neuromorphic SoC; sensores inteligentes <1mW",
    "moat": "Circuitos analógicos subumbrales; 1000x más eficiente que digital",
    "loc": "Europa",
    "country": "Europa",
    "growth": "🟢 Wearables e IoT industrial",
    "margin": 0.00,
    "capex_2026": "~$0.02B",
    "backlog_status": "Sampleo",
    "preipo": true,
    "mkt": "INNATERA"
  },

  // ── DC REITs ─────────────────────────────────────────────────────
  {
    "id": "IronMountain",
    "label": "Iron Mountain",
    "ticker": "IRM · NYSE",
    "cat": "dc_reit",
    "port": "",
    "role": "REIT de almacenamiento y datacenters",
    "supplies": "Colocation, gestión de datos, servicios cloud para empresas",
    "moat": "8.5M+ registros; clientes Fortune 500; 1300 instalaciones globales",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 DC expansion plan $11B 2025-2027",
    "margin": 0.25,
    "capex_2026": "~$3.0B",
    "backlog_status": "Expansión agresiva",
    "mkt": "IRM"
  },
  {
    "id": "QTS",
    "label": "QTS Realty Trust",
    "ticker": "QTS · Privado (Blackstone)",
    "cat": "dc_reit",
    "port": "",
    "role": "Datacenters hiperescala y colocation",
    "supplies": "Campus DC de alta densidad; 10GW+ en desarrollo",
    "moat": "Propiedad Blackstone; 8M sqft capacidad; clientes hyperscalers",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Mayor pipeline DC por MW en EE.UU.",
    "margin": 0.35,
    "capex_2026": "~$5.0B",
    "backlog_status": "Récord",
    "mkt": "BX"
  },
  {
    "id": "CyrusOne",
    "label": "CyrusOne",
    "ticker": "Privado (KKR/GIP)",
    "cat": "dc_reit",
    "port": "",
    "role": "Datacenters enterprise e hiperescala Europa/EE.UU.",
    "supplies": "Colocation, potencia garantizada, conectividad multi-carrier",
    "moat": "Presencia europea estratégica; 50+ datacenters en mercados clave",
    "loc": "EE.UU./Europa",
    "country": "EEUU",
    "growth": "🟢 Expansión europea AI-driven",
    "margin": 0.30,
    "capex_2026": "~$2.0B",
    "backlog_status": "Expansión",
    "mkt": "KKR"
  },
  {
    "id": "DataBank",
    "label": "DataBank",
    "ticker": "Privado (DigitalBridge)",
    "cat": "dc_reit",
    "port": "",
    "role": "Edge datacenters y colocation distribuida",
    "supplies": "70+ DCs en 27 mercados; edge computing, colocation regional",
    "moat": "Mayor proveedor edge DC independiente EE.UU.",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Edge AI crecimiento",
    "margin": 0.28,
    "capex_2026": "~$0.5B",
    "backlog_status": "Estable",
    "mkt": "DATABANK"
  },
  {
    "id": "Switch",
    "label": "Switch (Endeavor DC)",
    "ticker": "Privado (DigitalBridge)",
    "cat": "dc_reit",
    "port": "",
    "role": "Datacenters tier 5 de alta disponibilidad",
    "supplies": "Campus DC SUPERNAP; 100% renovables; máxima redundancia",
    "moat": "Patentes de diseño DC; mayor eficiencia energética del sector",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Crecimiento sostenido AI workloads",
    "margin": 0.40,
    "capex_2026": "~$1.0B",
    "backlog_status": "Expansión",
    "mkt": "DBRG"
  },

  // ── CDN / EDGE ───────────────────────────────────────────────────
  {
    "id": "Fastly",
    "label": "Fastly",
    "ticker": "FSLY · NYSE",
    "cat": "cdn_edge",
    "port": "",
    "role": "CDN edge cloud programable",
    "supplies": "Edge compute, CDN, WAF, streaming de video de baja latencia",
    "moat": "Compute@Edge; streaming HLS más rápido; clientes media premium",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Crecimiento moderado; competencia Cloudflare",
    "margin": -0.15,
    "capex_2026": "~$0.1B",
    "backlog_status": "Estabilización",
    "mkt": "FSLY"
  },
  {
    "id": "Edgio",
    "label": "Edgio (ex-Limelight)",
    "ticker": "EGIO · NASDAQ",
    "cat": "cdn_edge",
    "port": "",
    "role": "Entrega de contenido y edge cloud para media",
    "supplies": "CDN para streaming, edge security, performance web",
    "moat": "Red de más de 200 PoPs; especialización en video OTT",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🔴 Reestructuración; pérdida clientes",
    "margin": -0.25,
    "capex_2026": "~$0.05B",
    "backlog_status": "Riesgo alto",
    "mkt": "EGIO"
  },
  {
    "id": "Imperva",
    "label": "Imperva (Thales)",
    "ticker": "Privado (Thales)",
    "cat": "cdn_edge",
    "port": "",
    "role": "Seguridad de aplicaciones web y datos",
    "supplies": "WAF, DDoS, seguridad de base de datos, CDN con seguridad integrada",
    "moat": "Plataforma unificada WAF+DB security; clientela enterprise global",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Integración con Thales; expansión",
    "margin": 0.20,
    "capex_2026": "~$0.1B",
    "backlog_status": "Integración",
    "mkt": "IMPERVA"
  },
  {
    "id": "Zscaler",
    "label": "Zscaler",
    "ticker": "ZS · NASDAQ",
    "cat": "cdn_edge",
    "port": "",
    "role": "Zero Trust Network Access y SASE cloud",
    "supplies": "ZIA, ZPA, ZDX; plataforma SASE nativa cloud para empresas",
    "moat": "Mayor inline proxy cloud del mundo; 400B+ transacciones/día",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 ARR $2.5B+; expansión enterprise",
    "margin": 0.20,
    "capex_2026": "~$0.3B",
    "backlog_status": "Fuerte",
    "mkt": "ZS"
  },

  // ── AI AUTOMOTIVE ────────────────────────────────────────────────
  {
    "id": "Mobileye",
    "label": "Mobileye Global",
    "ticker": "MBLY · NASDAQ",
    "cat": "ai_auto",
    "port": "",
    "role": "Sistemas ADAS y conducción autónoma",
    "supplies": "EyeQ chips, SuperVision, Drive Kit Plus para OEMs",
    "moat": "700M+ vehículos ADAS; líder NCAP; datos de carretera únicos",
    "loc": "Israel",
    "country": "Israel",
    "growth": "🟢 L2+ expansión masiva; FOTA monetización",
    "margin": 0.18,
    "capex_2026": "~$0.4B",
    "backlog_status": "Backlog multiaño",
    "mkt": "MBLY"
  },
  {
    "id": "Luminar",
    "label": "Luminar Technologies",
    "ticker": "LAZR · NASDAQ",
    "cat": "ai_auto",
    "port": "",
    "role": "LiDAR de largo alcance para ADAS Level 3+",
    "supplies": "Iris+ LiDAR; 250m alcance; integración Volvo, Mercedes, NVIDIA",
    "moat": "1550nm wavelength; mayor rango que competidores; acuerdos OEM firmados",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Rampa producción serie 2025",
    "margin": -0.50,
    "capex_2026": "~$0.2B",
    "backlog_status": "Rampa",
    "mkt": "LAZR"
  },
  {
    "id": "Waymo",
    "label": "Waymo (Alphabet)",
    "ticker": "GOOGL · NASDAQ",
    "cat": "ai_auto",
    "port": "",
    "role": "Robotaxi L4 y stack de conducción autónoma",
    "supplies": "Waymo One servicio robotaxi; Waymo Via carga autónoma",
    "moat": "Mayor dataset de conducción autónoma; 20M+ millas sin conductor",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Expansión ciudades; $5.6B raised 2024",
    "margin": -0.30,
    "capex_2026": "~$2.0B",
    "backlog_status": "Expansión",
    "preipo": true,
    "mkt": "WAYMO"
  },
  {
    "id": "Zoox",
    "label": "Zoox (Amazon)",
    "ticker": "AMZN · NASDAQ",
    "cat": "ai_auto",
    "port": "",
    "role": "Vehículo robotaxi bidireccional propósito específico",
    "supplies": "Vehículo sin volante; batería 133kWh; L5 autonomy stack",
    "moat": "Diseño ground-up sin volante; integración Amazon última milla",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Pruebas en curso; comercialización 2026+",
    "margin": -0.80,
    "capex_2026": "~$1.0B",
    "backlog_status": "Pre-comercial",
    "mkt": "ZOOX"
  },
  {
    "id": "Hesai",
    "label": "Hesai Technology",
    "ticker": "HSAI · NASDAQ",
    "cat": "ai_auto",
    "port": "",
    "role": "LiDAR automotriz de bajo costo (China)",
    "supplies": "PandarGT, AT128; LiDAR para robotaxi, ADAS, robots",
    "moat": "Lider LiDAR China; integración Baidu, SAIC, BYD; bajo costo",
    "loc": "China",
    "country": "China",
    "growth": "🟢 Volumen masivo mercado chino",
    "margin": 0.10,
    "capex_2026": "~$0.3B",
    "backlog_status": "Volumen",
    "mkt": "HSAI"
  },
  {
    "id": "Cepton",
    "label": "Cepton (Koito Mfg)",
    "ticker": "Privado (Koito)",
    "cat": "ai_auto",
    "port": "",
    "role": "LiDAR ADAS integrado en faros automotrices",
    "supplies": "Vista-X90; LiDAR embebido en faros; LIDAR for ADAS Level 2+",
    "moat": "Única integración LiDAR-faro; contratos GM Super Cruise",
    "loc": "EE.UU./Japón",
    "country": "EEUU",
    "growth": "🟢 Rampa GM 2025-26",
    "margin": 0.05,
    "capex_2026": "~$0.1B",
    "backlog_status": "Rampa serial",
    "mkt": "CEPTON"
  },

  // ── AI HEALTH ────────────────────────────────────────────────────
  {
    "id": "Tempus",
    "label": "Tempus AI",
    "ticker": "TEM · NASDAQ",
    "cat": "ai_health",
    "port": "",
    "role": "IA para oncología personalizada y datos clínicos",
    "supplies": "Plataforma genomics+AI; diagnóstico, matching ensayos clínicos",
    "moat": "Mayor biblioteca datos clínico-moleculares del mundo; 250B+ data points",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Revenue $700M+; expansión salud mental y cardio",
    "margin": -0.15,
    "capex_2026": "~$0.2B",
    "backlog_status": "Crecimiento",
    "mkt": "TEM"
  },
  {
    "id": "Recursion",
    "label": "Recursion Pharmaceuticals",
    "ticker": "RXRX · NASDAQ",
    "cat": "ai_health",
    "port": "",
    "role": "Descubrimiento de fármacos impulsado por IA",
    "supplies": "Plataforma BioHive; screening celular masivo + ML para drug discovery",
    "moat": "50PB+ dataset biológico; Exscientia acquisition; NVIDIA partnership",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Pipeline clínico early-stage",
    "margin": -0.50,
    "capex_2026": "~$0.1B",
    "backlog_status": "Investigación",
    "mkt": "RXRX"
  },
  {
    "id": "Veracyte",
    "label": "Veracyte",
    "ticker": "VCYT · NASDAQ",
    "cat": "ai_health",
    "port": "",
    "role": "Diagnóstico genómico de cáncer mediante IA",
    "supplies": "Afirma, Prosigna, Decipher; pruebas genómicas para evitar cirugías",
    "moat": "Datos de expresión génica únicos; validación clínica publicada",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Expansión internacional; nuevas indicaciones",
    "margin": 0.10,
    "capex_2026": "~$0.05B",
    "backlog_status": "Crecimiento",
    "mkt": "VCYT"
  },
  {
    "id": "Butterfly",
    "label": "Butterfly Network",
    "ticker": "BFLY · NYSE",
    "cat": "ai_health",
    "port": "",
    "role": "Ecografía portátil con IA integrada",
    "supplies": "iQ+ transductor de chip único; Butterfly iQ+ con diagnóstico IA",
    "moat": "Único ecógrafo semiconductor completo; 99% reducción costo vs tradional",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Adopción hospitales en desarrollo",
    "margin": -0.45,
    "capex_2026": "~$0.03B",
    "backlog_status": "Escala",
    "mkt": "BFLY"
  },
  {
    "id": "PathAI",
    "label": "PathAI",
    "ticker": "Privada",
    "cat": "ai_health",
    "port": "",
    "role": "Diagnóstico anatomopatológico con IA",
    "supplies": "AISight para análisis de biopsias; CRO digital pathology services",
    "moat": "Partenariados con Bristol-Myers, Roche; validado FDA",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Contratos farmacéuticas big pharma",
    "margin": -0.20,
    "capex_2026": "~$0.05B",
    "backlog_status": "Expansión",
    "preipo": true,
    "mkt": "PATHAI"
  },
  {
    "id": "Insilico",
    "label": "Insilico Medicine",
    "ticker": "Privada",
    "cat": "ai_health",
    "port": "",
    "role": "IA generativa para descubrimiento de fármacos",
    "supplies": "PandaOmics; Chemistry42; candidatos IPF en Fase 2 clínica",
    "moat": "Primer candidato diseñado 100% por IA en Fase 2; generative chemistry",
    "loc": "EE.UU./China/HK",
    "country": "China",
    "growth": "🟢 IPO preparación; pipeline amplio",
    "margin": -0.40,
    "capex_2026": "~$0.1B",
    "backlog_status": "Clínico",
    "preipo": true,
    "mkt": "INSILICO"
  },

  // ── AI FINANCE ───────────────────────────────────────────────────
  {
    "id": "AlphaSenseFin",
    "label": "AlphaSense (Finance AI)",
    "ticker": "Privada",
    "cat": "ai_finance",
    "port": "",
    "role": "Búsqueda e inteligencia de mercados financieros con IA",
    "supplies": "Plataforma LLM para research financiero; sentiment analysis",
    "moat": "10B+ documentos financieros indexados; Enterprise AI para buy-side",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 $4B valuation; Wall Street adoption",
    "margin": 0.10,
    "capex_2026": "~$0.1B",
    "backlog_status": "Expansión",
    "preipo": true,
    "mkt": "ALPHASENSE"
  },
  {
    "id": "Kensho",
    "label": "Kensho Technologies (S&P)",
    "ticker": "SPGI · NYSE",
    "cat": "ai_finance",
    "port": "",
    "role": "Analítica cuantitativa e IA para mercados financieros",
    "supplies": "NERD, Scribe, Classify; datos estructurados IA para S&P Global",
    "moat": "Integración profunda S&P data; NLP financiero especializado",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Expansión en toda la plataforma S&P",
    "margin": 0.35,
    "capex_2026": "~$0.1B",
    "backlog_status": "Integrado",
    "mkt": "SPGI"
  },
  {
    "id": "Kavout",
    "label": "Kavout",
    "ticker": "Privada",
    "cat": "ai_finance",
    "port": "",
    "role": "Predicción de mercados con IA y ranking de acciones",
    "supplies": "Kai score sistema; señales de trading IA para hedge funds",
    "moat": "Algoritmos propietarios ML; clientes institucionales seleccionados",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Mercado competitivo",
    "margin": 0.15,
    "capex_2026": "~$0.01B",
    "backlog_status": "Nicho",
    "preipo": true,
    "mkt": "KAVOUT"
  },
  {
    "id": "Addepar",
    "label": "Addepar",
    "ticker": "Privada",
    "cat": "ai_finance",
    "port": "",
    "role": "Gestión de patrimonio con IA para family offices",
    "supplies": "Plataforma wealth management; reporting multi-asset, analytics IA",
    "moat": "$6T+ AUM en plataforma; network effect datos alternativos",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Alta retención clientes UHNW",
    "margin": 0.10,
    "capex_2026": "~$0.05B",
    "backlog_status": "Crecimiento",
    "preipo": true,
    "mkt": "ADDEPAR"
  },

  // ── AI AGENTS ────────────────────────────────────────────────────
  {
    "id": "Cognition",
    "label": "Cognition AI (Devin)",
    "ticker": "Privada",
    "cat": "ai_agents",
    "port": "",
    "role": "Agente de software development autónomo",
    "supplies": "Devin; primer AI software engineer; coding agent autónomo",
    "moat": "Devin demos virales; $175M Series A; primera mover agentes código",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 $2B valuation; adopción empresas tech",
    "margin": 0.00,
    "capex_2026": "~$0.1B",
    "backlog_status": "Hipercrecimiento",
    "preipo": true,
    "mkt": "COGNITION"
  },
  {
    "id": "Adept",
    "label": "Adept AI",
    "ticker": "Privada",
    "cat": "ai_agents",
    "port": "",
    "role": "Agentes IA para automatizar flujos de trabajo empresariales",
    "supplies": "ACT-1 modelo; Adept Agents para operaciones en software",
    "moat": "Modelo de acción multimodal; integración flujos trabajo enterprise",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Microsoft + NVIDIA investment",
    "margin": 0.00,
    "capex_2026": "~$0.1B",
    "backlog_status": "Desarrollo",
    "preipo": true,
    "mkt": "ADEPT"
  },
  {
    "id": "Inflection",
    "label": "Inflection AI",
    "ticker": "Privada (Microsoft/Pi)",
    "cat": "ai_agents",
    "port": "",
    "role": "IA conversacional personal y agentes empáticos",
    "supplies": "Pi assistant; modelos inflection-2; Microsoft partnership",
    "moat": "Enfoque en inteligencia emocional IA; dataset conversación único",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Pivot post-Microsoft deal",
    "margin": -0.30,
    "capex_2026": "~$0.3B",
    "backlog_status": "Transición",
    "preipo": true,
    "mkt": "INFLECTION"
  },
  {
    "id": "Imbue",
    "label": "Imbue (ex-Generally Intelligent)",
    "ticker": "Privada",
    "cat": "ai_agents",
    "port": "",
    "role": "Agentes IA con razonamiento y código",
    "supplies": "Modelos de agentes con razonamiento multi-paso; coding agents",
    "moat": "Enfoque en agentes que razonan, no solo predicen; $200M raised",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Investigación a producto",
    "margin": -0.50,
    "capex_2026": "~$0.1B",
    "backlog_status": "I+D",
    "preipo": true,
    "mkt": "IMBUE"
  },

  // ── SATELLITE / EARTH OBS ────────────────────────────────────────
  {
    "id": "Eutelsat",
    "label": "Eutelsat / OneWeb",
    "ticker": "ETL · Euronext",
    "cat": "satellite",
    "port": "",
    "role": "Constelación LEO OneWeb + GEO tradicional",
    "supplies": "648 satélites LEO; conectividad broadband en regiones remotas",
    "moat": "Constelación OneWeb operativa; clientes gobierno y aeronáutica",
    "loc": "Europa",
    "country": "Europa",
    "growth": "🟡 Integración compleja; deuda elevada",
    "margin": 0.05,
    "capex_2026": "~$0.5B",
    "backlog_status": "Integración",
    "mkt": "ETL.PA"
  },
  {
    "id": "SpireGlobal",
    "label": "Spire Global",
    "ticker": "SPIR · NYSE",
    "cat": "earth_obs",
    "port": "",
    "role": "Datos de Earth Observation y meteorología satelital",
    "supplies": "100+ nanosatélites; datos AIS/ADS-B/GNSS-RO para clima/marítimo",
    "moat": "Mayor flota nanosatélites datos; NOAA y ESA contratos",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Camino a rentabilidad",
    "margin": -0.20,
    "capex_2026": "~$0.1B",
    "backlog_status": "Escala",
    "mkt": "SPIR"
  },
  {
    "id": "HawkEye360",
    "label": "HawkEye 360",
    "ticker": "Privada",
    "cat": "earth_obs",
    "port": "",
    "role": "Inteligencia RF desde el espacio",
    "supplies": "Detección señales RF; monitoreo marítimo, comunicaciones ilícitas",
    "moat": "Única empresa con constelación dedicada a geolocalización RF espacial",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Contratos DoD/IC; geopolítica favorable",
    "margin": 0.00,
    "capex_2026": "~$0.1B",
    "backlog_status": "Expansión",
    "preipo": true,
    "mkt": "HAWKEYE360"
  },
  {
    "id": "Umbra",
    "label": "Umbra Space",
    "ticker": "Privada",
    "cat": "earth_obs",
    "port": "",
    "role": "Imágenes SAR (Radar de apertura sintética) satelital",
    "supplies": "SAR comercial 16cm resolución; inteligencia geoespacial tiempo real",
    "moat": "Mayor resolución SAR comercial del mercado; clientes gobierno/defensa",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Contratos NRO y defensa",
    "margin": 0.10,
    "capex_2026": "~$0.1B",
    "backlog_status": "Crecimiento",
    "preipo": true,
    "mkt": "UMBRA"
  },
  {
    "id": "CapellaSpace",
    "label": "Capella Space",
    "ticker": "Privada",
    "cat": "earth_obs",
    "port": "",
    "role": "SAR comercial con revisita horaria",
    "supplies": "Constelación SAR; imágenes nocturnas/con nubes; API geoespacial",
    "moat": "Revisita <1h cualquier punto tierra; contratos NGA/NRO",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Expansión constelación; gobierno + comercial",
    "margin": 0.05,
    "capex_2026": "~$0.15B",
    "backlog_status": "Expansión",
    "preipo": true,
    "mkt": "CAPELLASPACE"
  },

  // ── SEMICONDUCTORES ADICIONALES ──────────────────────────────────
  {
    "id": "LatticeSemi",
    "label": "Lattice Semiconductor",
    "ticker": "LSCC · NASDAQ",
    "cat": "fabless",
    "port": "",
    "role": "FPGAs de baja potencia para edge AI e industrial",
    "supplies": "FPGAs Nexus, CrossLink; inferencia IA <1W para robotics/auto",
    "moat": "Única FPGA low-power edge; posición dominante en servidores (BMC)",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Normalización post-boom inventario",
    "margin": 0.28,
    "capex_2026": "~$0.1B",
    "backlog_status": "Normalización",
    "mkt": "LSCC"
  },
  {
    "id": "MaxLinear",
    "label": "MaxLinear",
    "ticker": "MXL · NASDAQ",
    "cat": "fabless",
    "port": "",
    "role": "Semiconductores para banda ancha, 5G y datacenter",
    "supplies": "PAM4 DSPs, cable modem SoCs, Wi-Fi 7 chips, datacenter optical",
    "moat": "Lider PAM4 óptico datacenter; posición en DOCSIS 3.1 broadband",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Ciclo bajista broadband; recuperación 2025",
    "margin": 0.12,
    "capex_2026": "~$0.05B",
    "backlog_status": "Recuperación",
    "mkt": "MXL"
  },
  {
    "id": "Semtech",
    "label": "Semtech",
    "ticker": "SMTC · NASDAQ",
    "cat": "fabless",
    "port": "",
    "role": "Semiconductores LoRa IoT y óptica datacenter",
    "supplies": "LoRa módems, ClearEdge PAM4, Sierra Wireless (IoT celular)",
    "moat": "Estándar LoRa de facto para IoT LP; ClearEdge óptica datacenter",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Post-Sierra integración; IoT recuperación",
    "margin": 0.08,
    "capex_2026": "~$0.1B",
    "backlog_status": "Integración",
    "mkt": "SMTC"
  },
  {
    "id": "SiliconLabs",
    "label": "Silicon Laboratories",
    "ticker": "SLAB · NASDAQ",
    "cat": "fabless",
    "port": "",
    "role": "MCUs y conectividad IoT (Matter, Thread, Zigbee)",
    "supplies": "EFR32 series; BG22 Bluetooth; Matter protocol chips para smart home",
    "moat": "Lider Matter/Thread estándar smart home; energy harvesting ICs",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Inventario normalización; Matter tailwind",
    "margin": 0.15,
    "capex_2026": "~$0.05B",
    "backlog_status": "Normalización",
    "mkt": "SLAB"
  },
  {
    "id": "MonolithicPower",
    "label": "Monolithic Power Systems",
    "ticker": "MPWR · NASDAQ",
    "cat": "power",
    "port": "",
    "role": "Gestión de energía de alta eficiencia para AI/datacenter",
    "supplies": "VRs para GPU/CPU (NVIDIA design wins); POL para servidores IA",
    "moat": "Tecnología CMOS BCD propietaria; ganando cuota en NVIDIA GB200",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Hypercrecimiento AI datacenter VR",
    "margin": 0.30,
    "capex_2026": "~$0.3B",
    "backlog_status": "Récord demanda",
    "mkt": "MPWR"
  },
  {
    "id": "Wolfspeed",
    "label": "Wolfspeed",
    "ticker": "WOLF · NYSE",
    "cat": "materials",
    "port": "",
    "role": "SiC wafers y módulos de potencia para EV e industrial",
    "supplies": "SiC bare wafers, epitaxiales, MOSFETs; fabricante pure-play",
    "moat": "Única fábrica SiC 200mm del mundo; mayor capacidad SiC global",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🔴 Ramp challenges; pérdidas; $2B fab Durham",
    "margin": -0.30,
    "capex_2026": "~$1.5B",
    "backlog_status": "Riesgo financiero",
    "mkt": "WOLF"
  },

  // ── HPC / SUPERCOMPUTING ─────────────────────────────────────────
  {
    "id": "CrayHPE",
    "label": "HPE Cray (Supercomputing)",
    "ticker": "HPE · NYSE",
    "cat": "hpc_super",
    "port": "",
    "role": "Supercomputadoras para gobierno e investigación científica",
    "supplies": "Frontier (#1 TOP500), Perlmutter; sistemas exascale HPC",
    "moat": "Frontier primer exaflop del mundo; contratos DOE, NOAA, NSA",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Exascale era; AI+HPC convergencia",
    "margin": 0.12,
    "capex_2026": "~$1.0B",
    "backlog_status": "Fuerte",
    "mkt": "HPE"
  },
  {
    "id": "Cerebras",
    "label": "Cerebras Systems",
    "ticker": "CBRS · NASDAQ",
    "cat": "hpc_super",
    "port": "",
    "role": "Wafer-Scale Engine para entrenamiento IA",
    "supplies": "WSE-3 chip más grande del mundo; CS-3 sistema; Cerebras Cloud",
    "moat": "WSE único (900B transistores en 1 wafer); latencia inferencia LLM",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 IPO 2024; contratos G42, CoreWeave",
    "margin": -0.10,
    "capex_2026": "~$0.5B",
    "backlog_status": "Expansión post-IPO",
    "mkt": "CBRS"
  },
  {
    "id": "SambaNova",
    "label": "SambaNova Systems",
    "ticker": "Privada",
    "cat": "hpc_super",
    "port": "",
    "role": "Plataforma IA reconfigurable para enterprise y gobierno",
    "supplies": "SN40L chip; RDU reconfigurable dataflow; modelos LLM empresariales",
    "moat": "Dataflow architecture 5x eficiencia vs GPU; contratos DOE labs",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 National labs; enterprise AI",
    "margin": 0.05,
    "capex_2026": "~$0.2B",
    "backlog_status": "Expansión",
    "preipo": true,
    "mkt": "SAMBANOVA"
  },

  // ── EDGE AI ──────────────────────────────────────────────────────
  {
    "id": "Kneron",
    "label": "Kneron",
    "ticker": "Privada",
    "cat": "edge_ai",
    "port": "",
    "role": "SoCs IA edge para visión artificial y biometría",
    "supplies": "KL720, KL530; edge NPU para cámaras, seguridad, automotive",
    "moat": "Procesamiento on-device sin cloud; costos inferiores a chips NVIDIA",
    "loc": "EE.UU./Taiwan",
    "country": "Taiwan",
    "growth": "🟢 Clientes Foxconn, Hon Hai",
    "margin": 0.10,
    "capex_2026": "~$0.05B",
    "backlog_status": "Crecimiento",
    "preipo": true,
    "mkt": "KNERON"
  },
  {
    "id": "Mythic",
    "label": "Mythic AI",
    "ticker": "Privada",
    "cat": "edge_ai",
    "port": "",
    "role": "Inferencia IA analógica ultra-eficiente en edge",
    "supplies": "M1076 AMP chip; compute-in-flash; 10x menos energía vs digital",
    "moat": "Compute-in-memory flash propietario; drones, robots, cámaras",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Financiación limitada; niche market",
    "margin": -0.30,
    "capex_2026": "~$0.02B",
    "backlog_status": "Supervivencia",
    "preipo": true,
    "mkt": "MYTHIC"
  },
  {
    "id": "GreenWaves",
    "label": "GreenWaves Technologies",
    "ticker": "Privada",
    "cat": "edge_ai",
    "port": "",
    "role": "Procesadores ultra-low-power para IoT y edge audio/visión",
    "supplies": "GAP9 SoC RISC-V multi-core; edge AI para wearables e industrial",
    "moat": "RISC-V multi-core open ISA; liderazgo en PULP platform",
    "loc": "Europa",
    "country": "Europa",
    "growth": "🟡 Adopción gradual",
    "margin": 0.00,
    "capex_2026": "~$0.01B",
    "backlog_status": "Early",
    "preipo": true,
    "mkt": "GREENWAVES"
  },
  {
    "id": "EdgeImpulse",
    "label": "Edge Impulse",
    "ticker": "Privada",
    "cat": "edge_ai",
    "port": "",
    "role": "Plataforma MLOps para desarrollo edge AI",
    "supplies": "Herramientas ML deployment MCU/DSP; plataforma TinyML",
    "moat": "Plataforma estándar TinyML; 60k+ developers; Nordic, ST, Arduino",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Ecosystem effect; enterprise expansion",
    "margin": -0.20,
    "capex_2026": "~$0.02B",
    "backlog_status": "Crecimiento plataforma",
    "preipo": true,
    "mkt": "EDGEIMPULSE"
  },

  // ── RARE EARTH / MATERIALS ───────────────────────────────────────
  {
    "id": "MP_Materials",
    "label": "MP Materials",
    "ticker": "MP · NYSE",
    "cat": "rare_earth",
    "port": "",
    "role": "Minería y refinación de tierras raras en EE.UU.",
    "supplies": "NdPr para imanes permanentes; única mina RE activa EE.UU. (Mountain Pass)",
    "moat": "Única fuente doméstica significativa EEUU; contratos GM, DoD",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Independencia RE de China; subsidios IRA",
    "margin": 0.35,
    "capex_2026": "~$0.5B",
    "backlog_status": "Expansión",
    "mkt": "MP"
  },
  {
    "id": "Lynas",
    "label": "Lynas Rare Earths",
    "ticker": "LYC · ASX",
    "cat": "rare_earth",
    "port": "",
    "role": "Mayor productor RE fuera de China",
    "supplies": "CeO, La, Nd, Pr, Dy, Tb; refinería Texas con DoD support",
    "moat": "Única cadena integrada RE fuera China; 10%+ cuota mercado global",
    "loc": "Australia",
    "country": "Australia",
    "growth": "🟢 Expansión refinería Texas; contratos DoD",
    "margin": 0.25,
    "capex_2026": "~$0.4B",
    "backlog_status": "Expansión",
    "mkt": "LYC.AX"
  },
  {
    "id": "EnergyFuels",
    "label": "Energy Fuels",
    "ticker": "UUUU · NYSE",
    "cat": "rare_earth",
    "port": "",
    "role": "Uranio + RE en EE.UU.; monacita separation",
    "supplies": "Separación NdPr de monacita; uranio para reactores nucleares",
    "moat": "White Mesa Mill única instalación RE+U en EE.UU.; permisos únicos",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Nuclear renaissance + RE tailwinds",
    "margin": 0.20,
    "capex_2026": "~$0.1B",
    "backlog_status": "Expansión",
    "mkt": "UUUU"
  },

  // ── BATTERY MATERIALS ────────────────────────────────────────────
  {
    "id": "Livent",
    "label": "Livent (Arcadium Lithium)",
    "ticker": "ALTM · NYSE",
    "cat": "battery_mat",
    "port": "",
    "role": "Productos de litio para baterías EV e industria",
    "supplies": "Hidróxido de litio, carbonato; materiales catódicos para baterías",
    "moat": "Salares Argentina bajo costo; contratos LT con OEMs EV",
    "loc": "EE.UU./Argentina",
    "country": "EEUU",
    "growth": "🟡 Precios litio presionados 2024",
    "margin": 0.15,
    "capex_2026": "~$0.5B",
    "backlog_status": "Ciclo bajo",
    "mkt": "ALTM"
  },
  {
    "id": "Albemarle",
    "label": "Albemarle Corporation",
    "ticker": "ALB · NYSE",
    "cat": "battery_mat",
    "port": "",
    "role": "Mayor productor global de litio",
    "supplies": "Litio, bromo, catalizadores de refinería; mayor productor mundial",
    "moat": "Salares Chile (Atacama); 30%+ cuota mercado global litio",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Corrección precios litio 2024-25",
    "margin": 0.20,
    "capex_2026": "~$1.5B",
    "backlog_status": "Ciclo bajo recuperación",
    "mkt": "ALB"
  },

  // ── SPACE LAUNCH ─────────────────────────────────────────────────
  {
    "id": "RocketLab",
    "label": "Rocket Lab",
    "ticker": "RKLB · NASDAQ",
    "cat": "space_launch",
    "port": "",
    "role": "Lanzamiento pequeño + componentes espaciales",
    "supplies": "Electron (small sat launch), Neutron (en desarrollo), componentes",
    "moat": "Cadencia lanzamiento pequeño más alta del mundo; integración vertical",
    "loc": "EE.UU./NZ",
    "country": "EEUU",
    "growth": "🟢 Neutron 2026; space systems revenue",
    "margin": -0.15,
    "capex_2026": "~$0.3B",
    "backlog_status": "Expansión",
    "mkt": "RKLB"
  },
  {
    "id": "ULA",
    "label": "ULA (United Launch Alliance)",
    "ticker": "Privado (Boeing/LM)",
    "cat": "space_launch",
    "port": "",
    "role": "Lanzamiento confiable para gobierno EE.UU.",
    "supplies": "Vulcan Centaur, Atlas V; misiones críticas DoD/NASA",
    "moat": "100% tasa éxito misiones críticas; NSSL Phase 3 contratos DoD",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Vulcan rampa; NSSL Lane 1 contratos",
    "margin": 0.10,
    "capex_2026": "~$0.3B",
    "backlog_status": "Establecido",
    "mkt": "ULA"
  },
  {
    "id": "Relativity",
    "label": "Relativity Space",
    "ticker": "Privada",
    "cat": "space_launch",
    "port": "",
    "role": "Cohetes impresos en 3D; Terran R reutilizable",
    "supplies": "Terran 1, Terran R (en desarrollo); cohetes con 3D printing",
    "moat": "Mayor estructura impresa 3D del mundo; 60 días manufáctura vs 2 años",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Terran 1 cancelado; pivot Terran R",
    "margin": -0.80,
    "capex_2026": "~$0.3B",
    "backlog_status": "Pivot estratégico",
    "preipo": true,
    "mkt": "RELATIVITY"
  },

  // ── MORE SEMICONDUCTOR ───────────────────────────────────────────
  {
    "id": "Allegro",
    "label": "Allegro MicroSystems",
    "ticker": "ALGM · NASDAQ",
    "cat": "fabless",
    "port": "",
    "role": "Sensores de posición magnéticos y drivers para automotive",
    "supplies": "Current sensors, encoders magnéticos; ADAS y EV powertrain",
    "moat": "Lider sensores magnéticos automotive; custom ASICs para clientes tier-1",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Automotriz normalización inventario",
    "margin": 0.20,
    "capex_2026": "~$0.1B",
    "backlog_status": "Normalización",
    "mkt": "ALGM"
  },
  {
    "id": "Ceva",
    "label": "CEVA",
    "ticker": "CEVA · NASDAQ",
    "cat": "fabless",
    "port": "",
    "role": "IP de DSP y IA para semiconductores",
    "supplies": "CEVA-X NPU IP, XC AI, Bluetooth/Wi-Fi IP; royalties SoC",
    "moat": "IP licenciada en 10B+ chips; ecosistema tools único para NPU",
    "loc": "EE.UU./Israel",
    "country": "Israel",
    "growth": "🟢 IoT y IA embedded crecimiento",
    "margin": 0.25,
    "capex_2026": "~$0.03B",
    "backlog_status": "Crecimiento royalties",
    "mkt": "CEVA"
  },
  {
    "id": "Indie",
    "label": "Indie Semiconductor",
    "ticker": "INDI · NASDAQ",
    "cat": "fabless",
    "port": "",
    "role": "Semiconductores ADAS e infotainment automotriz",
    "supplies": "UWB radar, LiDAR interface, ADAS SoCs, Bluetooth automotive",
    "moat": "Soluciones integradas ADAS low-cost; design wins tier-1 automotive",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Design wins OEM; Radar 4D",
    "margin": -0.15,
    "capex_2026": "~$0.05B",
    "backlog_status": "Rampa",
    "mkt": "INDI"
  },

  // ── ROBOTICS PHYSICAL EXTRA ──────────────────────────────────────
  {
    "id": "Figure",
    "label": "Figure AI",
    "ticker": "Privada",
    "cat": "robotics_physical",
    "port": "",
    "role": "Robot humanoide general para manufactura",
    "supplies": "Figure 01, 02; robot humanoide BMW partnership; OpenAI brain",
    "moat": "$2.6B raised; partnership BMW, OpenAI; más financiado humanoid startup",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Deployment BMW; Figure 02 lanzado",
    "margin": -0.50,
    "capex_2026": "~$0.5B",
    "backlog_status": "Piloto industrial",
    "preipo": true,
    "mkt": "FIGURE"
  },
  {
    "id": "PhysicalIntelligence",
    "label": "Physical Intelligence (π)",
    "ticker": "Privada",
    "cat": "robotics_physical",
    "port": "",
    "role": "Foundation models para robótica física general",
    "supplies": "π0 modelo; política de difusión para control motor general",
    "moat": "Fundadores top robótica (Sergey Levine, Chelsea Finn); $400M raised",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 $2B valuation; research to product",
    "margin": -0.70,
    "capex_2026": "~$0.2B",
    "backlog_status": "I+D",
    "preipo": true,
    "mkt": "PI_ROBOTICS"
  },
  {
    "id": "Apptronik",
    "label": "Apptronik",
    "ticker": "Privada",
    "cat": "robotics_physical",
    "port": "",
    "role": "Robot humanoide Apollo para logística",
    "supplies": "Apollo; robot humanoide para almacén, manufactura; NASA heritage",
    "moat": "NASA spinout; Google investment; foco en seguridad y colaboración humana",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Google + Mercedes pilots",
    "margin": -0.60,
    "capex_2026": "~$0.1B",
    "backlog_status": "Pilotos",
    "preipo": true,
    "mkt": "APPTRONIK"
  },

  // ── QUANTUM ADDITIONAL ───────────────────────────────────────────
  {
    "id": "PsiQuantum",
    "label": "PsiQuantum",
    "ticker": "Privada",
    "cat": "quantum_hw",
    "port": "",
    "role": "Computadora cuántica fotónica a escala de millón de qubits",
    "supplies": "Chips fotónicos cuánticos; fab en GlobalFoundries para escalado",
    "moat": "Único approach fotónico fabricable en fabs CMOS; $620M raised",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Australia $940M deal; GlobalFoundries",
    "margin": -0.90,
    "capex_2026": "~$0.5B",
    "backlog_status": "I+D preclínico",
    "preipo": true,
    "mkt": "PSIQUANTUM"
  },
  {
    "id": "QuEra",
    "label": "QuEra Computing",
    "ticker": "Privada",
    "cat": "quantum_hw",
    "port": "",
    "role": "Computación cuántica de átomos neutros",
    "supplies": "Aquila 256-qubit neutral atom; error correction demos",
    "moat": "Rekord coherencia tiempos; Harvard spinout; Nature papers",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 AWS partnership; DARPA contracts",
    "margin": -0.80,
    "capex_2026": "~$0.1B",
    "backlog_status": "I+D",
    "preipo": true,
    "mkt": "QUERA"
  },
  {
    "id": "Quantinuum",
    "label": "Quantinuum (Honeywell)",
    "ticker": "HON · NASDAQ",
    "cat": "quantum_hw",
    "port": "",
    "role": "Hardware y software cuántico de trampas de iones",
    "supplies": "H-Series trapped-ion QPU; Nexus platform; TKET toolkit",
    "moat": "Mayor fidelity de compuertas 2-qubit del mercado; Microsoft Azure",
    "loc": "EE.UU./UK",
    "country": "EEUU",
    "growth": "🟢 $300M raised; Azure partnership",
    "margin": -0.30,
    "capex_2026": "~$0.2B",
    "backlog_status": "Expansión",
    "preipo": true,
    "mkt": "QUANTINUUM"
  },

  // ── NETWORKING ADDITIONAL ────────────────────────────────────────
  {
    "id": "Sycamore",
    "label": "Sycamore Networks",
    "ticker": "SCMR · NASDAQ",
    "cat": "networking",
    "port": "",
    "role": "Equipos de telecomunicaciones SDH/SONET",
    "supplies": "Equipos red inteligente legacy; transición IP",
    "moat": "Legacy telco installed base",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🔴 Declive; mercado legacy",
    "margin": 0.05,
    "capex_2026": "~$0.01B",
    "backlog_status": "Declive",
    "mkt": "SCMR"
  },
  {
    "id": "Ciena",
    "label": "Ciena Corporation",
    "ticker": "CIEN · NYSE",
    "cat": "networking",
    "port": "",
    "role": "Redes ópticas y control plano de datos",
    "supplies": "Waveserver, 6500 ROADM, WaveLogic modems; redes ópticas coherentes",
    "moat": "WaveLogic tecnología líder coherente; AT&T, Verizon, grandes operadoras",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 AI traffic boom; 400G-800G demand",
    "margin": 0.12,
    "capex_2026": "~$0.2B",
    "backlog_status": "Recuperación fuerte",
    "mkt": "CIEN"
  },
  {
    "id": "Silicom",
    "label": "Silicom Ltd",
    "ticker": "SILC · NASDAQ",
    "cat": "networking",
    "port": "",
    "role": "Tarjetas de red SmartNIC y FPGA para datacenter",
    "supplies": "SmartNICs, FPGA-based network cards; DPU para offload",
    "moat": "Customización OEM para HPE, Dell; FPGA flex para clientes clave",
    "loc": "Israel",
    "country": "Israel",
    "growth": "🟡 Competencia Intel/NVIDIA DPU",
    "margin": 0.18,
    "capex_2026": "~$0.03B",
    "backlog_status": "Estable",
    "mkt": "SILC"
  },

  // ── AISOFT ADDITIONAL ────────────────────────────────────────────
  {
    "id": "Runway",
    "label": "Runway ML",
    "ticker": "Privada",
    "cat": "aisoft",
    "port": "",
    "role": "Video generativo e IA creativa",
    "supplies": "Gen-3 Alpha; video-to-video, text-to-video para creadores",
    "moat": "Herramienta estándar creativo Hollywood; premiere integrations",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 $1.5B valuation; estudio adopción",
    "margin": -0.20,
    "capex_2026": "~$0.1B",
    "backlog_status": "Hipercrecimiento",
    "preipo": true,
    "mkt": "RUNWAY"
  },
  {
    "id": "Suno",
    "label": "Suno AI",
    "ticker": "Privada",
    "cat": "aisoft",
    "port": "",
    "role": "Generación musical con IA",
    "supplies": "Suno v4; canciones completas desde texto en segundos",
    "moat": "10M+ usuarios; modelo de audio más avanzado; partenariados discográficas",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Viralidad; $125M raised",
    "margin": -0.40,
    "capex_2026": "~$0.05B",
    "backlog_status": "Hipercrecimiento",
    "preipo": true,
    "mkt": "SUNO"
  },
  {
    "id": "Perplexity",
    "label": "Perplexity AI",
    "ticker": "Privada",
    "cat": "aisoft",
    "port": "",
    "role": "Motor de búsqueda conversacional con IA",
    "supplies": "Answer engine; Pro search; API para desarrolladores",
    "moat": "100M+ usuarios; respuestas con citas; modelo ads sin SEO gaming",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 $9B valuation; SoftBank investment",
    "margin": -0.25,
    "capex_2026": "~$0.2B",
    "backlog_status": "Hipercrecimiento",
    "preipo": true,
    "mkt": "PERPLEXITY"
  },
  {
    "id": "Glean",
    "label": "Glean",
    "ticker": "Privada",
    "cat": "aisoft",
    "port": "",
    "role": "Búsqueda empresarial unificada con IA",
    "supplies": "Workplace AI search; conectores 100+ fuentes; Glean Agents",
    "moat": "Búsqueda semántica cross-SaaS; $4.6B valuation; adopción enterprise",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 $260M ARR; Fortune 500 clientes",
    "margin": -0.15,
    "capex_2026": "~$0.1B",
    "backlog_status": "Expansión enterprise",
    "preipo": true,
    "mkt": "GLEAN"
  },
  {
    "id": "Cohere",
    "label": "Cohere",
    "ticker": "Privada",
    "cat": "aisoft",
    "port": "",
    "role": "LLMs enterprise para RAG y búsqueda semántica",
    "supplies": "Command R+, Embed, Rerank; despliegue on-prem para enterprise",
    "moat": "Especialización enterprise; on-premise deployment; Oracle partnership",
    "loc": "Canadá",
    "country": "EEUU",
    "growth": "🟢 $5B valuation; Oracle cloud deal",
    "margin": -0.30,
    "capex_2026": "~$0.3B",
    "backlog_status": "Expansión enterprise",
    "preipo": true,
    "mkt": "COHERE"
  },

  // ── EDA TOOLS ADDITIONAL ─────────────────────────────────────────
  {
    "id": "AnsysEDA",
    "label": "Ansys (EDA/Simulation)",
    "ticker": "ANSS · NASDAQ",
    "cat": "eda",
    "port": "",
    "role": "Simulación multifísica para semiconductores e ingeniería",
    "supplies": "HFSS, Redhawk-SC; simulación electromagnética, térmica, SI/PI chips",
    "moat": "Estándar industria simulación; adquirido por Synopsys $35B (2023)",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 Integración Synopsys; AI-driven simulation",
    "margin": 0.30,
    "capex_2026": "~$0.2B",
    "backlog_status": "Integración",
    "mkt": "ANSS"
  },

  // ── CONNECTIVITY ADDITIONAL ──────────────────────────────────────
  {
    "id": "Viasat",
    "label": "ViaSat",
    "ticker": "VSAT · NASDAQ",
    "cat": "connectivity_infra",
    "port": "",
    "role": "Satélites de banda ancha y conectividad en aviones",
    "supplies": "ViaSat-3 GEO satellites; Ka-band broadband; in-flight WiFi",
    "moat": "Mayor capacidad Ka-band por satélite; contratos DOD y aerolineas",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟡 Desafíos ViaSat-3; deuda post-Inmarsat",
    "margin": 0.08,
    "capex_2026": "~$1.5B",
    "backlog_status": "Reestructuración",
    "mkt": "VSAT"
  },
  {
    "id": "Iridium",
    "label": "Iridium Communications",
    "ticker": "IRDM · NASDAQ",
    "cat": "connectivity_infra",
    "port": "",
    "role": "Comunicaciones satelitales globales LEO (66 satélites)",
    "supplies": "Cobertura polar 100%; IoT satelital; Iridium NEXT constelación",
    "moat": "Única cobertura polar verdadera; contratos DoD, marítimo, aviación",
    "loc": "EE.UU.",
    "country": "EEUU",
    "growth": "🟢 IoT satelital + Apple Emergency SOS",
    "margin": 0.30,
    "capex_2026": "~$0.2B",
    "backlog_status": "Estable",
    "mkt": "IRDM"
  }

];
