// nodes/private_valuations.js — GENERADO por scripts/build_private_valuations.py.
// Última valuación CERRADA verificada con fuente de empresas privadas (y la
// negociación, aparte). Lo "en vivo" lo agrega el Dossier desde los titulares
// (/api/company/valuation). No editar a mano: regenerar con una verificación nueva.
window.PRIVATE_VALUATIONS = {
 "as_of": "2026-09-29",
 "entries": {
  "01AI": {
   "valuation_usd_b": 1.0,
   "as_of": "2023-11",
   "lead": "Alibaba Cloud",
   "talks_note_es": "Bloomberg (jul-2026): prepara ronda pre-IPO antes de cotizar en Hong Kong en 2027; valuación no reportada.",
   "talks_note_en": "Bloomberg (Jul 2026): preparing a pre-IPO round ahead of a 2027 Hong Kong listing; valuation not reported.",
   "note_es": "Alcanzó una valuación de ~$1.000M en nov-2023 con respaldo de Alibaba Cloud; en 2026 pivotó a software empresarial.",
   "note_en": "Reached a ~$1B valuation in Nov 2023 backed by Alibaba Cloud; pivoted to enterprise software in 2026.",
   "source_url": "https://techcrunch.com/2023/11/05/valued-at-1b-kai-fu-lees-llm-startup-unveils-open-source-model/",
   "talks_source_url": "https://www.bloomberg.com/news/articles/2026-07-20/ai-pioneer-kai-fu-lee-s-startup-targets-hong-kong-ipo-next-year",
   "confidence": "medium",
   "label": "$1B (2023-11)"
  },
  "Agility": {
   "valuation_usd_b": 2.5,
   "as_of": "2026-06-24",
   "round": "Fusión SPAC (acuerdo)",
   "raised": "n/d",
   "lead": "Churchill Capital Corp XI",
   "status_note": "Saliendo a bolsa vía SPAC (Churchill Capital Corp XI), cierre esperado en 2026.",
   "note_es": "Acordó salir a bolsa vía SPAC con Churchill Capital XI a ~$2.500M implícitos (24-jun-2026); última ronda privada $400M a ~$2.100M (mar-2025).",
   "note_en": "Agreed to go public via SPAC with Churchill Capital XI at ~$2.5B implied (Jun 24, 2026); last private round $400M at ~$2.1B (Mar 2025).",
   "source_url": "https://techcrunch.com/2026/07/05/this-humanoid-robotics-company-is-going-public-but-its-ceo-isnt-promising-a-robot-in-your-home-anytime-soon/",
   "confidence": "medium",
   "label": "$2.5B (2026-06-24)"
  },
  "AlphaSense": {
   "valuation_usd_b": 7.5,
   "as_of": "2026-06-03",
   "round": "Ronda de crecimiento",
   "raised": "$350M",
   "lead": "Vitruvian Partners, Accenture Ventures, J.P. Morgan AM",
   "note_es": "Última ronda cerrada: $350M a una valuación de $7.500M (jun-2026).",
   "note_en": "Last closed round: $350M at a $7.5B valuation (Jun 2026).",
   "source_url": "https://www.alpha-sense.com/press/alphasense-raises-350m-at-7-5b-valuation-and-surpasses-600m-in-annual-recurring-revenue/",
   "confidence": "high",
   "label": "$7.5B (2026-06-03)"
  },
  "AlphaSenseFin": {
   "valuation_usd_b": 7.5,
   "as_of": "2026-06-03",
   "round": "Ronda de crecimiento",
   "raised": "$350M",
   "lead": "Vitruvian Partners, Accenture Ventures, J.P. Morgan AM",
   "note_es": "Última ronda cerrada: $350M a una valuación de $7.500M (jun-2026).",
   "note_en": "Last closed round: $350M at a $7.5B valuation (Jun 2026).",
   "source_url": "https://www.alpha-sense.com/press/alphasense-raises-350m-at-7-5b-valuation-and-surpasses-600m-in-annual-recurring-revenue/",
   "confidence": "high",
   "label": "$7.5B (2026-06-03)"
  },
  "Anduril": {
   "valuation_usd_b": 61,
   "as_of": "2026-05-13",
   "round": "Serie H",
   "raised": "$5B",
   "lead": "Thrive Capital, Andreessen Horowitz",
   "talks_usd_b": 100,
   "talks_note_es": "Conversaciones (jul-2026, no cerradas) para una ronda a ~$100.000M.",
   "talks_note_en": "Talks (Jul 2026, not closed) for a round at ~$100B.",
   "note_es": "Última ronda cerrada: Serie H de $5.000M a una valuación de $61.000M (13-may-2026).",
   "note_en": "Last closed round: $5B Series H at a $61B valuation (May 13, 2026).",
   "source_url": "https://techcrunch.com/2026/05/13/anduril-raises-5b-doubles-valuation-to-61b/",
   "talks_source_url": "https://techcrunch.com/2026/07/24/anduril-reportedly-in-talks-to-raise-funding-at-100b-valuation-more-than-3x-last-years-mark/",
   "confidence": "high",
   "label": "$61B (2026-05-13)"
  },
  "Anthropic": {
   "valuation_usd_b": 965,
   "as_of": "2026-05-28",
   "round": "Serie H",
   "raised": "$65B",
   "lead": "Altimeter, Dragoneer, Greenoaks, Sequoia",
   "status_note": "Sigue privada; presentó confidencialmente para IPO (jun-2026).",
   "note_es": "Última ronda cerrada: Serie H de $65.000M a una valuación post-money de $965.000M (28-may-2026).",
   "note_en": "Last closed round: $65B Series H at a $965B post-money valuation (May 28, 2026).",
   "source_url": "https://www.anthropic.com/news/series-h",
   "confidence": "high",
   "label": "$965B (2026-05-28)"
  },
  "Apptronik": {
   "valuation_usd_b": 5.5,
   "as_of": "2026-02-11",
   "round": "Extensión Serie A",
   "raised": "$520M",
   "lead": "B Capital, Google, Mercedes-Benz, PEAK6",
   "note_es": "Última ronda cerrada: extensión de Serie A de $520M a una valuación de más de $5.500M (11-feb-2026; CNBC reporta ~$5.000M).",
   "note_en": "Last closed round: $520M Series A extension at a valuation above $5.5B (Feb 11, 2026; CNBC reports ~$5B).",
   "source_url": "https://www.bloomberg.com/news/articles/2026-02-11/apptronik-raises-520-million-in-new-funding-to-build-more-humanoids",
   "confidence": "medium",
   "label": "$5.5B (2026-02-11)"
  },
  "AyarLabs": {
   "valuation_usd_b": 3.75,
   "as_of": "2026-03",
   "round": "Serie E (+ext. sept-2026)",
   "raised": "$500M + $150M",
   "lead": "Neuberger Berman; Wiwynn (ext.)",
   "note_es": "Última ronda cerrada: Serie E de $500M a una valuación de $3.750M (mar-2026), ampliada con $150M en sept-2026.",
   "note_en": "Last closed round: $500M Series E at a $3.75B valuation (Mar 2026), extended by $150M in Sep 2026.",
   "source_url": "https://pulse2.com/ayar-labs-500-million-series-e-raised-at-3-75-billion-valuation-for-optics-solutions-for-ai-scale-up/",
   "confidence": "medium",
   "label": "$3.75B (2026-03)"
  },
  "ByteDance": {
   "valuation_usd_b": 330,
   "as_of": "2025-08",
   "round": "Recompra a empleados",
   "raised": "n/d",
   "talks_usd_b": 550,
   "talks_note_es": "Venta secundaria de General Atlantic reportada a ~$550.000M (feb-2026); no es ronda primaria.",
   "talks_note_en": "General Atlantic secondary sale reported at ~$550B (Feb 2026); not a primary round.",
   "note_es": "Última recompra a empleados: $200,41/acción, ~$330.000M (ago-2025); ventas secundarias posteriores a ~$480.000-550.000M.",
   "note_en": "Last employee buyback: $200.41/share, ~$330B (Aug 2025); later secondary sales at ~$480-550B.",
   "source_url": "https://seekingalpha.com/news/4489637-bytedance-valuation-rises-past-330b-amid-new-employee-buyback-program-report",
   "talks_source_url": "https://www.pymnts.com/news/investment-tracker/2026/bytedance-valuation-hits-550-billion-in-planned-share-sale/",
   "confidence": "medium",
   "label": "$330B (2025-08)"
  },
  "CharacterAI": {
   "valuation_usd_b": 2.5,
   "as_of": "2024-08",
   "raised": "~$2.7B (licencia de Google)",
   "lead": "Google",
   "status_note": "Independiente tras el acuerdo de licencia con Google (2024); su CEO Karandeep Anand pasó a Disney como CTO (sept-2026).",
   "note_es": "Google pagó ~$2.700M (ago-2024) por licenciar su tecnología y recontratar a sus fundadores; los inversores salieron a una valuación cercana a $2.500M. Sin ronda nueva en 2026.",
   "note_en": "Google paid ~$2.7B (Aug 2024) to license its tech and rehire its founders; investors were bought out at a ~$2.5B valuation. No new round in 2026.",
   "source_url": "https://www.revenuememo.com/p/who-owns-character-ai",
   "confidence": "medium",
   "label": "$2.5B (2024-08)"
  },
  "Cognition": {
   "valuation_usd_b": 26,
   "as_of": "2026-05-27",
   "round": "Ronda de crecimiento",
   "raised": "$1B+",
   "lead": "Lux Capital, General Catalyst, 8VC",
   "talks_usd_b": 40,
   "talks_note_es": "Conversaciones tempranas (ago-2026) a ≥$40.000M, no cerradas.",
   "talks_note_en": "Early talks (Aug 2026) at ≥$40B, not closed.",
   "note_es": "Última ronda cerrada: más de $1.000M a $25.000M pre-money (~$26.000M post-money) (may-2026).",
   "note_en": "Last closed round: over $1B at $25B pre-money (~$26B post-money) (May 2026).",
   "source_url": "https://techcrunch.com/2026/05/27/ai-coding-startup-cognition-raises-1b-at-25b-pre-money-valuation/",
   "confidence": "high",
   "label": "$26B (2026-05-27)"
  },
  "Cohere": {
   "valuation_usd_b": 7,
   "as_of": "2025-09",
   "round": "Extensión Serie D",
   "raised": "$100M",
   "talks_usd_b": 20,
   "talks_note_es": "Fusión acordada con Aleph Alpha (~$20.000M combinada, sept-2026) y conversaciones para $2.000-3.000M a ~$20.000M; no cerrado.",
   "talks_note_en": "Definitive merger with Aleph Alpha (~$20B combined, Sep 2026) and talks to raise $2-3B at ~$20B; not closed.",
   "note_es": "Última ronda cerrada: extensión de $100M a una valuación de $7.000M (2025).",
   "note_en": "Last closed round: $100M extension at a $7B valuation (2025).",
   "source_url": "https://betakit.com/coheres-valuation-hits-7-billion-usd-following-100-million-round-extension/",
   "talks_source_url": "https://siliconangle.com/2026/09/16/cohere-and-aleph-alpha-agree-to-merge-in-reported-20b-deal/",
   "confidence": "medium",
   "label": "$7B (2025-09)"
  },
  "Databricks": {
   "valuation_usd_b": 190,
   "as_of": "2026-08-13",
   "round": "Ronda estratégica",
   "raised": "$5B",
   "lead": "Coatue",
   "note_es": "Última ronda cerrada: $5.000M a una valuación de $190.000M (ago-2026).",
   "note_en": "Last closed round: $5B at a $190B valuation (Aug 2026).",
   "source_url": "https://www.bloomberg.com/news/articles/2026-08-13/databricks-raises-5-billion-at-a-190-billion-valuation",
   "confidence": "high",
   "label": "$190B (2026-08-13)"
  },
  "DeepSeek": {
   "valuation_usd_b": 52,
   "as_of": "2026-07",
   "round": "Primera ronda externa",
   "raised": "~CNY 50.000M (~$7.400M)",
   "lead": "Tencent (mayor externo), CATL",
   "talks_usd_b": 70,
   "talks_note_es": "SCMP: negocia una nueva ronda a ~$70.000M pre-money; TechCrunch (jul-2026): ~$1.500M antes de una IPO.",
   "talks_note_en": "SCMP: negotiating a new round at ~$70B pre-money; TechCrunch (Jul 2026): ~$1.5B before an IPO.",
   "note_es": "Primera ronda externa: ~CNY 50.000M (~$7.400M) con Tencent y CATL a más de CNY 350.000M (~$52.000M) post-money, según un filing en China (jul-2026).",
   "note_en": "First outside round: ~CNY 50B (~$7.4B) with Tencent and CATL at over CNY 350B (~$52B) post-money, per a Chinese filing (Jul 2026).",
   "source_url": "https://www.caixinglobal.com/2026-07-17/deepseek-reaches-52-billion-valuation-in-round-backed-by-tencent-catl-102465358.html",
   "talks_source_url": "https://www.scmp.com/tech/big-tech/article/3360626/ai-investor-mania-chinas-deepseek-chases-us70-billion-valuation-fresh-round",
   "confidence": "medium",
   "label": "$52B (2026-07)"
  },
  "ElevenLabs": {
   "valuation_usd_b": 11,
   "as_of": "2026-02-04",
   "round": "Serie D",
   "raised": "$500M",
   "lead": "Sequoia Capital",
   "note_es": "Última ronda cerrada: Serie D de $500M a una valuación de $11.000M (4-feb-2026).",
   "note_en": "Last closed round: $500M Series D at an $11B valuation (Feb 4, 2026).",
   "source_url": "https://elevenlabs.io/blog/series-d",
   "confidence": "high",
   "label": "$11B (2026-02-04)"
  },
  "Etched": {
   "valuation_usd_b": 21,
   "as_of": "2026-08-18",
   "round": "Ronda de crecimiento",
   "raised": "$700M",
   "lead": "Jane Street",
   "note_es": "Última ronda cerrada: $700M a una valuación de $21.000M (ago-2026).",
   "note_en": "Last closed round: $700M at a $21B valuation (Aug 2026).",
   "source_url": "https://techcrunch.com/2026/08/18/etcheds-valuation-doubles-to-21b-in-a-month/",
   "confidence": "high",
   "label": "$21B (2026-08-18)"
  },
  "Figure": {
   "valuation_usd_b": 39,
   "as_of": "2025-09",
   "round": "Serie C",
   "raised": ">$1B",
   "lead": "Parkway Venture Capital",
   "note_es": "Última ronda cerrada: Serie C de más de $1.000M a una valuación post-money de $39.000M (sept-2025); sin ronda nueva confirmada en 2026.",
   "note_en": "Last closed round: Series C of over $1B at a $39B post-money valuation (Sep 2025); no new round confirmed in 2026.",
   "source_url": "https://www.figure.ai/news/series-c",
   "confidence": "high",
   "label": "$39B (2025-09)"
  },
  "Glean": {
   "valuation_usd_b": 7.2,
   "as_of": "2025-06",
   "round": "Serie F",
   "raised": "$150M",
   "lead": "Wellington Management",
   "note_es": "Última ronda cerrada: Serie F de $150M a una valuación de $7.200M (jun-2025).",
   "note_en": "Last closed round: $150M Series F at a $7.2B valuation (Jun 2025).",
   "source_url": "https://www.glean.com/press/glean-raises-150m-series-f-at-7-2b-valuation-to-accelerate-enterprise-ai-agent-innovation-globally",
   "confidence": "high",
   "label": "$7.2B (2025-06)"
  },
  "Groq": {
   "valuation_usd_b": 3.5,
   "as_of": "2026-08-17",
   "round": "Ronda de crecimiento",
   "raised": "$350M",
   "status_note": "Privada; Nvidia licenció su tecnología LPU y contrató al equipo directivo (dic-2025); pivote a neocloud.",
   "note_es": "Última ronda cerrada: $350M a una valuación de $3.500M (ago-2026), tras la licencia a Nvidia (~$17.000M) y la salida de su CEO.",
   "note_en": "Last closed round: $350M at a $3.5B valuation (Aug 2026), after the Nvidia license deal (~$17B) and CEO departure.",
   "source_url": "https://techcrunch.com/2026/08/17/groq-raises-350m-to-fuel-its-pivot-from-ai-chips-to-neocloud/",
   "confidence": "high",
   "label": "$3.5B (2026-08-17)"
  },
  "Helion": {
   "valuation_usd_b": 15.5,
   "as_of": "2026-06",
   "round": "Serie G",
   "raised": "$465M",
   "lead": "Thrive Capital",
   "note_es": "Última ronda cerrada: Serie G de $465M a una valuación de $15.500M (jun-2026).",
   "note_en": "Last closed round: $465M Series G at a $15.5B valuation (Jun 2026).",
   "source_url": "https://www.geekwire.com/2026/helion-hits-15-5b-valuation-with-465m-in-new-cash-to-commercialize-fusion-this-decade/",
   "confidence": "high",
   "label": "$15.5B (2026-06)"
  },
  "HuggingFace": {
   "valuation_usd_b": 12.93,
   "as_of": "2026-09-02",
   "round": "Adquisición (acuerdo definitivo)",
   "raised": "$12.93B (precio)",
   "lead": "NVIDIA (comprador)",
   "status_note": "En proceso de adquisición por NVIDIA (acuerdo definitivo 2-sept-2026, pendiente de cierre).",
   "note_es": "Nvidia acordó comprarla por ~$12.930M (2-sept-2026); cierre esperado en 1S-2027. Última ronda: $4.500M (Serie D, 2023).",
   "note_en": "Nvidia agreed to acquire it for ~$12.93B (Sep 2, 2026); closing expected 1H 2027. Last round: $4.5B (Series D, 2023).",
   "source_url": "https://blogs.nvidia.com/blog/nvidia-to-acquire-hugging-face/",
   "confidence": "high",
   "label": "$12.93B (2026-09-02)"
  },
  "ICEYE": {
   "valuation_usd_b": 11.5,
   "as_of": "2026-06-09",
   "round": "Serie F",
   "raised": "€1B (incl. €450M primario)",
   "lead": "General Atlantic",
   "note_es": "Última ronda cerrada: €1.000M (incl. secundario) a más de €10.000M (~$11.500M) (jun-2026).",
   "note_en": "Last closed round: €1B (incl. secondary) at over €10B (~$11.5B) (Jun 2026).",
   "source_url": "https://www.bloomberg.com/news/articles/2026-06-09/iceye-valuation-jumps-to-10-billion-in-funding-round-led-by-general-atlantic",
   "confidence": "high",
   "label": "$11.5B (2026-06-09)"
  },
  "Imbue": {
   "valuation_usd_b": 1.0,
   "as_of": "2023-09",
   "round": "Serie B",
   "raised": "$200M",
   "lead": "Astera Institute (con Nvidia)",
   "note_es": "Serie B de $200M (sept-2023) con Astera y Nvidia a una valuación de más de $1.000M; sin rondas nuevas.",
   "note_en": "$200M Series B (Sep 2023) with Astera and Nvidia at a valuation of over $1B; no newer rounds.",
   "source_url": "https://www.bwdisrupt.com/article/ai-startup-imbue-raises-200mn-at-over-1bn-valuation-490472",
   "confidence": "medium",
   "label": "$1B (2023-09)"
  },
  "LambdaLabs": {
   "valuation_usd_b": 5.9,
   "as_of": "2025-11",
   "round": "Serie E",
   "raised": "$1.5B+",
   "lead": "TWG Global",
   "talks_usd_b": 12,
   "talks_note_es": "Conversaciones (ago-2026) para una ronda pre-IPO de hasta $3.000M a ≥$12.000M; no cerrada.",
   "talks_note_en": "Talks (Aug 2026) for a pre-IPO round of up to $3B at ≥$12B; not closed.",
   "note_es": "Última ronda cerrada: Serie E de más de $1.500M a ~$5.900M post-money (nov-2025).",
   "note_en": "Last closed round: $1.5B+ Series E at ~$5.9B post-money (Nov 2025).",
   "source_url": "https://www.businesswire.com/news/home/20251118345878/en/Lambda-Raises-Over-$1.5B-From-TWG-Global-USIT-to-Build-Superintelligence-Cloud-Infrastructure",
   "talks_source_url": "https://www.bloomberg.com/news/articles/2026-08-24/ai-cloud-provider-lambda-in-talks-for-3-billion-pre-ipo-round",
   "confidence": "medium",
   "label": "$5.9B (2025-11)"
  },
  "LangChain": {
   "valuation_usd_b": 1.25,
   "as_of": "2025-10-20",
   "round": "Serie B",
   "raised": "$125M",
   "lead": "IVP",
   "note_es": "Última ronda cerrada: Serie B de $125M a ~$1.250-1.300M (oct-2025).",
   "note_en": "Last closed round: $125M Series B at ~$1.25-1.3B (Oct 2025).",
   "source_url": "https://www.langchain.com/blog/series-b",
   "confidence": "medium",
   "label": "$1.25B (2025-10-20)"
  },
  "Mistral": {
   "valuation_usd_b": 24.5,
   "as_of": "2026-09-08",
   "round": "Serie D",
   "raised": "€3B (~$3.5B)",
   "lead": "Samsung Electronics; co-líderes EQT Scaleup Europe Fund, PSG Equity",
   "note_es": "Última ronda cerrada: Serie D de €3.000M a más de €21.000M post-money (~$24.500M) (8-sept-2026).",
   "note_en": "Last closed round: €3B Series D at over €21B post-money (~$24.5B) (Sep 8, 2026).",
   "source_url": "https://techcrunch.com/2026/09/08/mistral-raises-e3b-as-sovereign-ai-becomes-big-business/",
   "confidence": "high",
   "label": "$24.5B (2026-09-08)"
  },
  "Nuro": {
   "valuation_usd_b": 6,
   "as_of": "2025-08-21",
   "round": "Serie E",
   "note_es": "Última ronda cerrada: Serie E a una valuación de $6.000M (ago-2025).",
   "note_en": "Last closed round: Series E at a $6B valuation (Aug 2025).",
   "source_url": "https://www.nuro.ai/blog/nuro-announces-series-e-financing-at-6b-valuation-backed-by-leading-financial-and-strategic-investors",
   "confidence": "medium",
   "label": "$6B (2025-08-21)"
  },
  "OpenAI": {
   "valuation_usd_b": 852,
   "as_of": "2026-03-31",
   "round": "Primary (ronda récord)",
   "raised": "$122B",
   "lead": "SoftBank (co-líder) con Amazon, Nvidia, Microsoft",
   "talks_usd_b": 1200,
   "talks_note_es": "Conversaciones (no cerradas) para una ronda pre-IPO a ~$1,2 billones.",
   "talks_note_en": "Reported talks (not closed) for a pre-IPO round at ~$1.2T.",
   "status_note": "Sigue privada; presentó S-1 confidencial (jun-2026); IPO ya no esperada en 2026 según reportes.",
   "note_es": "Última ronda cerrada: $122.000M a una valuación post-money de $852.000M (31-mar-2026).",
   "note_en": "Last closed round: $122B at an $852B post-money valuation (Mar 31, 2026).",
   "source_url": "https://openai.com/index/accelerating-the-next-phase-ai/",
   "talks_source_url": "https://www.pymnts.com/news/artificial-intelligence/2026/openai-eyes-1-2-trillion-valuation-in-pre-ipo-funding-round/",
   "confidence": "high",
   "label": "$852B (2026-03-31)"
  },
  "Perplexity": {
   "valuation_usd_b": 20,
   "as_of": "2025-09",
   "round": "Ronda de crecimiento",
   "raised": "$200M",
   "talks_usd_b": 30,
   "talks_note_es": "Nvidia en conversaciones (ago-2026) para una ronda a más de $30.000M; no cerrada.",
   "talks_note_en": "Nvidia in talks (Aug 2026) for a round above $30B; not closed.",
   "note_es": "Última ronda cerrada confirmada por prensa: $200M a $20.000M (sept-2025); fuentes secundarias citan una extensión a ~$23.000M (ene-2026).",
   "note_en": "Last press-confirmed closed round: $200M at $20B (Sep 2025); secondary sources cite an extension at ~$23B (Jan 2026).",
   "source_url": "https://finance.yahoo.com/news/perplexity-finalizes-20-billion-valuation-232758524.html",
   "talks_source_url": "https://sacra.com/c/perplexity/",
   "confidence": "medium",
   "label": "$20B (2025-09)"
  },
  "PhysicalIntelligence": {
   "valuation_usd_b": 11,
   "as_of": "2026-03",
   "raised": "~$1B",
   "lead": "Founders Fund",
   "status_note": "Rumor de compra por Anthropic (jul-2026) desmentido por su CEO; sigue independiente.",
   "note_es": "Bloomberg (mar-2026) reportó ~$1.000M a más de $11.000M con Founders Fund, Lightspeed, Thrive y Lux; TechCrunch (jul-2026) la describe ya valuada en $11.000M. Ronda previa: $600M a $5.600M (nov-2025).",
   "note_en": "Bloomberg (Mar 2026) reported ~$1B at over $11B with Founders Fund, Lightspeed, Thrive and Lux; TechCrunch (Jul 2026) describes it as valued at $11B. Prior round: $600M at $5.6B (Nov 2025).",
   "source_url": "https://www.bloomberg.com/news/articles/2026-03-27/ex-deepmind-staffers-robotics-startup-in-talks-for-11-billion-valuation",
   "confidence": "medium",
   "label": "$11B (2026-03)"
  },
  "PsiQuantum": {
   "valuation_usd_b": 10.5,
   "as_of": "2026-05",
   "round": "Serie E",
   "raised": "$1.5B",
   "note_es": "Última ronda cerrada: $1.500M a una valuación de $10.500M (may-2026).",
   "note_en": "Last closed round: $1.5B at a $10.5B valuation (May 2026).",
   "source_url": "https://www.smartcompany.com.au/startupsmart/psiquantum-valuation-skyrockets-10-5-billion-1-5-billion-series-e-raise/",
   "confidence": "medium",
   "label": "$10.5B (2026-05)"
  },
  "Runway": {
   "valuation_usd_b": 5.3,
   "as_of": "2026-02-10",
   "round": "Serie E",
   "raised": "$315M",
   "lead": "General Atlantic",
   "note_es": "Última ronda cerrada: Serie E de $315M a una valuación de $5.300M (10-feb-2026).",
   "note_en": "Last closed round: $315M Series E at a $5.3B valuation (Feb 10, 2026).",
   "source_url": "https://techcrunch.com/2026/02/10/ai-video-startup-runway-raises-315m-at-5-3b-valuation-eyes-more-capable-world-models/",
   "confidence": "high",
   "label": "$5.3B (2026-02-10)"
  },
  "SambaNova": {
   "valuation_usd_b": 11,
   "as_of": "2026-07-08",
   "round": "Serie F (primer cierre)",
   "raised": "$1B",
   "lead": "General Atlantic",
   "note_es": "Última ronda cerrada: Serie F de $1.000M a una valuación de $11.000M (8-jul-2026).",
   "note_en": "Last closed round: $1B Series F at an $11B valuation (Jul 8, 2026).",
   "source_url": "https://techcrunch.com/2026/07/08/sambanova-draws-1b-at-11b-valuation-in-series-f-first-close/",
   "confidence": "high",
   "label": "$11B (2026-07-08)"
  },
  "ScaleAI": {
   "valuation_usd_b": 29,
   "as_of": "2025-06",
   "round": "Inversión estratégica (Meta, 49%)",
   "raised": "$14.3B",
   "lead": "Meta Platforms",
   "note_es": "Última marca: Meta invirtió $14.300M por el 49% (jun-2025), valuando la empresa en ~$29.000M; sin ronda posterior.",
   "note_en": "Last mark: Meta invested $14.3B for 49% (Jun 2025), valuing the company at ~$29B; no later round.",
   "source_url": "https://scale.com/blog/scale-ai-announces-next-phase-of-company-evolution",
   "confidence": "medium",
   "label": "$29B (2025-06)"
  },
  "ShieldAI": {
   "valuation_usd_b": 12.7,
   "as_of": "2026-03-26",
   "round": "Serie G",
   "raised": "$2B",
   "lead": "Advent International",
   "note_es": "Última ronda cerrada: Serie G de $2.000M a una valuación de $12.700M (26-mar-2026).",
   "note_en": "Last closed round: $2B Series G at a $12.7B valuation (Mar 26, 2026).",
   "source_url": "https://shield.ai/shield-ai-to-acquire-software-simulation-company-aechelon-and-raise-2b-at-12-7b-valuation/",
   "confidence": "high",
   "label": "$12.7B (2026-03-26)"
  },
  "SiMa": {
   "valuation_usd_b": 1.45,
   "as_of": "2026-09-28",
   "round": "Serie C",
   "raised": "$150M",
   "lead": "Fidelity, Amplify",
   "note_es": "Última ronda cerrada: Serie C de $150M a una valuación de $1.450M (28-sept-2026).",
   "note_en": "Last closed round: $150M Series C at a $1.45B valuation (Sep 28, 2026).",
   "source_url": "https://siliconangle.com/2026/09/28/physical-ai-custom-chip-producer-sima-ai-raises-150m-at-1-45b-valuation/",
   "confidence": "high",
   "label": "$1.45B (2026-09-28)"
  },
  "SierraSpace": {
   "valuation_usd_b": 8,
   "as_of": "2026-03-05",
   "round": "Serie C",
   "raised": "$550M",
   "lead": "LuminArx Capital",
   "note_es": "Última ronda cerrada: Serie C de $550M a una valuación post-money de $8.000M (mar-2026).",
   "note_en": "Last closed round: $550M Series C at an $8B post-money valuation (Mar 2026).",
   "source_url": "https://www.sierraspace.com/press-releases/sierra-space-closes-550-million-in-series-c-round-with-a-valuation-of-8-billion/",
   "confidence": "high",
   "label": "$8B (2026-03-05)"
  },
  "StokSpace": {
   "valuation_usd_b": 10,
   "as_of": "2026-09-08",
   "round": "Serie E",
   "raised": "$1B",
   "lead": "Point72 Ventures, Spark Capital",
   "note_es": "Última ronda: Serie E de $1.000M a una valuación de ~$10.000M (8-sept-2026, según prensa local).",
   "note_en": "Latest round: $1B Series E at ~$10B valuation (Sep 8, 2026, per local press).",
   "source_url": "https://hoodline.com/2026/09/kent-rocket-startup-stoke-space-hits-10-billion-value-after-1-billion-raise/",
   "confidence": "medium",
   "label": "$10B (2026-09-08)"
  },
  "Suno": {
   "valuation_usd_b": 5.4,
   "as_of": "2026-06-03",
   "round": "Ronda de crecimiento",
   "raised": "$400M",
   "lead": "Bond Capital",
   "note_es": "Última ronda cerrada: $400M a una valuación de $5.400M (jun-2026).",
   "note_en": "Last closed round: $400M at a $5.4B valuation (Jun 2026).",
   "source_url": "https://variety.com/2026/digital/news/ai-music-suno-funding-round-400-million-5-4-billion-valuation-1236765727/",
   "confidence": "high",
   "label": "$5.4B (2026-06-03)"
  },
  "TAETechnologies": {
   "valuation_usd_b": 6,
   "as_of": "2025-12-18",
   "round": "Fusión con Trump Media (acuerdo)",
   "raised": "todo en acciones",
   "lead": "Trump Media & Technology Group",
   "status_note": "Fusionándose con Trump Media (NASDAQ: DJT); cierre esperado en 4T-2026.",
   "note_es": "Acordó fusionarse con Trump Media en una operación de más de $6.000M en acciones (18-dic-2025); cierre previsto en 4T-2026.",
   "note_en": "Agreed to merge with Trump Media in an all-stock deal valued at over $6B (Dec 18, 2025); closing targeted for Q4 2026.",
   "source_url": "https://www.cnbc.com/2025/12/18/trump-media-djt-tae-fusion-merger.html",
   "confidence": "medium",
   "label": "$6B (2025-12-18)"
  },
  "Tenstorrent": {
   "valuation_usd_b": 2.7,
   "as_of": "2024-12",
   "round": "Serie D",
   "raised": "$693M",
   "lead": "Samsung Securities y AFW Partners",
   "talks_usd_b": 3.2,
   "talks_note_es": "The Information (nov-2025): negociaba ~$800M liderados por Fidelity a ~$3.000-3.200M; agregadores citan una Serie E de $1.290M (ago-2026) no confirmada por la compañía.",
   "talks_note_en": "The Information (Nov 2025): in talks for ~$800M led by Fidelity at ~$3-3.2B; aggregators cite a $1.29B Series E (Aug 2026) not confirmed by the company.",
   "note_es": "Serie D de más de $693M a una valuación pre-money de $2.000M (~$2.700M post) liderada por Samsung Securities y AFW Partners (dic-2024).",
   "note_en": "Series D of over $693M at a $2B pre-money valuation (~$2.7B post) led by Samsung Securities and AFW Partners (Dec 2024).",
   "source_url": "https://tenstorrent.com/en/newsroom/tenstorrent-closes-693m-of-series-d-funding-led-by-samsung-securities-and-afw-partners",
   "talks_source_url": "https://www.theinformation.com/articles/tenstorrent-nears-3-billion-valuation-fidelity-led-round",
   "confidence": "high",
   "label": "$2.7B (2024-12)"
  },
  "Together_AI": {
   "valuation_usd_b": 8.3,
   "as_of": "2026-07-01",
   "round": "Serie C",
   "raised": "$800M",
   "lead": "Aramco Ventures",
   "note_es": "Última ronda cerrada: $800M a una valuación de $8.300M (1-jul-2026).",
   "note_en": "Last closed round: $800M at an $8.3B valuation (Jul 1, 2026).",
   "source_url": "https://www.businesswire.com/news/home/20260701243402/en/Together-AI-Raises-$800-Million-at-$8.3-Billion-Valuation-to-Make-Frontier-AI-Accessible-to-All",
   "confidence": "high",
   "label": "$8.3B (2026-07-01)"
  },
  "Wayve": {
   "valuation_usd_b": 8.6,
   "as_of": "2026-02-24",
   "round": "Serie D",
   "raised": "~$1.2-1.5B",
   "lead": "Eclipse, Balderton, SoftBank Vision Fund 2",
   "note_es": "Última ronda cerrada: Serie D de ~$1.500M a una valuación post-money de $8.600M (feb-2026).",
   "note_en": "Last closed round: ~$1.5B Series D at an $8.6B post-money valuation (Feb 2026).",
   "source_url": "https://www.cnbc.com/2026/02/24/wayve-fundraise-nvidia-microsoft.html",
   "confidence": "high",
   "label": "$8.6B (2026-02-24)"
  },
  "crusoe-energy": {
   "valuation_usd_b": 30.9,
   "as_of": "2026-09-17",
   "round": "Serie F",
   "raised": "$3.9B",
   "lead": "Atreides, Mubadala Capital, Valor Equity Partners",
   "note_es": "Última ronda cerrada: Serie F de $3.900M a una valuación de $30.900M (17-sept-2026).",
   "note_en": "Last closed round: $3.9B Series F at a $30.9B valuation (Sep 17, 2026).",
   "source_url": "https://www.crusoe.ai/resources/newsroom/crusoe-announces-series-f-funding",
   "confidence": "high",
   "label": "$30.9B (2026-09-17)"
  },
  "dMatrix": {
   "valuation_usd_b": 2,
   "as_of": "2025-11",
   "round": "Serie C",
   "raised": "$275M",
   "lead": "Bullhound Capital, Triatomic Capital, Temasek",
   "note_es": "Última ronda cerrada: Serie C de $275M a una valuación de $2.000M (nov-2025).",
   "note_en": "Last closed round: $275M Series C at a $2B valuation (Nov 2025).",
   "source_url": "https://www.d-matrix.ai/announcements/d-matrix-raises-275-million-to-power-the-age-of-ai-inference/",
   "confidence": "high",
   "label": "$2B (2025-11)"
  },
  "dexterity": {
   "valuation_usd_b": 1.65,
   "as_of": "2025-03-11",
   "round": "Ronda de crecimiento",
   "raised": "$95M",
   "lead": "Lightspeed, Sumitomo",
   "note_es": "Última ronda cerrada: $95M a una valuación de $1.650M (mar-2025).",
   "note_en": "Last closed round: $95M at a $1.65B valuation (Mar 2025).",
   "source_url": "https://www.bloomberg.com/news/articles/2025-03-11/ai-robotics-startup-dexterity-lands-1-65-billion-valuation",
   "confidence": "high",
   "label": "$1.65B (2025-03-11)"
  },
  "fluidstack": {
   "valuation_usd_b": 18,
   "as_of": "2026-09-03",
   "round": "Serie B",
   "raised": "$1.5B",
   "lead": "Jane Street, Situational Awareness",
   "note_es": "Última ronda cerrada: Serie B de ~$1.500M a una valuación de $18.000M (sept-2026).",
   "note_en": "Last closed round: ~$1.5B Series B at an $18B valuation (Sep 2026).",
   "source_url": "https://www.techtimes.com/articles/326746/20260905/fluidstack-closes-15b-revenue-soars-18m-660m-projected-while-owning-zero-chips.htm",
   "confidence": "medium",
   "label": "$18B (2026-09-03)"
  },
  "helsing": {
   "valuation_usd_b": 18,
   "as_of": "2026-07-13",
   "round": "Serie E",
   "raised": "$1.8B",
   "lead": "Dragoneer, Lightspeed y otros",
   "note_es": "Última ronda cerrada: Serie E de $1.800M a una valuación post-money de $18.000M (13-jul-2026).",
   "note_en": "Last closed round: $1.8B Series E at an $18B post-money valuation (Jul 13, 2026).",
   "source_url": "https://www.defensenews.com/global/europe/2026/07/13/helsing-raises-18-billion-in-europes-biggest-defense-startup-round/",
   "confidence": "high",
   "label": "$18B (2026-07-13)"
  },
  "impulse-space": {
   "valuation_usd_b": 4.26,
   "as_of": "2026-06-02",
   "round": "Serie D",
   "raised": "$500M",
   "lead": "137 Ventures, Banner VC",
   "note_es": "Última ronda cerrada: Serie D de $500M a una valuación de $4.260M (2-jun-2026).",
   "note_en": "Last closed round: $500M Series D at a $4.26B valuation (Jun 2, 2026).",
   "source_url": "https://kfgo.com/2026/06/02/impulse-space-raises-500-million-at-4-26-billion-valuation-as-space-investing-surges/",
   "confidence": "high",
   "label": "$4.26B (2026-06-02)"
  },
  "lightning-ai": {
   "valuation_usd_b": 2.5,
   "as_of": "2026-01-21",
   "round": "Fusión con Voltage Park",
   "raised": "n/d",
   "note_es": "Completó la fusión con Voltage Park (21-ene-2026); entidad combinada valuada en más de $2.500M.",
   "note_en": "Completed its merger with Voltage Park (Jan 21, 2026); combined entity valued at over $2.5B.",
   "source_url": "https://www.forbes.com/sites/iainmartin/2026/01/21/ai-startup-merges-with-a-billionaire-backed-data-center-operator-in-25-billion-deal/",
   "confidence": "medium",
   "label": "$2.5B (2026-01-21)"
  },
  "loft-orbital": {
   "valuation_usd_b": 1.0,
   "as_of": "2025-01",
   "round": "Serie C",
   "raised": "$170M",
   "lead": "Tikehau Capital y Axial Partners",
   "note_es": "Serie C de $170M co-liderada por Tikehau y Axial (ene-2025) a una valuación reportada de ~$1.000M.",
   "note_en": "$170M Series C co-led by Tikehau and Axial (Jan 2025) at a reported ~$1B valuation.",
   "source_url": "https://www.bloomberg.com/news/articles/2025-01-14/space-firm-loft-orbital-raises-170-million-to-scale-up-launches",
   "confidence": "medium",
   "label": "$1B (2025-01)"
  },
  "neura-robotics": {
   "valuation_usd_b": 7,
   "as_of": "2026-06-10",
   "round": "Serie C",
   "raised": "hasta $1.4B",
   "lead": "Tether, Qualcomm, Amazon, Nvidia",
   "note_es": "Última ronda cerrada: Serie C de hasta $1.400M a una valuación de ~$7.000M (10-jun-2026, según fuentes).",
   "note_en": "Last closed round: Series C of up to $1.4B at ~$7B valuation (Jun 10, 2026, per sources).",
   "source_url": "https://www.cnbc.com/2026/06/10/neura-robotics-funding-ai-humanoid-robots.html",
   "confidence": "medium",
   "label": "$7B (2026-06-10)"
  },
  "nscale": {
   "valuation_usd_b": 14.6,
   "as_of": "2026-03-09",
   "round": "Serie C",
   "raised": "$2B",
   "lead": "Aker ASA, 8090 Industries",
   "note_es": "Última ronda cerrada: Serie C de $2.000M a una valuación de $14.600M (9-mar-2026).",
   "note_en": "Last closed round: $2B Series C at a $14.6B valuation (Mar 9, 2026).",
   "source_url": "https://www.cnbc.com/2026/03/09/nscale-ai-data-center-nvidia-raise.html",
   "confidence": "high",
   "label": "$14.6B (2026-03-09)"
  },
  "poolside-ai": {
   "valuation_usd_b": 13,
   "as_of": "2026-08",
   "raised": "$1B",
   "lead": "Nvidia",
   "status_note": "No es adquisición: licencia no exclusiva + transferencia de >100 empleados a Nvidia (ago-2026); los $6.000M se repartirán a inversores.",
   "note_es": "Nvidia pagó una licencia no exclusiva de $6.000M y Poolside levantó $1.000M a $12.000M pre-money (~$13.000M post) en ago-2026; más de 100 ingenieros pasan a Nvidia.",
   "note_en": "Nvidia paid a $6B non-exclusive license and Poolside raised $1B at a $12B pre-money (~$13B post) in Aug 2026; 100+ engineers move to Nvidia.",
   "source_url": "https://www.bloomberg.com/news/articles/2026-08-20/nvidia-to-pay-ai-startup-poolside-a-6-billion-license-newcomer-says",
   "confidence": "medium",
   "label": "$13B (2026-08)"
  },
  "reflection-ai": {
   "valuation_usd_b": 27.5,
   "as_of": "2026-04",
   "round": "Serie C",
   "raised": "$2.5B",
   "note_es": "Última ronda cerrada: Serie C de $2.500M a $25.000M pre-money (~$27.500M post-money) (abr-2026).",
   "note_en": "Last closed round: $2.5B Series C at $25B pre-money (~$27.5B post-money) (Apr 2026).",
   "source_url": "https://www.cnbc.com/video/2026/04/23/reflection-ceo-on-ai-race-the-best-open-models-are-coming-from-china.html",
   "confidence": "medium",
   "label": "$27.5B (2026-04)"
  },
  "sakana-ai": {
   "valuation_usd_b": 2.65,
   "as_of": "2025-11",
   "round": "Serie B",
   "raised": "$135M",
   "note_es": "Última ronda cerrada: Serie B de $135M a una valuación de ~$2.650M (nov-2025).",
   "note_en": "Last closed round: $135M Series B at ~$2.65B valuation (Nov 2025).",
   "source_url": "https://sakana.ai/series-b/",
   "confidence": "medium",
   "label": "$2.65B (2025-11)"
  },
  "skild-ai": {
   "valuation_usd_b": 14,
   "as_of": "2026-01-14",
   "round": "Serie C",
   "raised": "$1.4B",
   "lead": "SoftBank",
   "note_es": "Última ronda cerrada: Serie C de $1.400M a una valuación de más de $14.000M (14-ene-2026).",
   "note_en": "Last closed round: $1.4B Series C at a valuation above $14B (Jan 14, 2026).",
   "source_url": "https://www.businesswire.com/news/home/20260114335623/en/Skild-AI-Raises-$1.4B-Now-Valued-Over-$14B",
   "confidence": "high",
   "label": "$14B (2026-01-14)"
  },
  "skydio": {
   "valuation_usd_b": 4.4,
   "as_of": "2026-04",
   "round": "Serie F",
   "raised": "$110M",
   "lead": "Inversores existentes",
   "note_es": "Última ronda cerrada: Serie F de $110M a una valuación de $4.400M (abr-2026).",
   "note_en": "Last closed round: $110M Series F at a $4.4B valuation (Apr 2026).",
   "source_url": "https://dronelife.com/2026/04/28/skydio-series-f-110m-funding-us-manufacturing/",
   "confidence": "medium",
   "label": "$4.4B (2026-04)"
  },
  "tensorwave": {
   "valuation_usd_b": 1.55,
   "as_of": "2026-06-10",
   "round": "Serie B",
   "raised": "$350M",
   "lead": "Magnetar, AMD Ventures",
   "note_es": "Última ronda cerrada: Serie B de $350M a una valuación de $1.550M (10-jun-2026).",
   "note_en": "Last closed round: $350M Series B at a $1.55B valuation (Jun 10, 2026).",
   "source_url": "https://www.businesswire.com/news/home/20260610650010/en/TensorWave-Raises-$350-Million-Series-B-at-$1.55B-Valuation-to-Expand-Global-AMD-Powered-AI-Infrastructure",
   "confidence": "high",
   "label": "$1.55B (2026-06-10)"
  },
  "true-anomaly": {
   "valuation_usd_b": 2.2,
   "as_of": "2026-04-28",
   "round": "Serie D",
   "raised": "$650M",
   "lead": "Eclipse, Riot Ventures",
   "note_es": "Última ronda cerrada: Serie D de $650M a una valuación de $2.200M (28-abr-2026).",
   "note_en": "Last closed round: $650M Series D at a $2.2B valuation (Apr 28, 2026).",
   "source_url": "https://spacenews.com/true-anomaly-raises-650-million-reaching-2-2-billion-valuation/",
   "confidence": "high",
   "label": "$2.2B (2026-04-28)"
  },
  "waabi": {
   "valuation_usd_b": 3.0,
   "as_of": "2026-01",
   "round": "Serie C",
   "raised": "$750M (+ hasta $250M de Uber por hitos)",
   "lead": "Khosla Ventures y G2 Venture Partners",
   "note_es": "Serie C de $750M (ene-2026) co-liderada por Khosla y G2VP, más hasta $250M de Uber; The Globe and Mail reporta valuación de $3.000M (pre-money).",
   "note_en": "$750M Series C (Jan 2026) co-led by Khosla and G2VP, plus up to $250M from Uber; The Globe and Mail reports a $3B (pre-money) valuation.",
   "source_url": "https://www.theglobeandmail.com/business/article-waabi-driverless-truck-raquel-urtasun-750-million-financing-khosla-g2/",
   "confidence": "medium",
   "label": "$3B (2026-01)"
  },
  "world-labs": {
   "valuation_usd_b": 5,
   "as_of": "2026-02-18",
   "round": "Ronda de crecimiento",
   "raised": "$1B",
   "lead": "AMD, Nvidia, Autodesk, Fidelity, Emerson",
   "note_es": "Última ronda cerrada: $1.000M (18-feb-2026) a una valuación reportada de ~$5.000M (no oficial).",
   "note_en": "Last closed round: $1B (Feb 18, 2026) at a reported ~$5B valuation (not official).",
   "source_url": "https://www.bloomberg.com/news/articles/2026-02-18/ai-pioneer-fei-fei-li-s-startup-world-labs-raises-1-billion",
   "confidence": "medium",
   "label": "$5B (2026-02-18)"
  },
  "yotta-data-services": {
   "valuation_usd_b": 3.9,
   "as_of": "2026-07",
   "round": "Pre-IPO",
   "raised": "$150M",
   "lead": "HNIs y family offices",
   "talks_usd_b": 6.0,
   "talks_note_es": "Bloomberg (may-2026): prepara IPO en India de hasta $900M a una valuación cercana a $6.000M; prospecto previsto desde oct-2026.",
   "talks_note_en": "Bloomberg (May 2026): preparing an India IPO of up to $900M at a valuation near $6B; draft prospectus expected from Oct 2026.",
   "note_es": "Levantó $150M en ronda pre-IPO a ₹37.000 crore (~$3.900M) de valuación (jul-2026).",
   "note_en": "Raised $150M in a pre-IPO round at a ₹37,000 crore (~$3.9B) valuation (Jul 2026).",
   "source_url": "https://www.business-standard.com/amp/companies/start-ups/yotta-raises-150-mn-at-37-000-crore-valuation-to-fund-ai-expansion-126070500709_1.html",
   "talks_source_url": "https://www.bloomberg.com/news/articles/2026-05-05/yotta-data-said-to-hire-advisors-for-900-million-india-ipo",
   "confidence": "medium",
   "label": "$3.9B (2026-07)"
  },
  "zipline": {
   "valuation_usd_b": 7.6,
   "as_of": "2026-03",
   "round": "Serie H",
   "raised": "$600M+ (ene) + $200M (mar)",
   "lead": "Valor Equity Partners; Fidelity (ext.)",
   "talks_usd_b": 20,
   "talks_note_es": "Conversaciones (sept-2026, no cerradas) para ~$1.000M a ~$20.000M, liderada por Paradigm.",
   "talks_note_en": "Talks (Sep 2026, not closed) to raise ~$1B at ~$20B, led by Paradigm.",
   "note_es": "Última ronda cerrada: más de $600M (ene-2026) + $200M Serie H (mar-2026) a $7.600M post-money.",
   "note_en": "Last closed round: $600M+ (Jan 2026) plus a $200M Series H (Mar 2026) at $7.6B post-money.",
   "source_url": "https://techcrunch.com/2026/01/21/zipline-charts-drone-delivery-expansion-with-600m-in-new-funding/",
   "talks_source_url": "https://www.bloomberg.com/news/articles/2026-09-16/drone-startup-zipline-in-talks-on-about-1-billion-raise-at-20-billion-valuation",
   "confidence": "high",
   "label": "$7.6B (2026-03)"
  }
 }
};
(function () {
  var PI = window.PREIPO_INTEL || {}, E = window.PRIVATE_VALUATIONS.entries;
  Object.keys(E).forEach(function (id) {
    if (PI[id]) PI[id].valuation = E[id].label;   // la cifra vieja del catálogo deja de circular
  });
})();
