"""core/portfolio_ai.py — ASISTENTE DE CARTERAS (💼 Carteras → 🤖 Asistente).

Pedido (2026-09-30): "que puedas responder preguntas y que te proponga
carteras con AI".

Dos piezas, ambas en /api/portfolio-ai/*:

  POST /ask      preguntas en lenguaje natural (es/en) respondidas con datos de
                 Khipus: el grafo (sector, proveedores/clientes, NRS), mercado
                 en vivo (core.live_caps), claims ACTIVOS de los agentes de
                 investigación (Phase 2, si hay base) y — si se envía una
                 cartera — su composición y su riesgo real
                 (core.risk_report.build_report). La IA solo REDACTA; los
                 números vienen del contexto y el guardián de cifras de
                 core.ai._ai_complete los verifica. Sin IA → respuesta
                 determinista marcada "sin IA".

  POST /propose  cuestionario (objetivo, horizonte, riesgo, monto, temas,
                 exclusiones) → 2-3 carteras candidatas construidas de forma
                 DETERMINISTA: universo = empresas COTIZADAS del grafo filtradas
                 por tema; ranking por señales de calidad (NRS, centralidad en
                 la cadena, tamaño/dato en vivo, postura de los claims);
                 diversificación con topes por nombre/sector/país según el
                 riesgo; pesos por inversa de volatilidad o paridad de riesgo con
                 1 año REAL de precios (core.risk_report.fetch_history); riesgo
                 de la cartera con core.risk_report.compute. La IA escribe el
                 porqué en lenguaje simple usando SOLO esos números.

  GET  /themes   temas (sectores del grafo) con el nº de cotizadas de cada uno.

NUNCA ejecuta órdenes ni promete rendimientos: es una propuesta EDUCATIVA. Crear
la cartera ocurre en el navegador como cartera SIMULADA (kh_portfolios).
"""
import hashlib
import json
import logging
import math
import re
import threading
import time
from collections import OrderedDict, defaultdict
from concurrent.futures import ThreadPoolExecutor, wait
from datetime import datetime, timezone

from flask import Blueprint, jsonify, request

from core.http import _safe_ticker, rate_limit

log = logging.getLogger(__name__)

portfolio_ai_bp = Blueprint('portfolio_ai', __name__, url_prefix='/api/portfolio-ai')

MIN_DAYS = 120            # días de historia común mínimos para dimensionar
POOL_MAX = 36             # empresas cuya historia se descarga por propuesta
HIST_WAIT_S = 25          # tope total de espera de historias
BENCH = 'SPY'
DISCLAIMER = {
    'es': 'Propuesta educativa generada por IA a partir de datos reales; no es asesoría personalizada '
          'ni una recomendación de compra. No se ejecuta nada: si la creas, es una cartera SIMULADA.',
    'en': 'Educational proposal generated by AI from real data; not personalized advice or a buy '
          'recommendation. Nothing is executed: if you create it, it is a SIMULATED portfolio.',
}

GOALS = {'crecimiento': 'crecimiento', 'growth': 'crecimiento',
         'equilibrio': 'equilibrio', 'balanced': 'equilibrio', 'balance': 'equilibrio',
         'defensivo': 'defensivo', 'defensive': 'defensivo'}
HORIZONS = {'lt1': 'lt1', '<1': 'lt1', '0-1': 'lt1', '1-3': '1-3', '3+': '3+', 'gt3': '3+'}
RISKS = {'bajo': 'bajo', 'low': 'bajo', 'medio': 'medio', 'medium': 'medio',
         'alto': 'alto', 'high': 'alto'}

# Topes por nivel de riesgo: nº de nombres, % máx por empresa/sector/país y
# volatilidad anual máxima admitida por nombre (en %, antes del ajuste por plazo).
PROFILES = {
    'bajo':  {'n': 12, 'max_name': 0.12, 'max_sector': 0.30, 'max_country': 0.60, 'max_vol': 45.0},
    'medio': {'n': 10, 'max_name': 0.15, 'max_sector': 0.40, 'max_country': 0.70, 'max_vol': 65.0},
    'alto':  {'n': 8,  'max_name': 0.20, 'max_sector': 0.55, 'max_country': 0.85, 'max_vol': 110.0},
}
HORIZON_VOL_MULT = {'lt1': 0.85, '1-3': 1.0, '3+': 1.15}
# pesos del ranking: calidad (1-NRS/100), tamaño, centralidad, claims, dato en vivo
SCORE_W = {
    'bajo':  {'q': .45, 'size': .25, 'cent': .15, 'res': .10, 'live': .05},
    'medio': {'q': .30, 'size': .20, 'cent': .30, 'res': .15, 'live': .05},
    'alto':  {'q': .15, 'size': .10, 'cent': .45, 'res': .25, 'live': .05},
}

# Temas = sectores del grafo (SECTORS9); 'semis' agrupa los tres de chips.
THEMES = OrderedDict([
    ('semis',        {'es': 'Semiconductores', 'en': 'Semiconductors',
                      'sectors': ['fabricacion', 'diseno', 'equipos']}),
    ('cloud_ia',     {'sectors': ['cloud_ia']}),
    ('infra',        {'sectors': ['infra']}),
    ('energia',      {'sectors': ['energia']}),
    ('espacio',      {'sectors': ['espacio']}),
    ('defensa',      {'sectors': ['defensa']}),
    ('robotica',     {'sectors': ['robotica']}),
    ('materiales',   {'sectors': ['materiales']}),
    ('logistica',    {'sectors': ['logistica']}),
    ('inmobiliario', {'sectors': ['inmobiliario']}),
    ('macro_credito', {'sectors': ['macro_credito']}),
])
_BAD_LISTING = {'acquired', 'defunct', 'merged', 'subsidiary', 'delisted', 'bankrupt', 'private'}

# NRS: MISMA heurística que computeNRS (app.html) con el término de margen
# acotado a [0,20] como la réplica server (ontology/agents.py). Documentado.
_GEO = {'China': 28, 'Taiwan': 25, 'Korea': 15, 'Japan': 12, 'EEUU': 8, 'Europa': 10, 'Israel': 18}
_COUNTRY_NORM = {'estados unidos': 'EEUU', 'eeuu': 'EEUU', 'usa': 'EEUU', 'us': 'EEUU',
                 'japon': 'Japon', 'japón': 'Japon', 'japan': 'Japon',
                 'taiwan': 'Taiwan', 'taiwán': 'Taiwan', 'corea': 'Corea', 'korea': 'Corea',
                 'reino unido': 'ReinoUnido', 'reinounido': 'ReinoUnido', 'uk': 'ReinoUnido',
                 'paises bajos': 'PaisesBajos', 'paisesbajos': 'PaisesBajos', 'china': 'China',
                 'canada': 'Canada', 'canadá': 'Canada', 'alemania': 'Alemania', 'germany': 'Alemania',
                 'francia': 'Francia', 'france': 'Francia', 'russia': 'Russia', 'rusia': 'Russia'}

_CACHE = OrderedDict()     # clave → (ts, valor)
_CACHE_LOCK = threading.Lock()
_CACHE_MAX = 96
_POOL = ThreadPoolExecutor(max_workers=8, thread_name_prefix='pf-ai')


# ── utilidades ───────────────────────────────────────────────────────────────
def _now():
    return datetime.now(timezone.utc).isoformat()


def _cache_get(key, ttl):
    with _CACHE_LOCK:
        e = _CACHE.get(key)
        if e and time.time() - e[0] < ttl:
            _CACHE.move_to_end(key)
            return e[1]
    return None


def _cache_put(key, val):
    with _CACHE_LOCK:
        _CACHE[key] = (time.time(), val)
        _CACHE.move_to_end(key)
        while len(_CACHE) > _CACHE_MAX:
            _CACHE.popitem(last=False)


def _key(*parts):
    return hashlib.sha1(json.dumps(parts, sort_keys=True, default=str).encode()).hexdigest()


def _lang(v):
    return 'en' if str(v or '').lower().startswith('en') else 'es'


def _country(c):
    c = str(c or '').strip()
    return _COUNTRY_NORM.get(c.lower(), c or '?')


def _norm(txt):
    from core.entities import norm
    return norm(txt)


class ValidationError(ValueError):
    def __init__(self, es, en):
        super().__init__(es)
        self.es, self.en = es, en


def _bad(e):
    return jsonify({'error': e.es, 'error_en': e.en, 'code': 'invalid'}), 400


# ── fuentes (inyectables en tests) ───────────────────────────────────────────
def _history(sym):
    """({fecha: precio}, moneda) — 1 año de Yahoo (caché 6 h en risk_report)."""
    from core.risk_report import fetch_history
    return fetch_history(sym, '1y')


def _fx(cur):
    from core.quotes import _fx_to_usd
    return _fx_to_usd(cur)


def _live_caps():
    try:
        from core.live_caps import get_caps
        return get_caps(start=True)
    except Exception:  # noqa: BLE001
        return {'caps': {}, 'as_of': None}


def _claims_for(ids):
    """{entity_id: [claims activos]} de los agentes de Phase 2; {} sin base."""
    ids = [i for i in ids if i][:200]
    if not ids:
        return {}
    try:
        from ontology.db import ontology_available, session_scope
        from research.models import ResearchClaim
        if not ontology_available():
            return {}
        out = defaultdict(list)
        with session_scope() as s:
            rows = (s.query(ResearchClaim)
                    .filter(ResearchClaim.subject_entity_id.in_(ids), ResearchClaim.status == 'active')
                    .order_by(ResearchClaim.confidence.desc()).limit(400).all())
            for c in rows:
                out[c.subject_entity_id].append({
                    'id': c.id, 'stance': c.stance, 'topic': c.topic, 'horizon': c.horizon,
                    'confidence': round(float(c.confidence or 0), 2), 'agent': c.agent_type,
                    'es': (c.statement_es or '')[:240], 'en': (c.statement_en or c.statement_es or '')[:240]})
        return dict(out)
    except Exception as e:  # noqa: BLE001 — la investigación es opcional
        log.info('portfolio_ai: claims no disponibles (%s)', type(e).__name__)
        return {}


def _portfolio_report(positions):
    from core.risk_report import build_report
    return build_report(positions, horizon=10)


# ── grafo ────────────────────────────────────────────────────────────────────
_GRAPH = {'deg': None, 'flow_deg': None, 'sup': None, 'cli': None, 'sectors9': None}
_GRAPH_LOCK = threading.Lock()


def _graph():
    """Grado, proveedores y clientes por id desde el snapshot (1 vez)."""
    with _GRAPH_LOCK:
        if _GRAPH['deg'] is None:
            from core.entities import _SNAPSHOT
            with open(_SNAPSHOT, encoding='utf-8') as fh:
                snap = json.load(fh)
            deg, sup, cli = defaultdict(int), defaultdict(list), defaultdict(list)
            for l in snap.get('links', []):
                s, t = l.get('source'), l.get('target')
                if not s or not t:
                    continue
                deg[s] += 1
                deg[t] += 1
                w = l.get('w') or 1
                sup[t].append((w, s))   # s PROVEE a t
                cli[s].append((w, t))
            try:   # G4d: el NRS usa el grado ESTRUCTURAL (pares de flujo distintos), igual que la app y el MCP
                from ontology.vocabulary import flow_degree
                fdeg = flow_degree(snap.get('links', []))
            except Exception:  # noqa: BLE001
                fdeg = dict(deg)
            _GRAPH.update(deg=dict(deg), flow_deg=fdeg, sup=dict(sup), cli=dict(cli),
                          sectors9=snap.get('sectors9') or {})
        return _GRAPH


def _nodes():
    from core.entities import get_index
    return get_index()['nodos']


def nrs(node, degree):
    from core.world import nrs_concentrated, nrs_geo
    geo = nrs_geo(node.get('country'))
    chain = min(25, degree * 2.5)
    margin = node.get('margin')
    try:
        from core.live_fundamentals import live_margin
        lm = live_margin(node.get('id')) if node.get('id') else None
        margin = lm if lm is not None else margin
    except Exception:  # noqa: BLE001
        pass
    market = max(0, min(20, round((1 - min(1, (margin if margin is not None else 0.15) / 0.4)) * 20)))
    g = str(node.get('growth') or '').lower()
    fundamental = min(15, (10 if node.get('preipo') else 0) + (5 if '🔴' in g else 2 if '🟡' in g else 0))
    conc = 10 if nrs_concentrated(node.get('country')) else 4
    return int(max(0, min(100, round(geo + chain + market + fundamental + conc))))


def sector_label(sec, lang='es'):
    s9 = _graph()['sectors9'].get(sec) or {}
    return (s9.get('en') if lang == 'en' else s9.get('label')) or sec


def theme_label(key, lang='es'):
    th = THEMES.get(key) or {}
    if th.get(lang if lang == 'en' else 'es'):
        return th[lang if lang == 'en' else 'es']
    return sector_label(th.get('sectors', [key])[0], lang)


def universe():
    """Empresas COTIZADAS del grafo aptas para una cartera (ticker válido,
    no adquirida/fusionada/subsidiaria/cerrada, no pre-IPO)."""
    g = _graph()
    out = []
    for nid, n in _nodes().items():
        sym = _safe_ticker((n.get('mkt') or '').strip().upper())
        if not sym or n.get('preipo'):
            continue
        if ((n.get('listing') or {}).get('status') or '') in _BAD_LISTING:
            continue
        deg = g['flow_deg'].get(nid, 0)
        out.append({'id': nid, 'symbol': sym, 'label': n.get('label') or nid,
                    'sector': n.get('sector') or '?', 'cat': n.get('cat') or '',
                    'country': _country(n.get('country')), 'degree': deg, 'nrs': nrs(n, deg)})
    return out


def themes_list(lang='es'):
    counts = defaultdict(int)
    for u in universe():
        counts[u['sector']] += 1
    return [{'key': k, 'label': theme_label(k, lang),
             'count': sum(counts.get(s, 0) for s in v['sectors'])} for k, v in THEMES.items()]


# ── validación ───────────────────────────────────────────────────────────────
def _as_list(v, max_items, max_len):
    if v is None or v == '':
        return []
    if isinstance(v, str):
        v = [x for x in re.split(r'[,;\n]', v)]
    if not isinstance(v, list):
        raise ValidationError('formato de lista inválido', 'invalid list format')
    out = []
    for x in v:
        x = str(x or '').strip()[:max_len]
        if x and x not in out:
            out.append(x)
    if len(out) > max_items:
        raise ValidationError(f'máximo {max_items} elementos', f'at most {max_items} items')
    return out


def validate_propose(body):
    if not isinstance(body, dict):
        raise ValidationError('cuerpo JSON inválido', 'invalid JSON body')
    goal = GOALS.get(str(body.get('goal') or 'equilibrio').lower())
    horizon = HORIZONS.get(str(body.get('horizon') or '1-3').lower())
    risk = RISKS.get(str(body.get('risk') or 'medio').lower())
    if not goal:
        raise ValidationError('objetivo inválido (crecimiento/equilibrio/defensivo)',
                              'invalid goal (growth/balanced/defensive)')
    if not horizon:
        raise ValidationError('horizonte inválido (lt1, 1-3, 3+)', 'invalid horizon (lt1, 1-3, 3+)')
    if not risk:
        raise ValidationError('riesgo inválido (bajo/medio/alto)', 'invalid risk (low/medium/high)')
    try:
        amount = float(body.get('amount_usd'))
    except (TypeError, ValueError):
        raise ValidationError('monto inválido', 'invalid amount') from None
    if not math.isfinite(amount) or amount < 100 or amount > 10_000_000:
        raise ValidationError('el monto debe estar entre 100 y 10.000.000 USD',
                              'amount must be between 100 and 10,000,000 USD')
    themes = [t.lower() for t in _as_list(body.get('themes'), 11, 30)]
    unknown = [t for t in themes if t not in THEMES]
    if unknown:
        raise ValidationError('tema desconocido: ' + ', '.join(unknown), 'unknown theme: ' + ', '.join(unknown))
    exclude = _as_list(body.get('exclude'), 20, 60)
    return {'goal': goal, 'horizon': horizon, 'risk': risk, 'amount_usd': round(amount, 2),
            'themes': themes, 'exclude': exclude, 'lang': _lang(body.get('lang'))}


def _resolve_exclusions(exclude, lang):
    """Cada texto → sector(es), país o empresa. Devuelve (ids, sectores, países, no_reconocidos)."""
    from core.entities import UMBRAL_ESCRITURA, resolve
    ids, secs, ctry, unknown = set(), set(), set(), []
    theme_by_norm = {}
    for k, v in THEMES.items():
        for name in (k, theme_label(k, 'es'), theme_label(k, 'en')):
            theme_by_norm[_norm(name)] = v['sectors']
    for sec in _graph()['sectors9']:
        for name in (sec, sector_label(sec, 'es'), sector_label(sec, 'en')):
            theme_by_norm.setdefault(_norm(name), [sec])
    countries = {_norm(c): c for c in set(_COUNTRY_NORM.values())}
    countries.update({_norm(k): v for k, v in _COUNTRY_NORM.items()})
    for x in exclude:
        nx = _norm(x)
        if nx in theme_by_norm:
            secs.update(theme_by_norm[nx])
        elif nx in countries:
            ctry.add(countries[nx])
        else:
            r = resolve(x, umbral=UMBRAL_ESCRITURA) or resolve(x)
            if r:
                ids.add(r['id'])
            else:
                unknown.append(x)
    return ids, secs, ctry, unknown


# ── matemática (pura, testeable) ─────────────────────────────────────────────
def _std(x):
    if len(x) < 2:
        return 0.0
    m = sum(x) / len(x)
    return math.sqrt(sum((v - m) ** 2 for v in x) / (len(x) - 1))


def _cov(a, b):
    n = len(a)
    if n < 2:
        return 0.0
    ma, mb = sum(a) / n, sum(b) / n
    return sum((x - ma) * (y - mb) for x, y in zip(a, b)) / (n - 1)


def common_returns(histories, syms):
    """(fechas comunes, {sym: retornos diarios}) sobre los días comunes."""
    common = sorted(set.intersection(*(set(histories[s]) for s in syms))) if syms else []
    rets = {s: [histories[s][common[i]] / histories[s][common[i - 1]] - 1.0 for i in range(1, len(common))]
            for s in syms}
    return common, rets


def inverse_vol(vols):
    inv = {s: 1.0 / v for s, v in vols.items() if v and v > 0}
    tot = sum(inv.values())
    return {s: x / tot for s, x in inv.items()} if tot else {}


def risk_parity(cov, syms, iters=600):
    """Contribución al riesgo IGUAL por nombre (ERC), iteración multiplicativa."""
    w = inverse_vol({s: math.sqrt(cov[s][s]) for s in syms})
    if not w:
        return {}
    n = len(syms)
    for _ in range(iters):
        sw = {a: sum(cov[a][b] * w[b] for b in syms) for a in syms}
        pv = sum(w[a] * sw[a] for a in syms)
        if pv <= 0:
            break
        target = pv / n
        new = {a: w[a] * math.sqrt(target / (w[a] * sw[a])) if w[a] * sw[a] > 0 else w[a] for a in syms}
        tot = sum(new.values())
        new = {a: v / tot for a, v in new.items()}
        if max(abs(new[a] - w[a]) for a in syms) < 1e-10:
            w = new
            break
        w = new
    return w


def _waterfill(w, cap):
    w = dict(w)
    for _ in range(len(w) + 2):
        over = {s for s, v in w.items() if v > cap + 1e-12}
        if not over:
            break
        excess = sum(w[s] - cap for s in over)
        for s in over:
            w[s] = cap
        free = [s for s in w if w[s] < cap - 1e-12]
        base = sum(w[s] for s in free)
        if not free or base <= 0:
            break
        for s in free:
            w[s] += excess * w[s] / base
    return w


def apply_caps(w, meta, max_name, max_sector, max_country):
    """Topes por nombre, sector y país redistribuyendo el exceso de forma
    proporcional. Un tope de grupo imposible (p.ej. un solo sector elegido) se
    RELAJA y se informa. Devuelve (pesos normalizados, relajados[])."""
    w = dict(w)
    tot = sum(w.values())
    if tot <= 0:
        return w, []
    w = {s: v / tot for s, v in w.items()}
    relaxed = []
    max_name = max(max_name, 1.0 / len(w))
    for key, cap in (('sector', max_sector), ('country', max_country)):
        # factible solo si los grupos, llenos hasta su tope (y el de nombre), suman ≥ 100 %
        sizes = defaultdict(int)
        for s in w:
            sizes[meta[s][key]] += 1
        if sum(min(cap, k * max_name) for k in sizes.values()) < 1 - 1e-9:
            relaxed.append(key)
    for _ in range(200):
        w = _waterfill(w, max_name)
        moved = False
        for key, cap in (('sector', max_sector), ('country', max_country)):
            if key in relaxed:
                continue
            groups = defaultdict(list)
            for s in w:
                groups[meta[s][key]].append(s)
            gt = {g: sum(w[s] for s in m) for g, m in groups.items()}
            over = {g for g, t in gt.items() if t > cap + 1e-9}
            if not over:
                continue
            excess = sum(gt[g] - cap for g in over)
            for g in over:
                for s in groups[g]:
                    w[s] *= cap / gt[g]
            under = [s for s in w if meta[s][key] not in over and w[s] < max_name - 1e-12]
            base = sum(w[s] for s in under)
            if not under or base <= 0:
                continue
            for s in under:
                w[s] += excess * w[s] / base
            moved = True
        if not moved and max(w.values()) <= max_name + 1e-9:
            break
    tot = sum(w.values())
    w = _waterfill({s: v / tot for s, v in w.items()}, max_name)   # el tope por nombre manda
    for key, cap in (('sector', max_sector), ('country', max_country)):
        gt = defaultdict(float)
        for s, v in w.items():
            gt[meta[s][key]] += v
        if key not in relaxed and max(gt.values()) > cap + 1e-4:
            relaxed.append(key)       # topes combinados incompatibles → se informa
    return w, relaxed


def score(c, prof_w, goal, max_deg, research):
    q = 1 - c['nrs'] / 100.0
    cent = math.sqrt(c['degree'] / max_deg) if max_deg else 0.0
    mcap = c.get('mcap_b')
    size = max(0.0, min(1.0, math.log10(mcap) / math.log10(3000))) if mcap and mcap > 1 else (0.3 if mcap is None else 0.0)
    res = (research.get(c['id']) or {}).get('net', 0.0)
    wq, wc = prof_w['q'], prof_w['cent']
    if goal == 'defensivo':
        wq += 0.10
    elif goal == 'crecimiento':
        wc += 0.10
    return round(wq * q + prof_w['size'] * size + wc * cent + prof_w['res'] * res +
                 prof_w['live'] * (1.0 if c.get('live') else 0.0), 6)


def research_signal(claims):
    """{id: {net ∈ [-1,1], n, neg}} desde claims activos (confianza como peso)."""
    out = {}
    for nid, cl in (claims or {}).items():
        num = den = 0.0
        neg = 0
        for c in cl:
            s = {'positive': 1, 'negative': -1}.get(c.get('stance'), 0)
            num += s * c.get('confidence', 0)
            den += c.get('confidence', 0)
            neg += 1 if s < 0 else 0
        out[nid] = {'net': round(num / den, 3) if den else 0.0, 'n': len(cl), 'neg': neg}
    return out


def _pick(ranked, n, max_sector, max_country):
    """n nombres respetando cuántos caben por sector/país con los topes."""
    per_sec = max(1, int(max_sector * n + 1e-9))
    per_cty = max(1, int(max_country * n + 1e-9))
    # con varios temas elegidos, ninguno se come la cartera: tope por tema
    k_themes = len({c.get('theme') for c in ranked})
    per_th = max(1, math.ceil(n / k_themes)) if k_themes > 1 else n
    chosen, sc, cc, tc = [], defaultdict(int), defaultdict(int), defaultdict(int)
    # pasadas cada vez más laxas: todos los topes → sin tope de tema → sin tope
    # de país → cualquiera (temas estrechos). Así se completa sin romper el
    # tope por sector mientras se pueda.
    for use_th, use_cty, use_sec in ((1, 1, 1), (0, 1, 1), (0, 0, 1), (0, 0, 0)):
        for c in ranked:
            if len(chosen) >= n:
                break
            if c in chosen:
                continue
            if (use_sec and sc[c['sector']] >= per_sec) or (use_cty and cc[c['country']] >= per_cty) or \
               (use_th and tc[c.get('theme')] >= per_th):
                continue
            chosen.append(c)
            sc[c['sector']] += 1
            cc[c['country']] += 1
            tc[c.get('theme')] += 1
    return chosen


# ── construcción ─────────────────────────────────────────────────────────────
def build_proposals(p, history_fn=None, fx_fn=None, caps=None, claims=None):
    """Núcleo DETERMINISTA. `p` = validate_propose(...). Sin IA."""
    history_fn = history_fn or _history
    fx_fn = fx_fn or _fx
    lang = p['lang']
    prof = dict(PROFILES[p['risk']])
    max_vol = prof['max_vol'] * HORIZON_VOL_MULT[p['horizon']]
    excluded = []

    ex_ids, ex_secs, ex_ctry, unknown = _resolve_exclusions(p['exclude'], lang)
    for x in unknown:
        excluded.append({'label': x, 'reason': 'no reconocido (no se aplicó)', 'reason_en': 'not recognized (ignored)'})
    theme_secs = set()
    for t in p['themes']:
        theme_secs.update(THEMES[t]['sectors'])

    caps = caps if caps is not None else (_live_caps().get('caps') or {})
    uni = []
    n_ex = 0
    for c in universe():
        if theme_secs and c['sector'] not in theme_secs:
            continue
        if c['id'] in ex_ids or c['sector'] in ex_secs or c['country'] in ex_ctry:
            n_ex += 1
            continue
        live = caps.get(c['id']) or {}
        theme = next((t for t in p['themes'] if c['sector'] in THEMES[t]['sectors']), None) if p['themes'] else None
        c = dict(c, mcap_b=live.get('mcap_b'), live=bool(live.get('price')), theme=theme)
        uni.append(c)
    if n_ex:
        excluded.append({'label': f'{n_ex}', 'reason': 'empresas excluidas por tu filtro',
                         'reason_en': 'companies excluded by your filter'})
    if len(uni) < 3:
        return {'ok': False, 'error': 'no hay suficientes empresas cotizadas con esos temas/exclusiones',
                'error_en': 'not enough listed companies for those themes/exclusions', 'excluded': excluded}

    claims = claims if claims is not None else _claims_for([c['id'] for c in uni])
    research = research_signal(claims)
    max_deg = max(c['degree'] for c in uni) or 1
    for c in uni:
        c['score'] = score(c, SCORE_W[p['risk']], p['goal'], max_deg, research)
        c['research'] = research.get(c['id'])
    ranked = sorted(uni, key=lambda c: (-c['score'], c['id']))

    # pool diverso: por sector en ronda (así un sector enorme no se lo come todo)
    by_sec = defaultdict(list)
    for c in ranked:
        by_sec[c['sector']].append(c)
    pool, i = [], 0
    while len(pool) < min(POOL_MAX, len(ranked)):
        added = False
        for sec in sorted(by_sec, key=lambda s: -by_sec[s][0]['score']):
            if i < len(by_sec[sec]) and len(pool) < POOL_MAX:
                pool.append(by_sec[sec][i])
                added = True
        i += 1
        if not added:
            break

    # historias reales (paralelo, con tope de tiempo)
    syms = sorted({c['symbol'] for c in pool} | {BENCH})
    futs = {s: _POOL.submit(history_fn, s) for s in syms}
    wait(list(futs.values()), timeout=HIST_WAIT_S)
    hist, fx, curr = {}, {}, {}
    for s, f in futs.items():
        try:
            h, cur = f.result(timeout=0) if f.done() else ({}, None)
        except Exception:  # noqa: BLE001
            h, cur = {}, None
        if len(h or {}) < MIN_DAYS:
            continue
        cur0 = cur or 'USD'
        cur = 'GBP' if cur0 == 'GBp' else cur0.upper()
        rate = fx_fn(cur)
        if not rate:
            continue
        hist[s], fx[s], curr[s] = h, (rate / 100.0 if cur0 == 'GBp' else rate), cur
    bench = hist.pop(BENCH, None)

    ok_pool = []
    for c in pool:
        if c['symbol'] not in hist:
            excluded.append({'node_id': c['id'], 'label': c['label'], 'symbol': c['symbol'],
                             'reason': 'sin historia de precios suficiente (1 año)',
                             'reason_en': 'not enough price history (1 year)'})
            continue
        h = hist[c['symbol']]
        ds = sorted(h)[-253:]
        r = [h[ds[k]] / h[ds[k - 1]] - 1 for k in range(1, len(ds))]
        vol = _std(r) * math.sqrt(252) * 100
        if vol > max_vol:
            excluded.append({'node_id': c['id'], 'label': c['label'], 'symbol': c['symbol'],
                             'reason': f'volatilidad {vol:.0f}% anual > tope {max_vol:.0f}% para tu perfil',
                             'reason_en': f'volatility {vol:.0f}% a year > {max_vol:.0f}% cap for your profile'})
            continue
        ok_pool.append(dict(c, vol=vol))
    if len(ok_pool) < 3:
        return {'ok': False, 'error': 'no hay suficientes datos de precios reales para construir una cartera',
                'error_en': 'not enough real price data to build a portfolio', 'excluded': excluded}

    n = min(prof['n'], len(ok_pool))
    sectors_avail = {c['sector'] for c in ok_pool}
    notes = []
    if n < prof['n']:
        notes.append({'es': f'Solo {n} empresas pasaron los filtros (se buscaban {prof["n"]}).',
                      'en': f'Only {n} companies passed the filters ({prof["n"]} were sought).'})

    variants = [
        ('diversificada', 'Diversificada', 'Diversified', 'inverse_vol',
         sorted(ok_pool, key=lambda c: (-c['score'], c['id']))),
        ('baja_vol', 'Baja volatilidad', 'Low volatility', 'risk_parity',
         sorted(ok_pool, key=lambda c: (c['vol'], -c['score'], c['id']))),
    ]
    if p['risk'] != 'bajo':
        variants.append(('conviccion', 'Convicción en la cadena', 'Supply-chain conviction', 'risk_parity',
                         sorted(ok_pool, key=lambda c: (-(c['degree'] / max_deg + 0.5 * (c['research'] or {}).get('net', 0)),
                                                        -c['score'], c['id']))))
    out, seen = [], set()
    for pid, name_es, name_en, method, ranked_v in variants:
        chosen = _pick(ranked_v, n, prof['max_sector'], prof['max_country'])
        key = frozenset(c['symbol'] for c in chosen)
        if key in seen or len(chosen) < 3:
            continue
        seen.add(key)
        pf = _size_and_measure(pid, name_es, name_en, method, chosen, hist, fx, curr, bench, prof,
                               p['amount_usd'], lang)
        if pf:
            pf['notes'] = notes + pf.get('notes', [])
            out.append(pf)
    if not out:
        return {'ok': False, 'error': 'no se pudo calcular el riesgo con la historia disponible',
                'error_en': 'could not compute risk with the available history', 'excluded': excluded}
    return {'ok': True, 'portfolios': out, 'excluded': excluded, 'universe_n': len(uni),
            'sectors_available': sorted(sectors_avail), 'profile': prof, 'max_vol_pct': round(max_vol, 1)}


def _size_and_measure(pid, name_es, name_en, method, chosen, hist, fx, curr, bench, prof, amount, lang):
    from core.risk_report import compute
    syms = [c['symbol'] for c in chosen]
    common, rets = common_returns(hist, syms)
    if len(common) < MIN_DAYS:
        return None
    vols = {s: _std(rets[s]) for s in syms}
    if method == 'risk_parity':
        cov = {a: {b: _cov(rets[a], rets[b]) for b in syms} for a in syms}
        w0 = risk_parity(cov, syms)
    else:
        w0 = inverse_vol(vols)
    meta = {c['symbol']: c for c in chosen}
    w, relaxed = apply_caps(w0, meta, prof['max_name'], prof['max_sector'], prof['max_country'])
    last = common[-1]
    price_usd = {s: hist[s][last] * fx[s] for s in syms}
    shares = {s: amount * w[s] / price_usd[s] for s in syms}
    sub_hist = {s: {d: hist[s][d] for d in common} for s in syms}
    rep = compute(sub_hist, shares, fx, bench=bench, horizon=10)
    if not rep.get('ok'):
        return None
    rc = {p['symbol']: p for p in rep['positions']}
    positions = []
    for s in sorted(syms, key=lambda x: -w[x]):
        c = meta[s]
        positions.append({'node_id': c['id'], 'symbol': s, 'label': c['label'], 'sector': c['sector'],
                          'sector_label': sector_label(c['sector'], lang), 'country': c['country'],
                          'currency': curr.get(s, 'USD'),
                          'weight': round(w[s], 4), 'usd': round(amount * w[s], 2),
                          'shares': round(shares[s], 6), 'price': round(price_usd[s], 4), 'price_date': last,
                          'vol_ann_pct': round(vols[s] * math.sqrt(252) * 100, 2), 'nrs': c['nrs'],
                          'risk_contrib_pct': (rc.get(s) or {}).get('risk_contrib_pct'),
                          'research': c.get('research')})
    sec_w, cty_w = defaultdict(float), defaultdict(float)
    for pz in positions:
        sec_w[pz['sector']] += pz['weight']
        cty_w[pz['country']] += pz['weight']
    corr = rep['correlation']
    pairs = []
    for i, a in enumerate(corr['symbols']):
        for j in range(i + 1, len(corr['symbols'])):
            v = corr['matrix'][i][j]
            if v is not None:
                pairs.append((v, a, corr['symbols'][j]))
    pairs.sort(reverse=True)
    avg_corr = round(sum(v for v, _, _ in pairs) / len(pairs), 3) if pairs else None
    metrics = {
        'vol_ann_pct': rep['vol_ann_pct'], 'vol_daily_pct': rep['vol_daily_pct'],
        'var95_1d_usd': rep['var95']['hist_1d_usd'], 'var95_1d_pct': rep['var95']['hist_1d_pct'],
        'var99_1d_usd': rep['var99']['hist_1d_usd'], 'cvar95_1d_usd': rep['var95']['cvar_1d_usd'],
        'var95_10d_usd': rep['var95']['hist_nd_usd'],
        'max_drawdown_pct': rep['max_drawdown_pct'], 'beta_spy': rep['beta_spy'],
        'diversification_ratio': rep['diversification_ratio'], 'avg_correlation': avg_corr,
        'n_names': len(positions), 'n_sectors': len(sec_w), 'n_countries': len(cty_w),
        'max_weight_pct': round(max(pz['weight'] for pz in positions) * 100, 2),
        'sector_weights_pct': {k: round(v * 100, 2) for k, v in sorted(sec_w.items(), key=lambda x: -x[1])},
        'country_weights_pct': {k: round(v * 100, 2) for k, v in sorted(cty_w.items(), key=lambda x: -x[1])},
        'avg_nrs': round(sum(pz['nrs'] * pz['weight'] for pz in positions), 1),
        'days': rep['days'], 'from': rep['from'], 'as_of': rep['as_of'], 'amount_usd': amount,
    }
    pf = {'id': pid, 'name': name_en if lang == 'en' else name_es, 'name_es': name_es, 'name_en': name_en,
          'method': method, 'positions': positions, 'metrics': metrics,
          'caps': {'max_name_pct': round(prof['max_name'] * 100), 'max_sector_pct': round(prof['max_sector'] * 100),
                   'max_country_pct': round(prof['max_country'] * 100), 'relaxed': relaxed},
          'top_corr': [{'a': a, 'b': b, 'corr': v} for v, a, b in pairs[:3]], 'notes': []}
    for k in relaxed:
        pf['notes'].append({'es': f'Tope por {"sector" if k == "sector" else "país"} relajado: tus temas no dan '
                                  f'para diversificar más.',
                            'en': f'{"Sector" if k == "sector" else "Country"} cap relaxed: your themes do not '
                                  f'allow more diversification.'})
    pf['risks_es'], pf['risks_en'] = _risks(pf, 'es'), _risks(pf, 'en')
    pf['risks'] = pf['risks_en'] if lang == 'en' else pf['risks_es']
    return pf


def _risks(pf, lang):
    en = lang == 'en'
    m, pos = pf['metrics'], pf['positions']
    lbl = {p['symbol']: p['label'] for p in pos}
    out = []
    top = max(pos, key=lambda p: p.get('risk_contrib_pct') or 0)
    if top.get('risk_contrib_pct') is not None:
        out.append(f'{top["label"]} contributes {top["risk_contrib_pct"]}% of the risk with {round(top["weight"] * 100, 1)}% of the weight.'
                   if en else
                   f'{top["label"]} aporta el {top["risk_contrib_pct"]}% del riesgo con el {round(top["weight"] * 100, 1)}% del peso.')
    sec, sw = next(iter(m['sector_weights_pct'].items()))
    out.append(f'Largest sector: {sector_label(sec, "en")} = {sw}% of the portfolio.' if en else
               f'Sector más grande: {sector_label(sec, "es")} = {sw}% de la cartera.')
    if pf['top_corr']:
        t = pf['top_corr'][0]
        if t['corr'] >= 0.6:
            out.append(f'{lbl.get(t["a"], t["a"])} and {lbl.get(t["b"], t["b"])} move together (correlation {t["corr"]}): '
                       'they tend to fall on the same days.' if en else
                       f'{lbl.get(t["a"], t["a"])} y {lbl.get(t["b"], t["b"])} se mueven juntas (correlación {t["corr"]}): '
                       'suelen caer los mismos días.')
    tw = round(sum(p['weight'] for p in pos if p['country'] in ('Taiwan', 'China')) * 100, 1)
    if tw > 0:
        out.append(f'{tw}% in Taiwan/China: higher geopolitical risk (it raises the NRS).' if en else
                   f'{tw}% en Taiwán/China: mayor riesgo geopolítico (sube el NRS).')
    fxw = round(sum(p['weight'] for p in pos if (p.get('currency') or 'USD') != 'USD') * 100, 1)
    if fxw > 0:
        out.append(f'{fxw}% trades in other currencies: the exchange rate adds risk.' if en else
                   f'{fxw}% cotiza en otras monedas: el tipo de cambio suma riesgo.')
    neg = [p['label'] for p in pos if (p.get('research') or {}).get('neg')]
    if neg:
        out.append(('Research agents have active negative claims on: ' if en else
                    'Los agentes de investigación tienen claims negativos activos sobre: ') + ', '.join(neg[:4]) + '.')
    out.append('Figures come from 1 year of real prices; the past does not guarantee the future.' if en else
               'Las cifras salen de 1 año de precios reales; el pasado no garantiza el futuro.')
    return out


# ── redacción (IA con respaldo determinista) ─────────────────────────────────
def deterministic_rationale(pf, p, lang):
    en = lang == 'en'
    m = pf['metrics']
    names = ', '.join(f'{x["label"]} {round(x["weight"] * 100, 1)}%' for x in pf['positions'][:5])
    themes = ', '.join(theme_label(t, lang) for t in p['themes']) or ('all sectors of the graph' if en else 'todos los sectores del grafo')
    how = ('inverse volatility: the steadier names weigh more' if en else
           'inversa de la volatilidad: las más estables pesan más') if pf['method'] == 'inverse_vol' else \
          ('risk parity: each name contributes a similar share of risk' if en else
           'paridad de riesgo: cada empresa aporta un riesgo parecido')
    why = {
        'diversificada': ('the best ranked by risk score (NRS), size and role in the supply chain, spread across sectors'
                          if en else 'las mejor puntuadas por riesgo (NRS), tamaño y papel en la cadena, repartidas entre sectores'),
        'baja_vol': ('the calmest stocks of the last year among the well-ranked ones' if en else
                     'las acciones más tranquilas del último año entre las bien puntuadas'),
        'conviccion': ('the most connected companies of the supply chain (key suppliers/customers)' if en else
                       'las empresas más conectadas de la cadena de suministro (proveedores/clientes clave)'),
    }.get(pf['id'], '')
    var = f'${m["var95_1d_usd"]:,.2f}'
    if en:
        return (f'Theme: {themes}. We chose {m["n_names"]} listed companies: {why}. Main weights: {names}. '
                f'Sizing by {how}. Estimated annual volatility {m["vol_ann_pct"]}%; on a bad day (1 in 20) '
                f'the loss could exceed {var}. What would change the view: if correlations rise, if the NRS of a '
                f'large name worsens, or if research agents publish negative claims.')
    return (f'Tema: {themes}. Elegimos {m["n_names"]} empresas cotizadas: {why}. Pesos principales: {names}. '
            f'Tamaño por {how}. Volatilidad anual estimada {m["vol_ann_pct"]}%; en un mal día (1 de cada 20) '
            f'la pérdida podría superar {var}. Qué cambiaría la vista: si las correlaciones suben, si empeora el '
            f'NRS de un nombre grande o si los agentes publican claims negativos.')


def _ai_rationales(pfs, p, lang):
    """Una sola llamada para todas las carteras → {id: texto} o {} si no hay IA."""
    from core import ai as _ai
    if not _ai._ai_configured():
        return {}, None
    data = []
    for pf in pfs:
        m = pf['metrics']
        data.append({'id': pf['id'], 'nombre': pf['name'], 'metodo': pf['method'],
                     'posiciones': [{'empresa': x['label'], 'ticker': x['symbol'], 'sector': x['sector_label'],
                                     'pais': x['country'], 'peso_pct': round(x['weight'] * 100, 1),
                                     'usd': x['usd'], 'vol_anual_pct': x['vol_ann_pct'], 'nrs': x['nrs'],
                                     'aporte_riesgo_pct': x['risk_contrib_pct']} for x in pf['positions']],
                     'vol_anual_pct': m['vol_ann_pct'], 'var95_1dia_usd': m['var95_1d_usd'],
                     'caida_maxima_pct': m['max_drawdown_pct'], 'ratio_diversificacion': m['diversification_ratio'],
                     'correlacion_media': m['avg_correlation'], 'beta_sp500': m['beta_spy'],
                     'riesgos': pf['risks']})
    system = ('Eres el asistente educativo de carteras de Khipus Finance AI. Explicas a inversionistas NO expertos, '
              'en lenguaje simple y sin jerga, por qué una cartera ya construida tiene esas empresas y pesos. '
              'Usa SOLO los datos dados (no inventes cifras, precios ni rendimientos). Nunca prometas ganancias ni '
              'digas "compra"/"vende": es una propuesta educativa. Responde en ' +
              ('inglés' if lang == 'en' else 'español') + '.')
    prompt = (f'Perfil del usuario: objetivo {p["goal"]}, horizonte {p["horizon"]} años, riesgo {p["risk"]}, '
              f'monto ${p["amount_usd"]:,.2f} USD, temas {p["themes"] or "todos"}.\n'
              f'Carteras (JSON):\n{json.dumps(data, ensure_ascii=False)}\n\n'
              'Devuelve SOLO un JSON: {"<id>": "<3-5 frases: por qué estas empresas y pesos, los riesgos principales '
              'y qué cambiaría la vista>"} con una entrada por cartera.')
    try:
        text, used = _ai._ai_complete(system, prompt, max_tokens=1400, tier='fast')
        obj = _ai._extract_json(text)
        if isinstance(obj, dict):
            return {k: str(v)[:1500] for k, v in obj.items() if isinstance(v, str) and v.strip()}, used
    except Exception as e:  # noqa: BLE001
        log.warning('portfolio_ai: redacción IA falló (%s)', str(e)[:120])
    return {}, None


def propose(p, history_fn=None, fx_fn=None, caps=None, claims=None, use_ai=True):
    res = build_proposals(p, history_fn=history_fn, fx_fn=fx_fn, caps=caps, claims=claims)
    lang = p['lang']
    if not res.get('ok'):
        return res
    texts, model = (_ai_rationales(res['portfolios'], p, lang) if use_ai else ({}, None))
    for pf in res['portfolios']:
        det = deterministic_rationale(pf, p, lang)
        if texts.get(pf['id']):
            pf['rationale'], pf['rationale_source'], pf['model'] = texts[pf['id']], 'ai', model
        else:
            pf['rationale'], pf['rationale_source'] = det, 'sin IA'
        pf['rationale_deterministic'] = det
    res['disclaimer'] = DISCLAIMER[lang]
    res['disclaimer_es'], res['disclaimer_en'] = DISCLAIMER['es'], DISCLAIMER['en']
    res['as_of'] = _now()
    res['request'] = p
    return res


# ── preguntas (/ask) ─────────────────────────────────────────────────────────
GLOSSARY = [
    (r'diversif', 'Diversificar es repartir tu dinero entre empresas, sectores y países que NO se mueven igual. '
                  'Si una cae, las otras amortiguan. No elimina el riesgo, pero evita que un solo golpe te hunda.',
     'Diversifying means spreading your money across companies, sectors and countries that do NOT move the same way. '
     'If one falls, the others cushion it. It does not remove risk, but it stops a single blow from sinking you.'),
    (r'volatil', 'La volatilidad mide cuánto sube y baja un precio. Anual 20% ≈ un año normal puede moverse ±20%. '
                 'Más volatilidad = más sustos (y también más posibles subidas).',
     'Volatility measures how much a price swings. 20% a year ≈ a normal year may move ±20%. More volatility = '
     'more scares (and also more possible gains).'),
    (r'\bvar\b|valor en riesgo|value at risk', 'El VaR 95% es la pérdida que, según el último año, solo se superó '
                 '1 de cada 20 días. Es una estimación del pasado, no un límite.',
     'VaR 95% is the loss that, based on the last year, was exceeded only 1 day in 20. It is an estimate from the '
     'past, not a limit.'),
    (r'\bnrs\b', 'El NRS (0-100) es el índice de riesgo de Khipus: país, dependencia en la cadena de suministro, '
                 'margen y concentración. Más alto = más frágil.',
     'The NRS (0-100) is the Khipus risk score: country, supply-chain dependency, margin and concentration. '
     'Higher = more fragile.'),
    (r'correl|juntas|together|se mueven', 'La correlación (de -1 a 1) dice si dos acciones se mueven juntas. Cerca '
                 'de 1: caen los mismos días (diversifican poco). Cerca de 0: independientes.',
     'Correlation (from -1 to 1) says whether two stocks move together. Near 1: they fall on the same days (little '
     'diversification). Near 0: independent.'),
    (r'paridad|parity', 'Paridad de riesgo: se dan pesos para que cada empresa aporte un riesgo parecido; las más '
                        'volátiles pesan menos.',
     'Risk parity: weights are set so each company contributes similar risk; the more volatile ones weigh less.'),
    (r'riesg|risk|segur|safe', 'Para algo menos riesgoso: más empresas y sectores, menos peso en cada una, preferir '
                 'volatilidad baja y NRS bajo, y evitar concentrarse en un solo país. Pulsa "Proponme una cartera" '
                 'con riesgo bajo para ver un ejemplo con datos reales.',
     'For something less risky: more companies and sectors, less weight in each, prefer low volatility and low NRS, '
     'and avoid concentrating in one country. Press "Propose a portfolio" with low risk to see an example with '
     'real data.'),
]


def validate_ask(body):
    if not isinstance(body, dict):
        raise ValidationError('cuerpo JSON inválido', 'invalid JSON body')
    q = str(body.get('question') or '').strip()
    if len(q) < 2:
        raise ValidationError('escribe una pregunta', 'write a question')
    if len(q) > 800:
        raise ValidationError('pregunta demasiado larga (máx. 800)', 'question too long (max 800)')
    hist = body.get('history') or []
    if not isinstance(hist, list):
        raise ValidationError('historial inválido', 'invalid history')
    history = []
    for h in hist[-6:]:
        if isinstance(h, dict) and h.get('text'):
            history.append({'role': 'user' if h.get('role') == 'user' else 'assistant',
                            'text': str(h['text'])[:600]})
    positions = []
    pf = body.get('portfolio')
    if pf is not None:
        if not isinstance(pf, dict) or not isinstance(pf.get('positions', []), list):
            raise ValidationError('cartera inválida', 'invalid portfolio')
        if len(pf.get('positions') or []) > 30:
            raise ValidationError('máximo 30 posiciones', 'at most 30 positions')
        for x in pf.get('positions') or []:
            if not isinstance(x, dict):
                continue
            try:
                sh = float(x.get('shares')) if x.get('shares') is not None else None
                usd = float(x.get('usd')) if x.get('usd') is not None else None
            except (TypeError, ValueError):
                raise ValidationError('cantidad inválida en la cartera', 'invalid amount in portfolio') from None
            positions.append({'node_id': str(x.get('node_id') or '')[:120], 'symbol': str(x.get('symbol') or '')[:15],
                              'label': str(x.get('label') or '')[:80], 'shares': sh, 'usd': usd})
    return {'question': q, 'history': history, 'positions': positions, 'lang': _lang(body.get('lang')),
            'portfolio_name': str((pf or {}).get('name') or '')[:80]}


def _entity_context(ids, caps, claims, lang):
    idx_nodes = _nodes()
    g = _graph()
    lines = []
    for nid in ids:
        n = idx_nodes.get(nid) or {}
        deg = g['flow_deg'].get(nid, 0)
        sup = [idx_nodes.get(s, {}).get('label', s) for _, s in sorted(g['sup'].get(nid, []), reverse=True)[:5]]
        cli = [idx_nodes.get(t, {}).get('label', t) for _, t in sorted(g['cli'].get(nid, []), reverse=True)[:5]]
        live = caps.get(nid) or {}
        role = n.get('role_en') if lang == 'en' else n.get('role')
        parts = [f'- {n.get("label") or nid} (id {nid}; ticker {n.get("mkt") or "no cotiza"}; '
                 f'sector {sector_label(n.get("sector"), lang)}; país {n.get("country") or "?"}; '
                 f'NRS {nrs(n, deg)}/100; {deg} vínculos en la cadena)']
        if role:
            parts.append(f'  Rol: {role[:220]}')
        if sup:
            parts.append('  Proveedores clave: ' + ', '.join(sup))
        if cli:
            parts.append('  Clientes clave: ' + ', '.join(cli))
        if live.get('price') is not None:
            parts.append(f'  En vivo: precio {live.get("price")} USD'
                         + (f'; capitalización {live.get("mcap_b")} mil millones USD' if live.get('mcap_b') else '')
                         + (f'; cambio del día {live.get("change_pct")}%' if live.get('change_pct') is not None else ''))
        for c in (claims.get(nid) or [])[:3]:
            parts.append(f'  Claim de agente ({c["agent"]}, {c["stance"]}, confianza {c["confidence"]}, '
                         f'horizonte {c["horizon"]}): {c["en"] if lang == "en" else c["es"]}')
        lines.append('\n'.join(parts))
    return '\n'.join(lines)


def _pair_stats(ids, history_fn=None):
    """Correlación y volatilidad reales (1 año) entre 2-4 cotizadas mencionadas."""
    history_fn = history_fn or _history
    nodes_ = _nodes()
    syms = {}
    for nid in ids:
        s = _safe_ticker((nodes_.get(nid, {}).get('mkt') or '').strip().upper())
        if s:
            syms[s] = nodes_[nid].get('label') or nid
    if len(syms) < 2:
        return None
    futs = {s: _POOL.submit(history_fn, s) for s in list(syms)[:4]}
    wait(list(futs.values()), timeout=15)
    hist = {}
    for s, f in futs.items():
        try:
            h, _cur = f.result(timeout=0) if f.done() else ({}, None)
        except Exception:  # noqa: BLE001
            h = {}
        if len(h or {}) >= MIN_DAYS:
            hist[s] = h
    if len(hist) < 2:
        return None
    ss = sorted(hist)
    common, rets = common_returns(hist, ss)
    if len(common) < MIN_DAYS:
        return None
    vol = {s: round(_std(rets[s]) * math.sqrt(252) * 100, 1) for s in ss}
    pairs = []
    for i, a in enumerate(ss):
        for b in ss[i + 1:]:
            sa, sb = _std(rets[a]), _std(rets[b])
            if sa and sb:
                pairs.append({'a': syms[a], 'b': syms[b], 'corr': round(_cov(rets[a], rets[b]) / (sa * sb), 2)})
    return {'vol': {syms[s]: v for s, v in vol.items()}, 'pairs': pairs, 'days': len(common) - 1,
            'from': common[0], 'to': common[-1]}


def _portfolio_ctx(positions, caps):
    """Composición + reporte de riesgo real de la cartera enviada (caché 30 min)."""
    from core.entities import resolve
    nodes_ = _nodes()
    rows, calc, skipped = [], [], []
    for x in positions:
        nid = x['node_id'] if x['node_id'] in nodes_ else ((resolve(x['symbol'] or x['label'], 85) or {}).get('id'))
        n = nodes_.get(nid) or {}
        sym = _safe_ticker((x['symbol'] or n.get('mkt') or '').strip().upper())
        label = n.get('label') or x['label'] or sym or '?'
        sh = x['shares']
        if (sh is None or sh <= 0) and x['usd'] and nid and (caps.get(nid) or {}).get('price'):
            sh = x['usd'] / caps[nid]['price']
        rows.append({'label': label, 'symbol': sym, 'node_id': nid, 'sector': n.get('sector'),
                     'country': n.get('country'), 'shares': sh})
        if sym and sh and sh > 0:
            calc.append({'symbol': sym, 'shares': sh, 'label': label})
        else:
            skipped.append(label)
    rep = None
    if calc:
        k = _key('pfrep', sorted((c['symbol'], round(c['shares'], 4)) for c in calc))
        rep = _cache_get(k, 1800)
        if rep is None:
            try:
                rep = _portfolio_report(calc)
            except Exception as e:  # noqa: BLE001
                rep = {'ok': False, 'error': type(e).__name__}
            _cache_put(k, rep)
    return rows, rep, skipped


def _portfolio_text(rows, rep, skipped, lang):
    lines = ['CARTERA SELECCIONADA DEL USUARIO (simulada):']
    for r in rows:
        lines.append(f'- {r["label"]} ({r["symbol"] or "no cotiza"}; sector {sector_label(r["sector"], lang) if r["sector"] else "?"}; '
                     f'país {r["country"] or "?"})')
    if rep and rep.get('ok'):
        lines.append(f'Riesgo real (1 año, {rep["days"]} días hasta {rep["as_of"]}): valor {rep["portfolio_value_usd"]} USD; '
                     f'volatilidad anual {rep["vol_ann_pct"]}%; VaR 95% 1 día {rep["var95"]["hist_1d_usd"]} USD '
                     f'({rep["var95"]["hist_1d_pct"]}%); caída máxima {rep["max_drawdown_pct"]}%; '
                     f'beta vs S&P 500 {rep["beta_spy"]}; ratio de diversificación {rep["diversification_ratio"]}.')
        for p in rep['positions'][:8]:
            lines.append(f'  · {p["symbol"]}: peso {p["weight_pct"]}%, vol anual {p["vol_ann_pct"]}%, '
                         f'aporte al riesgo {p["risk_contrib_pct"]}%')
    elif rep:
        lines.append(f'(No se pudo medir el riesgo: {rep.get("error")})')
    if skipped:
        lines.append('Sin cotización (fuera del cálculo): ' + ', '.join(skipped[:8]))
    return '\n'.join(lines)


def _mentioned(question, history):
    from core.entities import resolve
    from core.live_facts import detect_entities
    ids = detect_entities(question, limit=5)
    if not ids:        # "nvidia", "amd" en minúsculas: tokens sueltos por el resolutor
        for tok in re.findall(r'[A-Za-zÀ-ÿ0-9.&-]{3,}', question)[:25]:
            r = resolve(tok, 90)
            if r and r['id'] not in ids:
                ids.append(r['id'])
            if len(ids) >= 5:
                break
    return ids


def _glossary(question, lang):
    ql = question.lower()
    return [(en if lang == 'en' else es) for rx, es, en in GLOSSARY if re.search(rx, ql)]


def ask(a, history_fn=None, caps=None, claims=None):
    lang = a['lang']
    caps = caps if caps is not None else (_live_caps().get('caps') or {})
    ids = _mentioned(a['question'], a['history'])
    pf_ids = []
    rows = rep = None
    skipped = []
    if a['positions']:
        rows, rep, skipped = _portfolio_ctx(a['positions'], caps)
        pf_ids = [r['node_id'] for r in rows if r.get('node_id')]
    claims = claims if claims is not None else _claims_for(ids + pf_ids)
    pair = _pair_stats(ids, history_fn) if len(ids) >= 2 else None
    sources = [{'type': 'graph', 'label': 'Grafo Khipus (proveedores/clientes, NRS)' if lang == 'es'
                else 'Khipus graph (suppliers/customers, NRS)'}]
    ctx = []
    if ids:
        ctx.append('EMPRESAS MENCIONADAS (datos del grafo Khipus):\n' + _entity_context(ids, caps, claims, lang))
        if any((caps.get(i) or {}).get('price') is not None for i in ids):
            sources.append({'type': 'market', 'label': 'Yahoo Finance (en vivo)'})
        nclaims = sum(len(claims.get(i) or []) for i in ids)
        if nclaims:
            sources.append({'type': 'research', 'label': (f'{nclaims} claims de agentes' if lang == 'es'
                                                          else f'{nclaims} agent claims')})
    if pair:
        ctx.append(f'DATOS REALES DE PRECIOS (1 año, {pair["days"]} días, {pair["from"]} → {pair["to"]}):\n' +
                   '\n'.join(f'- correlación diaria {p["a"]} / {p["b"]}: {p["corr"]}' for p in pair['pairs']) + '\n' +
                   '\n'.join(f'- volatilidad anual {k}: {v}%' for k, v in pair['vol'].items()))
        sources.append({'type': 'prices', 'label': 'Yahoo Finance (1 año, precios diarios)' if lang == 'es'
                        else 'Yahoo Finance (1 year, daily prices)'})
    if rows is not None:
        ctx.append(_portfolio_text(rows, rep, skipped, lang))
        sources.append({'type': 'portfolio', 'label': (f'Tu cartera «{a["portfolio_name"]}»' if lang == 'es'
                                                       else f'Your portfolio «{a["portfolio_name"]}»')})
    secs = defaultdict(int)
    for u in universe():
        secs[u['sector']] += 1
    ctx.append('SECTORES DEL GRAFO (nº de cotizadas): ' +
               ', '.join(f'{sector_label(s, lang)} {n}' for s, n in sorted(secs.items(), key=lambda x: -x[1])))
    context = '\n\n'.join(ctx)

    answer, model = None, None
    from core import ai as _ai
    if _ai._ai_configured():
        system = ('Eres el asistente de carteras de Khipus Finance AI para inversionistas NO expertos. '
                  'Responde en ' + ('inglés' if lang == 'en' else 'español') + ', claro y breve (máx. 180 palabras), '
                  'tono educativo, sin jerga (si usas un término, explícalo en una frase). Usa SOLO los datos del '
                  'CONTEXTO para cifras sobre empresas o carteras; si un dato no está, dilo. Nunca prometas '
                  'rendimientos ni des órdenes de comprar/vender; no es asesoría personalizada. Si piden una '
                  'cartera, sugiere el botón "Proponme una cartera" de esta pantalla.')
        convo = '\n'.join(f'{"Usuario" if h["role"] == "user" else "Asistente"}: {h["text"]}' for h in a['history'])
        prompt = (f'CONTEXTO:\n{context}\n\n' + (f'CONVERSACIÓN PREVIA:\n{convo}\n\n' if convo else '') +
                  f'PREGUNTA: {a["question"]}')
        try:
            answer, model = _ai._ai_complete(system, prompt, max_tokens=700, tier='fast')
        except Exception as e:  # noqa: BLE001
            log.warning('portfolio_ai.ask: IA falló (%s)', str(e)[:120])
            answer = None
    if not answer:
        answer = _deterministic_answer(a, ids, caps, claims, pair, rows, rep, lang)
    return {'answer': answer.strip(), 'sources': sources, 'as_of': _now(), 'ai': bool(model),
            'model': model, 'answer_source': 'ai' if model else 'sin IA', 'entities': ids}


def _deterministic_answer(a, ids, caps, claims, pair, rows, rep, lang):
    en = lang == 'en'
    parts = _glossary(a['question'], lang)
    nodes_ = _nodes()
    g = _graph()
    for nid in ids[:3]:
        n = nodes_.get(nid) or {}
        deg = g['flow_deg'].get(nid, 0)
        live = caps.get(nid) or {}
        s = (f'{n.get("label")}: sector {sector_label(n.get("sector"), lang)}, NRS {nrs(n, deg)}/100, '
             f'{deg} {"supply-chain links" if en else "vínculos en la cadena"}')
        if live.get('price') is not None:
            s += f', {"price" if en else "precio"} ${live["price"]}'
        cl = claims.get(nid) or []
        if cl:
            s += (f'; {len(cl)} active agent claims' if en else f'; {len(cl)} claims activos de agentes')
        parts.append(s + '.')
    if pair:
        for p in pair['pairs'][:3]:
            lvl = ('high' if en else 'alta') if p['corr'] >= 0.6 else (('moderate' if en else 'moderada') if p['corr'] >= 0.3
                                                                     else ('low' if en else 'baja'))
            parts.append((f'{p["a"]} and {p["b"]}: daily correlation {p["corr"]} ({lvl}) over the last year.' if en else
                          f'{p["a"]} y {p["b"]}: correlación diaria {p["corr"]} ({lvl}) en el último año.'))
    if rep and rep.get('ok'):
        top = rep['positions'][0] if rep['positions'] else None
        parts.append((f'Your portfolio: annual volatility {rep["vol_ann_pct"]}%, 1-day VaR 95% ${rep["var95"]["hist_1d_usd"]}.'
                      if en else f'Tu cartera: volatilidad anual {rep["vol_ann_pct"]}%, VaR 95% a 1 día ${rep["var95"]["hist_1d_usd"]}.')
                     + ((f' {top["symbol"]} contributes {top["risk_contrib_pct"]}% of the risk.' if en else
                         f' {top["symbol"]} aporta el {top["risk_contrib_pct"]}% del riesgo.') if top else ''))
    if not parts:
        parts.append('I can explain concepts (diversify, volatility, VaR, NRS, correlation), compare companies of the '
                     'graph or analyze your selected portfolio. To get a portfolio built with real data, press '
                     '"Propose a portfolio".' if en else
                     'Puedo explicarte conceptos (diversificar, volatilidad, VaR, NRS, correlación), comparar empresas '
                     'del grafo o analizar tu cartera seleccionada. Para una cartera armada con datos reales, pulsa '
                     '"Proponme una cartera".')
    parts.append('(sin IA — respuesta automática con datos de Khipus; no es asesoría)' if not en else
                 '(no AI — automatic answer with Khipus data; not advice)')
    return '\n\n'.join(parts)


# ── endpoints ────────────────────────────────────────────────────────────────
@portfolio_ai_bp.route('/themes', methods=['GET'])
@rate_limit(240, 3600)
def themes_endpoint():
    lang = _lang(request.args.get('lang'))
    k = _key('themes', lang)
    val = _cache_get(k, 3600)
    if val is None:
        val = {'themes': themes_list(lang), 'as_of': _now()}
        _cache_put(k, val)
    return jsonify(val)


@portfolio_ai_bp.route('/propose', methods=['POST'])
@rate_limit(20, 3600)
def propose_endpoint():
    try:
        p = validate_propose(request.get_json(silent=True))
    except ValidationError as e:
        return _bad(e)
    k = _key('propose', p, datetime.now(timezone.utc).strftime('%Y-%m-%d'))
    hit = _cache_get(k, 1200)
    if hit is not None:
        return jsonify(dict(hit, cached=True))
    try:
        res = propose(p)
    except Exception as e:  # noqa: BLE001
        log.exception('portfolio_ai.propose')
        return jsonify({'error': 'no se pudo construir la propuesta', 'error_en': 'could not build the proposal',
                        'detail': type(e).__name__}), 500
    if not res.get('ok'):
        return jsonify({'error': res.get('error'), 'error_en': res.get('error_en'), 'code': 'no_data',
                        'excluded': res.get('excluded', []), 'portfolios': []}), 422
    _cache_put(k, res)
    return jsonify(res)


@portfolio_ai_bp.route('/ask', methods=['POST'])
@rate_limit(60, 3600)
def ask_endpoint():
    try:
        a = validate_ask(request.get_json(silent=True))
    except ValidationError as e:
        return _bad(e)
    k = _key('ask', a)
    hit = _cache_get(k, 600)
    if hit is not None:
        return jsonify(dict(hit, cached=True))
    try:
        res = ask(a)
    except Exception as e:  # noqa: BLE001
        log.exception('portfolio_ai.ask')
        return jsonify({'error': 'no se pudo responder', 'error_en': 'could not answer',
                        'detail': type(e).__name__}), 500
    _cache_put(k, res)
    return jsonify(res)
