"""core/portfolio_advisor.py — COMITÉ DE CARTERA: analiza una cartera completa y
da ACCIONES CONCRETAS como consejo (reducir, vender, añadir, diversificar).

Pedido (2026-10-02, Fabrizio): "que el comité pueda analizar carteras, no solo
empresas, y que te dé acciones concretas, como quitar una posición o reducir
riesgo o adquirir otra posición, a modo de consejo, que advierta que es una IA,
pero que sí lo haga; quiero que una persona sin experiencia pueda usar esta app
y tener carteras de acuerdo a sus expectativas".

Cómo decide (todo AUDITABLE; la IA solo explica en lenguaje simple):
  1. RIESGO MEDIDO con precios reales (core/risk_report): peso, volatilidad,
     contribución al riesgo, correlaciones, máxima caída, VaR.
  2. PERFIL del inversionista (conservador / moderado / agresivo): topes por
     posición y por sector y volatilidad objetivo.
  3. INVESTIGACIÓN de los agentes (convicción por empresa, research/committee.board).
  4. REGLAS fijas → acciones: concentración, riesgo desproporcionado, convicción
     negativa, sector concentrado, volatilidad por encima del perfil, pares muy
     correlacionados, posiciones con convicción alta y poco peso, y candidatas
     para diversificar (de la Pizarra, en sectores que no tienes).
Cada acción trae: qué hacer, de cuánto a cuánto (% y USD), por qué (con la
cifra que lo justifica) y prioridad. Nada se ejecuta: aplicar en una cartera
simulada es un clic; en una cuenta real pasa por el bróker con tu PIN.
"""
import logging
import math
from datetime import datetime, timezone

log = logging.getLogger('khipu')

PROFILES = {
    'conservador': {'max_position': 12.0, 'max_sector': 30.0, 'target_vol': 14.0, 'max_dd': 15.0,
                    'es': 'Conservador', 'en': 'Conservative'},
    'moderado': {'max_position': 20.0, 'max_sector': 40.0, 'target_vol': 20.0, 'max_dd': 25.0,
                 'es': 'Moderado', 'en': 'Moderate'},
    'agresivo': {'max_position': 30.0, 'max_sector': 60.0, 'target_vol': 30.0, 'max_dd': 40.0,
                 'es': 'Agresivo', 'en': 'Aggressive'},
}
DISCLAIMER_ES = ('Consejo generado por un sistema de IA con datos públicos y reglas fijas. Es educativo: no es '
                 'asesoría personalizada de un profesional, no conoce toda tu situación y puede equivocarse. '
                 'Ninguna acción se ejecuta sin que tú la confirmes.')
DISCLAIMER_EN = ('Advice generated by an AI system from public data and fixed rules. It is educational: it is not '
                 'personalized advice from a professional, it does not know your whole situation and it can be '
                 'wrong. No action is executed unless you confirm it.')


def _f(v, d=None):
    try:
        x = float(v)
        return x if math.isfinite(x) else d
    except (TypeError, ValueError):
        return d


def _resolve_positions(positions):
    """[{symbol|id, shares|usd, label?, cost_usd?}] → [{entity_id, symbol, label, sector, country, shares, usd}]"""
    from core.entities import resolve
    from core.semantic import _load_snapshot
    snap = _load_snapshot()
    out = []
    for p in (positions or [])[:30]:
        if not isinstance(p, dict):
            continue
        key = str(p.get('id') or p.get('nodeId') or p.get('symbol') or '').strip()
        if not key:
            continue
        r = resolve(key[:120])
        nid = r['id'] if r else None
        n = snap['by_id'].get(nid) or {}
        sym = (p.get('symbol') or n.get('mkt') or '').strip().upper() or None
        out.append({'entity_id': nid, 'symbol': sym, 'label': p.get('label') or n.get('label') or key,
                    'sector': n.get('sector'), 'country': n.get('country'),
                    'shares': _f(p.get('shares')), 'usd': _f(p.get('usd')),
                    'cost_usd': _f(p.get('cost_usd'))})
    return out


def _board_index():
    try:
        from ontology.db import ontology_available, session_scope
        if not ontology_available():
            return {}, []
        from research.committee import board
        with session_scope() as s:
            b = board(s, limit=80)
        return {x['entity_id']: x for x in b['items']}, b['items']
    except Exception as e:  # noqa: BLE001
        log.info('portfolio_advisor: pizarra no disponible (%s)', type(e).__name__)
        return {}, []


def _sector_label(sec, lang):
    try:
        from core.portfolio_ai import sector_label
        return sector_label(sec, lang)
    except Exception:  # noqa: BLE001
        return sec or '—'


def analyze(positions, profile=None, lang='es', risk_fn=None, board_fn=None, cash_usd=0.0):
    """Devuelve el análisis completo (sin IA). risk_fn/board_fn inyectables (tests)."""
    es = not str(lang).startswith('en')
    prof_key = (profile or {}).get('risk') if isinstance(profile, dict) else None
    prof_key = prof_key if prof_key in PROFILES else 'moderado'
    P = PROFILES[prof_key]
    pos = _resolve_positions(positions)
    if not pos:
        return {'ok': False, 'error_code': 'no_positions',
                'error': 'La cartera no tiene posiciones reconocibles.' if es else 'The portfolio has no recognizable positions.'}
    listed = [p for p in pos if p['symbol'] and (p['shares'] or p['usd'])]
    if risk_fn is None:
        from core.risk_report import build_report as risk_fn
    rep = risk_fn([{'symbol': p['symbol'], 'shares': p['shares'], 'usd': p['usd'], 'label': p['label']}
                   for p in listed], horizon=10) if listed else {'ok': False, 'error_code': 'no_positions'}
    if not rep.get('ok'):
        return {'ok': False, 'error_code': rep.get('error_code') or 'data_unavailable',
                'error': rep.get('error') or ('No pude medir el riesgo con precios reales.' if es else
                                              'Could not measure risk with real prices.'),
                'excluded': rep.get('excluded', [])}
    bidx, bitems = (board_fn or _board_index)()
    by_sym = {p['symbol']: p for p in listed}
    total = float(rep['portfolio_value_usd']) + max(0.0, _f(cash_usd, 0.0))
    rows = []
    for rp in rep['positions']:
        meta = by_sym.get(rp['symbol'], {})
        b = bidx.get(meta.get('entity_id')) or {}
        w = rp['value_usd'] / total * 100 if total else 0
        rows.append({**rp, 'weight_pct': round(w, 2), 'entity_id': meta.get('entity_id'), 'label': meta.get('label') or rp['symbol'],
                     'sector': meta.get('sector'), 'country': meta.get('country'),
                     'conviction': b.get('overall_conviction'), 'best_for': b.get('best_for'),
                     'best_against': b.get('best_against'), 'memo': b.get('memo'),
                     'cost_usd': meta.get('cost_usd')})
    corr = rep.get('correlation') or {}
    syms, mat = corr.get('symbols') or [], corr.get('matrix') or []

    actions, n = [], 0

    def act(kind, row, to_pct, prio, why_es, why_en, facts=None):
        nonlocal n
        n += 1
        frm = row['weight_pct'] if row else 0.0
        delta_usd = round((to_pct - frm) / 100 * total, 2)
        actions.append({'id': f'A{n}', 'kind': kind, 'symbol': row['symbol'] if row else None,
                        'entity_id': row['entity_id'] if row else None, 'label': row['label'] if row else None,
                        'from_pct': round(frm, 2), 'to_pct': round(to_pct, 2), 'delta_usd': delta_usd,
                        'priority': prio, 'why_es': why_es, 'why_en': why_en, 'facts': facts or []})

    seen = set()
    # 1) convicción negativa de los analistas
    for r in rows:
        c = r['conviction']
        if c is not None and c <= -35:
            act('sell', r, 0.0, 1,
                f"Los analistas son claramente negativos con {r['label']} (convicción {c:+.0f}/100). Considera salir.",
                f"The analysts are clearly negative on {r['label']} (conviction {c:+.0f}/100). Consider exiting.",
                [f'convicción {c:+.0f}'])
            seen.add(r['symbol'])
        elif c is not None and c <= -15 and r['weight_pct'] > P['max_position'] / 2:
            act('reduce', r, round(r['weight_pct'] / 2, 2), 2,
                f"Convicción negativa ({c:+.0f}) y un peso relevante ({r['weight_pct']:.1f} %): reduce a la mitad mientras se aclara.",
                f"Negative conviction ({c:+.0f}) with a relevant weight ({r['weight_pct']:.1f}%): halve it until it clears up.",
                [f'convicción {c:+.0f}', f"peso {r['weight_pct']:.1f} %"])
            seen.add(r['symbol'])
    # 2) concentración por posición
    for r in rows:
        if r['symbol'] in seen:
            continue
        if r['weight_pct'] > P['max_position'] * 1.1:
            act('reduce', r, P['max_position'], 1 if r['weight_pct'] > P['max_position'] * 1.6 else 2,
                f"{r['label']} pesa {r['weight_pct']:.1f} % de tu cartera; para un perfil {P['es'].lower()} lo prudente es hasta {P['max_position']:.0f} %.",
                f"{r['label']} is {r['weight_pct']:.1f}% of your portfolio; for a {P['en'].lower()} profile the prudent cap is {P['max_position']:.0f}%.",
                [f"peso {r['weight_pct']:.1f} %"])
            seen.add(r['symbol'])
        elif r['risk_contrib_pct'] > 25 and r['risk_contrib_pct'] > 2 * r['weight_pct']:
            to = round(max(r['weight_pct'] * 0.6, 1.0), 2)
            act('reduce', r, to, 2,
                f"{r['label']} es {r['weight_pct']:.1f} % del dinero pero aporta {r['risk_contrib_pct']:.0f} % del riesgo (se mueve mucho: {r['vol_ann_pct']:.0f} % al año).",
                f"{r['label']} is {r['weight_pct']:.1f}% of the money but drives {r['risk_contrib_pct']:.0f}% of the risk (it moves a lot: {r['vol_ann_pct']:.0f}% a year).",
                [f"contribución al riesgo {r['risk_contrib_pct']:.0f} %", f"volatilidad {r['vol_ann_pct']:.0f} %"])
            seen.add(r['symbol'])
    # 3) sector concentrado
    by_sec = {}
    for r in rows:
        by_sec.setdefault(r['sector'] or '—', []).append(r)
    sectors = []
    for sec, rs in by_sec.items():
        wsum = sum(x['weight_pct'] for x in rs)
        sectors.append({'sector': sec, 'label': _sector_label(sec, lang), 'weight_pct': round(wsum, 2), 'n': len(rs)})
        if wsum > P['max_sector'] * 1.1 and len(rows) > 1:
            big = max(rs, key=lambda x: x['weight_pct'])
            if big['symbol'] not in seen:
                excess = wsum - P['max_sector']
                to = round(max(big['weight_pct'] - excess, 0.0), 2)
                lab = _sector_label(sec, lang)
                act('reduce', big, to, 2,
                    f"El sector «{lab}» ocupa {wsum:.0f} % de tu cartera (tope sugerido {P['max_sector']:.0f} %). Recortar {big['label']} reparte el riesgo.",
                    f"The “{lab}” sector is {wsum:.0f}% of your portfolio (suggested cap {P['max_sector']:.0f}%). Trimming {big['label']} spreads the risk.",
                    [f'sector {wsum:.0f} %'])
                seen.add(big['symbol'])
    sectors.sort(key=lambda x: -x['weight_pct'])
    # 4) pares muy correlacionados
    pairs = []
    for i, a in enumerate(syms):
        for j in range(i + 1, len(syms)):
            v = mat[i][j] if i < len(mat) and j < len(mat[i]) else None
            if v is not None and v >= 0.8:
                pairs.append((v, a, syms[j]))
    pairs.sort(reverse=True)
    rows_by_sym = {r['symbol']: r for r in rows}
    for v, a, b in pairs[:2]:
        ra, rb = rows_by_sym.get(a), rows_by_sym.get(b)
        if not ra or not rb or (ra['weight_pct'] + rb['weight_pct']) < P['max_position']:
            continue
        small = min((ra, rb), key=lambda x: x['weight_pct'])
        if small['symbol'] in seen:
            continue
        act('consolidate', small, round(small['weight_pct'] / 2, 2), 3,
            f"{ra['label']} y {rb['label']} se mueven casi igual (correlación {v:.2f}): tener las dos no diversifica. Considera reducir {small['label']}.",
            f"{ra['label']} and {rb['label']} move almost alike (correlation {v:.2f}): holding both does not diversify. Consider trimming {small['label']}.",
            [f'correlación {v:.2f}'])
        seen.add(small['symbol'])
    # 5) convicción alta con poco peso → aumentar
    for r in rows:
        c = r['conviction']
        if r['symbol'] in seen or c is None:
            continue
        if c >= 35 and r['weight_pct'] < P['max_position'] / 2:
            to = round(min(P['max_position'] * 0.75, r['weight_pct'] * 2 + 2), 2)
            act('add', r, to, 3,
                f"Los analistas ven fuerte a {r['label']} (convicción {c:+.0f}) y hoy pesa solo {r['weight_pct']:.1f} %.",
                f"The analysts like {r['label']} (conviction {c:+.0f}) and it is only {r['weight_pct']:.1f}% today.",
                [f'convicción {c:+.0f}'])
    # 6) volatilidad por encima del perfil → diversificar con candidatas
    vol, mdd = rep.get('vol_ann_pct') or 0, rep.get('max_drawdown_pct') or 0
    held = {r['entity_id'] for r in rows}
    held_sec = {r['sector'] for r in rows}
    cands = [x for x in bitems if x['entity_id'] not in held and x['overall_conviction'] >= 25]
    cands.sort(key=lambda x: (x.get('entity_id') and (x['entity_id'] in held), -x['overall_conviction']))
    diversifiers = []
    from core.semantic import _load_snapshot
    snap = _load_snapshot()
    for x in cands:
        n_ = snap['by_id'].get(x['entity_id']) or {}
        if not n_.get('mkt'):
            continue
        if n_.get('sector') in held_sec and len(diversifiers) < 1:
            continue
        diversifiers.append({'entity_id': x['entity_id'], 'label': x['label'], 'symbol': n_.get('mkt'),
                             'sector': n_.get('sector'), 'sector_label': _sector_label(n_.get('sector'), lang),
                             'conviction': x['overall_conviction'],
                             'why': ((x.get('best_for') or {}).get('text_es' if es else 'text_en'))})
        if len(diversifiers) >= 3:
            break
    if vol > P['target_vol'] * 1.2 or len(rows) < 4:
        for d in diversifiers[:2]:
            n += 1
            to = round(min(P['max_position'] / 2, 8.0), 2)
            actions.append({'id': f'A{n}', 'kind': 'buy_new', 'symbol': d['symbol'], 'entity_id': d['entity_id'],
                            'label': d['label'], 'from_pct': 0.0, 'to_pct': to, 'delta_usd': round(to / 100 * total, 2),
                            'priority': 3,
                            'why_es': (f"Para diversificar ({'tu cartera se mueve ' + format(vol, '.0f') + ' % al año, más que el ' + format(P['target_vol'], '.0f') + ' % de tu perfil' if vol > P['target_vol'] * 1.2 else 'tienes pocas posiciones'}): "
                                       f"{d['label']} ({d['sector_label']}), convicción de los analistas {d['conviction']:+.0f}."),
                            'why_en': (f"To diversify ({'your portfolio moves ' + format(vol, '.0f') + '% a year, above your profile’s ' + format(P['target_vol'], '.0f') + '%' if vol > P['target_vol'] * 1.2 else 'you hold few positions'}): "
                                       f"{d['label']} ({d['sector_label']}), analysts' conviction {d['conviction']:+.0f}."),
                            'facts': [f"convicción {d['conviction']:+.0f}"]})
    actions.sort(key=lambda a: (a['priority'], -abs(a['delta_usd'])))

    # salud vs perfil
    issues = 0
    issues += 1 if vol > P['target_vol'] * 1.2 else 0
    issues += 1 if abs(mdd) > P['max_dd'] else 0
    issues += sum(1 for a in actions if a['priority'] == 1)
    issues += 1 if any(s['weight_pct'] > P['max_sector'] * 1.1 for s in sectors) else 0
    score = max(0, min(100, 100 - issues * 18 - sum(6 for a in actions if a['priority'] == 2)))
    if score >= 75:
        v_es, v_en, tone = 'Tu cartera está alineada con tu perfil.', 'Your portfolio fits your profile.', 'good'
    elif score >= 45:
        v_es, v_en, tone = 'Tu cartera es algo más arriesgada de lo que dijiste que quieres.', 'Your portfolio is somewhat riskier than you said you want.', 'warn'
    else:
        v_es, v_en, tone = 'Tu cartera es bastante más arriesgada que tu perfil: revisa las acciones prioritarias.', 'Your portfolio is much riskier than your profile: review the priority actions.', 'bad'
    perf = None
    cost = sum(r['cost_usd'] or 0 for r in rows)
    if cost > 0 and all(r['cost_usd'] for r in rows):
        val = sum(r['value_usd'] for r in rows)
        perf = {'cost_usd': round(cost, 2), 'value_usd': round(val, 2), 'pnl_usd': round(val - cost, 2),
                'pnl_pct': round((val / cost - 1) * 100, 2)}
    return {
        'ok': True, 'generated_at': datetime.now(timezone.utc).isoformat(), 'lang': 'es' if es else 'en',
        'profile': {'key': prof_key, 'label': P['es'] if es else P['en'], **{k: v for k, v in P.items() if k not in ('es', 'en')}},
        'health': {'score': score, 'tone': tone, 'verdict': v_es if es else v_en},
        'kpis': {'value_usd': round(total, 2), 'cash_usd': round(max(0.0, _f(cash_usd, 0.0)), 2),
                 'vol_ann_pct': vol, 'max_drawdown_pct': mdd, 'var95_1d_pct': (rep.get('var95') or {}).get('hist_1d_pct'),
                 'var95_1d_usd': (rep.get('var95') or {}).get('hist_1d_usd'), 'beta_spy': rep.get('beta_spy'),
                 'return_ann_pct': rep.get('return_ann_pct'), 'n_positions': len(rows),
                 'diversification_ratio': rep.get('diversification_ratio')},
        'performance': perf, 'positions': rows, 'sectors': sectors, 'actions': actions[:8],
        'diversifiers': diversifiers, 'correlated_pairs': [{'a': a, 'b': b, 'corr': v} for v, a, b in pairs[:5]],
        'excluded': rep.get('excluded', []) + [{'symbol': p['label'], 'reason': 'sin ticker cotizado o sin cantidad'}
                                                for p in pos if p not in listed],
        'as_of': rep.get('as_of'), 'source': rep.get('source'),
        'disclaimer': DISCLAIMER_ES if es else DISCLAIMER_EN,
    }


def explain(analysis, lang='es'):
    """Explicación en lenguaje simple (IA, con guardián de cifras) o determinista."""
    es = analysis.get('lang', lang) == 'es'
    acts = analysis.get('actions') or []
    k = analysis['kpis']
    facts = [f"Valor {k['value_usd']} USD; volatilidad anual {k['vol_ann_pct']} %; máxima caída {k['max_drawdown_pct']} %; "
             f"VaR 95 % 1 día {k['var95_1d_pct']} % ({k['var95_1d_usd']} USD); perfil {analysis['profile']['label']} "
             f"(tope por posición {analysis['profile']['max_position']} %, volatilidad objetivo {analysis['profile']['target_vol']} %)."]
    for r in analysis['positions']:
        facts.append(f"{r['label']} ({r['symbol']}): peso {r['weight_pct']} %, volatilidad {r['vol_ann_pct']} %, "
                     f"aporta {r['risk_contrib_pct']} % del riesgo, convicción {r['conviction'] if r['conviction'] is not None else 'sin investigación'}.")
    for a in acts:
        facts.append(f"{a['id']}: {a['kind']} {a['label']} de {a['from_pct']} % a {a['to_pct']} % ({a['delta_usd']} USD) — {a['why_es']}")
    sys_ = ('Eres el comité de cartera de Khipus Finance AI y le hablas a un inversionista SIN experiencia. '
            'Explica en 4-7 frases simples, sin jerga (o explicándola), qué tal está su cartera frente a su perfil y '
            'por qué las acciones propuestas (cítalas por su id A1, A2…) reducen riesgo o mejoran la cartera. '
            'No inventes acciones nuevas ni cifras: usa SOLO los datos dados. Cierra recordando que es un consejo '
            'de IA y que él decide. Responde en ' + ('español.' if es else 'English.'))
    try:
        from core import ai
        from core.ai_usage import ai_context
        if ai._ai_configured():
            with ai_context('comite_cartera'):
                text, model = ai._ai_complete(sys_, '\n'.join(facts), max_tokens=700, tier='deep')
            if text and text.strip():
                return {'text': text.strip(), 'ai': True, 'model': model}
    except Exception as e:  # noqa: BLE001
        log.info('portfolio_advisor.explain: %s', str(e)[:120])
    top = acts[:3]
    if es:
        t = f"{analysis['health']['verdict']} "
        if top:
            t += 'Lo más importante: ' + ' '.join(f"({a['id']}) {a['why_es']}" for a in top)
        else:
            t += 'No vemos cambios urgentes; revisa de nuevo cuando cambien los precios o la investigación.'
        t += ' Es un consejo automático: tú decides.'
    else:
        t = f"{analysis['health']['verdict']} "
        if top:
            t += 'Most important: ' + ' '.join(f"({a['id']}) {a['why_en']}" for a in top)
        else:
            t += 'No urgent changes; check again when prices or research change.'
        t += ' This is automated advice: you decide.'
    return {'text': t, 'ai': False, 'model': None}
